### ISSUE TITLE
在小米mix2上底部的虚拟按钮栏变成了黑色·

### ISSUE THREAD

**Issue by chenyusheng** [QMUI/QMUI_Android#103]
### 运行环境 ###

- [x] 设备型号：如：小米 MIX2 
- [x] 设备系统版本：如 `Android 7.1`
- [x] Gradle 版本：如 `2.3.2`
- [x] QMUI Android 版本：`1.0.4`

### 具体问题描述 ###
底部按钮栏变黑色
在没有使用qmui之前是白色的
#### 问题截图 ####
![image](https://user-images.githubusercontent.com/11496107/33920230-cbb563be-dff7-11e7-8293-e02d75d22bb4.png)

![image](https://user-images.githubusercontent.com/11496107/33920162-72f2f3cc-dff7-11e7-883c-92bfa567ae0a.png)

**Comment by cgspine** [comment]
小米 mix 的 navbar 颜色应该与 theme 的有关， QMUI Theme继承自 Theme.AppCompat.Light，在这个theme 下它是黑色的，你可以根据 https://dev.mi.com/console/doc/detail?pId=1160 用 setNavigationBarColor 设置 navbar 的颜色，这个方法虽然5.0就存在了，但很多国产机不能根据背景色改
 icon 颜色。所以也只能对小米调用浅色

**Comment by chenyusheng** [comment]
在theme设置了NavigationBarColor就生效了
