### ISSUE TITLE
QMUIDialog问题？

### ISSUE THREAD

**Issue by WO555O** [QMUI/QMUI_Android#105]
内容过多的时候不能往下滑动，比如MessageDialogBuilder、MenuDialogBuilder、CheckableDialogBuilder、MultiCheckableDialogBuilder，造成后面内容无法查看操作；最底部的操作按钮（取消、确定）好想也在最下面，无法查看到和点击！请问是我哪里没设置好吗？

**Comment by cgspine** [comment]
fix in version [1.0.5](https://github.com/QMUI/QMUI_Android/releases/tag/1.0.5)

**Comment by l455202325** [comment]
1.0.5 version 在哪里？什么时候更新？

**Comment by cgspine** [comment]
在 gradle 里修改依赖：compile 'com.qmuiteam:qmui:1.0.5'
