### ISSUE TITLE
引入项目，直接不能运行

### ISSUE THREAD

**Issue by DickyQie** [QMUI/QMUI_Android#107]
写的太复杂了，搞了一天都不能运行。

**Comment by cgspine** [comment]
http://qmuiteam.com/android/page/start.html
有修改theme吗？

**Comment by DickyQie** [comment]
Error:(44, 13) 错误: 找不到符号
符号:   类 QDWidgetContainer
位置: 类 QDDataManager

**Comment by DickyQie** [comment]
我的引入：
    compile 'com.android.support:appcompat-v7:24.2.+'
    compile 'com.jakewharton:butterknife:8.4.0'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.4.0'
    compile 'com.qmuiteam:qmui:1.0.4'

    debugCompile 'com.squareup.leakcanary:leakcanary-android:1.5'
    releaseCompile 'com.squareup.leakcanary:leakcanary-android-no-op:1.5'
    testCompile 'com.squareup.leakcanary:leakcanary-android-no-op:1.5'

**Comment by DickyQie** [comment]
建议还是写简单点吧！至少能让开发者都能看懂

**Comment by cgspine** [comment]
你直接更改的QD或者copy了QD的代码? QDWidgetContainer 和 QDDataManager 都是 QD 项目才会用到的

**Comment by DickyQie** [comment]
没有啊，复制你项目里面的

**Comment by cgspine** [comment]
复制代码时不应该复制QDDataManager相关的东西吧，那是QD项目管理widget用的

**Comment by DickyQie** [comment]
你的fragment里面很多Fragment都用到了QDDataManager  的
mQDItemDescription = QDDataManager.getInstance().getDescription(this.getClass());
这行代码，我才复制的，要删掉吗？

**Comment by cgspine** [comment]
要，那是去拿qmui widget title数据的，你的业务应该不需要

**Comment by NicodeLee** [comment]
Demo是复杂点，但是使用还是直接看http://qmuiteam.com/android/page/document.html 就行
不影响。

**Comment by ZhouKanZ** [comment]
今天也尝试使用了QMUI，我按照QMUI开始使用上面的介绍,第三条不太明白，我需要将你们项目里面的
item都复制过去然后改写么？

主题：
![image](https://user-images.githubusercontent.com/16540479/34149870-8bdca916-e4e1-11e7-9449-f3caab8bb603.png)


异常：
![image](https://user-images.githubusercontent.com/16540479/34149850-703c8780-e4e1-11e7-99d0-834a504d92d3.png)

帮忙看看是哪里不对

**Comment by cgspine** [comment]
1.  文档第三点是你需要更改组件样式时需要覆写，只覆写你需要改的item，如果不需要改，那就不用覆写
2. 推荐使用 QMUI.Compat theme
3. 你的 crash 是因为你 showDialog时用了 ApplicationContext。Dialog的展示是只能用Activity的Context的

**Comment by ZhouKanZ** [comment]
代码我是直接复制你们项目里面的，用的就是activity的

**Comment by cgspine** [comment]
截一下你的Dialog show 的代码？

**Comment by ZhouKanZ** [comment]
我找到原因了，我的项目里面有多个styles.xml文件，我当时改的时候 只改了一个value下的 所以导致不能使用，主题侵入的方式 还是不太好 我原本的一些样式 改没了

**Comment by cgspine** [comment]
恩，主题侵入有它存在的问题，也有其便利性。对于新一点的项目还好，基本上都是用了compat包，改起来很方便，而旧的项目引入就会修改到很多地方。

**Comment by DickyQie** [comment]
我clone 了代码要如何才能运行

**Comment by cgspine** [comment]
用 Android Studio 打开后有何异常？

**Comment by progremmer-wu** [comment]
Error:(4, 0) For input string: ""

导入直接爆了这个错 怎么改

**Comment by cgspine** [comment]
可以看 #93
