### ISSUE TITLE
QMUITopBar高度问题

### ISSUE THREAD

**Issue by leeyun** [QMUI/QMUI_Android#109]
### 运行环境 ###

- [x] 设备型号：`Nexus 6p`
- [x] 设备系统版本： `Android 8.0`
- [x] Gradle 版本： `3.0.1`
- [x] QMUI Android 版本：`1.0.4`

### 具体问题描述 ###
请问设置了
` QMUIStatusBarHelper.translucent(this);`
的情况下状态栏变成透明的，但是QMUITopBar高度固定，是否可以做到自适呢？还是说只能手动填充一个状态栏高度的view。
xml如下
`<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    >

  <com.qmuiteam.qmui.widget.QMUITopBar
      android:id="@+id/topbar"
      android:layout_width="match_parent"
      android:layout_height="?attr/qmui_topbar_height"
      />
</RelativeLayout>`

#### 问题截图 ####
![image](https://user-images.githubusercontent.com/11530379/33985360-51398ee0-e0f5-11e7-83e8-ef01d8025c1b.png)

**Comment by cgspine** [comment]
使用QMUITopBarLayout， 然后layout_height=wrap_content可以解决这个问题

**Comment by leeyun** [comment]
谢谢。
