### ISSUE TITLE
QMUIPullRefreshLayout刷新箭头异常

### ISSUE THREAD

**Issue by zzwdream** [QMUI/QMUI_Android#11]
### 运行环境 ###

- [x] 设备型号：如：`vivo`
- [x] 设备系统版本：如 `Android 5.1`
- [x] Gradle 版本：如 `2.2.3`
- [x] QMUI Android 版本：`1.0.0`

### 具体问题描述 ###
QMUIPullRefreshLayout在刷新过程中，再次下拉的话，会导致箭头显示异常。

**Comment by pcqpcq** [comment]
![image](https://user-images.githubusercontent.com/1411571/29923817-5da5ccf8-8e8d-11e7-8e74-40488136d9ff.png)

三星s4也一样，目测和设备没关系。
装的是示例apk

**Comment by cgspine** [comment]
1.0.1 版本 fix 这个问题，请更新
