### ISSUE TITLE
建议删除库中AndroidManifest中的 application中的@label属性

### ISSUE THREAD

**Issue by guiying712** [QMUI/QMUI_Android#110]
> Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@label value=(@string/name) from AndroidManifest.xml:8:9-45
  	is also present at [com.qmuiteam:qmui:1.0.4] AndroidManifest.xml:9:18-50 value=(@string/app_name).
  	Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:5:5-13:19 to override.

**Comment by cgspine** [comment]
delete in version [1.0.5](https://github.com/QMUI/QMUI_Android/releases/tag/1.0.5)
