### ISSUE TITLE
QMUIRoundButton木有水波纹效果吗？

### ISSUE THREAD

**Issue by tpnet** [QMUI/QMUI_Android#112]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

**Comment by leeyun** [comment]
自己配啊，我看demo里是没加，新增一个value-21然后添加点击效果就了

**Comment by tpnet** [comment]
@leeyun  我有设置了qmui_backgroundColor和qmui_borderColor的，，应该怎么设置水波汶呢
