### ISSUE TITLE
QMUIDialog还有点小问题

### ISSUE THREAD

**Issue by WO555O** [QMUI/QMUI_Android#114]
1.0.5中解决了MenuBaseDialogBuilder 的子类构建的 dialog 在内容列表过长时被截断的问题，但是消息类型的对话框如MessageDialogBuilder等，在Message消息文本过多的时候还是会被截断！这些好像是直接继承的QMUIDialogBuilder。

**Comment by l455202325** [comment]
1.0.5版本在哪里？

**Comment by cgspine** [comment]
1.0.6 版本修复了这个问题
