### ISSUE TITLE
QMUITabSegment的tab设置icon的位置为Bottom时不显示

### ISSUE THREAD

**Issue by hanqingkai** [QMUI/QMUI_Android#116]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.0.4`

### 具体问题描述 ###
QMUITabSegment的tab设置icon的位置为Bottom时不显示，其他方向都可以正常设置，不知道是bug还是我没设置对，只能在xml中设置，java中貌似icon设置方向的方法都是private
#### 问题截图 ####
![screenshot_2017-12-18-17-55-02](https://user-images.githubusercontent.com/9988660/34100363-236cd848-e41d-11e7-8cc6-213cfb96e485.png)

**Comment by cgspine** [comment]
![image](https://user-images.githubusercontent.com/7828876/34237792-8df21fe8-e639-11e7-8a5c-21639e74dff5.png)
在xml中设置，目前 release 的版本还不支持 java set

**Comment by cgspine** [comment]
1.0.6版本修复了这个问题
