### ISSUE TITLE
TopBar右侧设置两个Button怎么设置啊。还有TabSegment怎么设置ICON方向。翻了好久没翻到。望解答~

### ISSUE THREAD

**Issue by theoneee** [QMUI/QMUI_Android#122]
### 运行环境 ###

- [x] 设备型号：如：`PRO6`
- [x] 设备系统版本：如 `Android 7.1.1`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.0.4`

### 具体问题描述 ###
TopBar右侧设置两个Button怎么设置啊。
还有TabSegment怎么设置ICON方向。
Popup没箭头情况下的偏移设置无效。
还是我设置错了，
新手翻了好久没翻到。望解答~

**Comment by cgspine** [comment]
1. TopBar addRightImageButton/addRightTextButton 可以重复调用，添加多个button
2. TabSegment 目前 release 的版本只能通过 xml 里设置 qmui_tab_icon_position
3.  你是怎么设置偏移的？ 需要在show之前设置

**Comment by theoneee** [comment]
mListPopup.setAnimStyle(QMUIPopup.ANIM_GROW_FROM_RIGHT);
                mListPopup.setPositionOffsetX(10);
                mListPopup.setPopupTopBottomMinMargin(10);
                mListPopup.show(v);

您看是这样设置吗。是不是我设置错了啊。我点开Popup看只有这几个是设置偏移的。但是设置了没效果。

**Comment by cgspine** [comment]
你offset了10px，在3倍屏幕下就是3.3dp。是不是太太小了看不出来？

**Comment by theoneee** [comment]
这样啊 ，那我多点试试

**Comment by theoneee** [comment]
我把三角去掉了。设置Y的偏移无效。

**Comment by cgspine** [comment]
这应该是一个bug，去掉三角形要设置 DIRECTION_NONE， 这个不合理， 暂时你可以用一个hack一点的方式解决这个问题
![image](https://user-images.githubusercontent.com/7828876/34284022-fe981d08-e709-11e7-9e07-c6faa030068e.png)
子类重写的方式去掉箭头， mPreferredDirection 依旧用 DIRECTION_BOTTOM 或 DIRECTION_TOP

**Comment by theoneee** [comment]
好的  非常感谢。

**Comment by jetox** [comment]
> ### 运行环境
> * [x]  设备型号：如：`PRO6`
> * [x]  设备系统版本：如 `Android 7.1.1`
> * [x]  Gradle 版本：如 `2.3.0`
> * [x]  QMUI Android 版本：`1.0.4`
> 
> ### 具体问题描述
> TopBar右侧设置两个Button怎么设置啊。
> 还有TabSegment怎么设置ICON方向。
> Popup没箭头情况下的偏移设置无效。
> 还是我设置错了，
> 新手翻了好久没翻到。望解答~
> 
> #### 问题截图
> #### 异常日志（堆栈）

请问，你右侧添加两个button的问题解决了么
