### ISSUE TITLE
QMUI，在锤子手机上测试，状态栏黑色字体无法生效。用的腾讯优测，锤子M1L；

### ISSUE THREAD

**Issue by PantomZ** [QMUI/QMUI_Android#124]
### 运行环境 ###

- [x] 设备型号：如：`锤子手机M1L`
- [x] 设备系统版本：如 `Android 6.0.1`
- [x] Gradle 版本：如 `-`
- [x] QMUI Android 版本：`1.0.5`

### 具体问题描述 ###
QMUI，在锤子手机上测试，状态栏黑色字体无法生效。用的腾讯优测，锤子M1L；
操作过程:锤子M1L，6.0.1，安装QUMI1.0.5，进入QMUIStatusBarHelper,"设置状态栏黑色字体与图标"。无法变成黑色

**Comment by theoneee** [comment]
Flyme   MIUI  支持黑色字体与图表

Smartisan？ 支持？

**Comment by cgspine** [comment]
android 6.0 以上官方支持黑色字体与icon。 可能是优测上的效果与真机不相符合，也可能是锤子M1L并没有支持 android6.0 的这一功能

**Comment by PantomZ** [comment]
嗯。
