### ISSUE TITLE
关于沉浸式部分。有些场景没有顾全到。

### ISSUE THREAD

**Issue by PantomZ** [QMUI/QMUI_Android#126]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

### 具体问题描述 ###
关于沉浸式部分。在一个activity,多个按钮切换fragment的场景中。不同fragment切换不同主题色。例如：白色背景，状态栏黑色字体；深色背景，状态栏白色字体之间的切换。

**Comment by cgspine** [comment]
状态栏背景和字体都由fragment控制就好了吧。activity 的 contentView 不要 fitSystemWindow，fragment container 使用 QMUIWindowInsetLayout

**Comment by PantomZ** [comment]
好的。了解
