### ISSUE TITLE
GroupListView

### ISSUE THREAD

**Issue by theoneee** [QMUI/QMUI_Android#127]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

### 具体问题描述 ###
 Msg = groupListView.createItemView("系统消息");
 Msg.setImageDrawable(ContextCompat.getDrawable(this, R.mipmap.orange_notice));
希望左边的ImageDrawable固定大小，还有至于右边的文字当内容过多时距离左边的距离要远一点，最好和右边一样。
#### 问题截图 ####

![qq 20171222160120](https://user-images.githubusercontent.com/32156330/34290270-66406452-e731-11e7-83cd-3afb73811390.png)
![qq 20171222160203](https://user-images.githubusercontent.com/32156330/34290288-8009db52-e731-11e7-8e68-e2c3244bbb95.png)

**Comment by theoneee** [comment]
啥意思啊。更新吗。收纳这个意见了已经更新了吗。 @cgspine

**Comment by cgspine** [comment]
提交了右边文字间距过长，与左边title没有间隙的修改。
