### ISSUE TITLE
TopBar Separator

### ISSUE THREAD

**Issue by theoneee** [QMUI/QMUI_Android#128]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

### 具体问题描述 ###
这个分割线的颜色个高度怎么设置啊。好像没找到这个。
希望TopBar中间可以加入搜索框，底部增加进度条。
#### 问题截图 ####
![qq 20171223111546](https://user-images.githubusercontent.com/32156330/34316536-14a52806-e7d3-11e7-97ac-09f131a511dc.png)
![qq 20171223111621](https://user-images.githubusercontent.com/32156330/34316537-187b8222-e7d3-11e7-815a-0e4a5c48f8bd.png)

**Comment by cgspine** [comment]
如果是theme里配置分隔线颜色和高度的话，需要重写下面这个item
![image](https://user-images.githubusercontent.com/7828876/34317938-ccdb875e-e7f5-11e7-9ebc-52532464a37f.png)

TopBar本质是一个 RelativeLayout，所以你可以添加子 view 来做 进度条 和 搜索框，例如
![image](https://user-images.githubusercontent.com/7828876/34317952-3ac680a2-e7f6-11e7-9a02-b8e14dba5566.png)

**Comment by theoneee** [comment]
非常感谢。
