### ISSUE TITLE
Android Studio3.0下找不到资源文件，希望能尽快处理

### ISSUE THREAD

**Issue by luoqqsh** [QMUI/QMUI_Android#13]
compile('com.qmuiteam:qmui:1.0.0', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
一把这句话复制进去gradle sync后报资源文件找不到，什么东西都调用不了。我看你的gradle版本应该是androidstudio2.x的版本吧，以下错误是3.0beta2的版本上报的错，也是目前最新版本的androidstudio，我认为应该只要是3.0的版本都会有这个问题
Information:Gradle tasks [clean, :app:generateDebugSources, :app:generateDebugAndroidTestSources, :app:mockableAndroidJar]
/Users/gxxing/.gradle/caches/transforms-1/files-1.1/qmui-1.0.0.aar/75118861afd1d7ab436aee5f56ec7a00/res/values/values.xml
Error:(628, 5) style attribute '@android:attr/windowEnterAnimation' not found
Error:(628, 5) style attribute '@android:attr/windowExitAnimation' not found
Error:(632, 5) style attribute '@android:attr/windowEnterAnimation' not found
Error:(632, 5) style attribute '@android:attr/windowExitAnimation' not found
Error:(636, 5) style attribute '@android:attr/windowEnterAnimation' not found
Error:(636, 5) style attribute '@android:attr/windowExitAnimation' not found
Error:(641, 5) style attribute '@android:attr/windowEnterAnimation' not found
Error:(641, 5) style attribute '@android:attr/windowExitAnimation' not found
Error:(645, 5) style attribute '@android:attr/windowEnterAnimation' not found
Error:(645, 5) style attribute '@android:attr/windowExitAnimation' not found
Error:(649, 5) style attribute '@android:attr/windowEnterAnimation' not found
Error:(649, 5) style attribute '@android:attr/windowExitAnimation' not found
Error:/Users/gxxing/Documents/zuoye/shunfengche/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:2749 style attribute '@android:attr/windowEnterAnimation' not found
Error:/Users/gxxing/Documents/zuoye/shunfengche/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:2753 style attribute '@android:attr/windowEnterAnimation' not found
Error:/Users/gxxing/Documents/zuoye/shunfengche/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:2757 style attribute '@android:attr/windowEnterAnimation' not found
Error:/Users/gxxing/Documents/zuoye/shunfengche/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:2762 style attribute '@android:attr/windowEnterAnimation' not found
Error:/Users/gxxing/Documents/zuoye/shunfengche/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:2766 style attribute '@android:attr/windowEnterAnimation' not found
Error:/Users/gxxing/Documents/zuoye/shunfengche/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:2770 style attribute '@android:attr/windowEnterAnimation' not found
Error:failed linking references
Error:java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.AaptException: AAPT2 link failed:
Error:com.android.builder.internal.aapt.AaptException: AAPT2 link failed:
Error:Execution failed for task ':app:processDebugResources'.
> Failed to execute aapt
Information:BUILD FAILED in 3s
Information:22 errors
Information:0 warnings
Information:0 warnings

**Comment by luoqqsh** [comment]
这个是报错的截图
![image](https://user-images.githubusercontent.com/12087574/29961007-8495face-8f30-11e7-8fe8-148493042540.png)

**Comment by cgspine** [comment]
在 1.0.1 版本已经 fix 了这个问题，请更新

**Comment by thimper** [comment]
在android studio 3.0.1 ，Gradle Sync 是还是会出这个错，用的是1.0.6 版本，再编译一下就好了。请问这是什么原因
