### ISSUE TITLE
GroupListView  ACCESSORY_TYPE_SWITCH

### ISSUE THREAD

**Issue by theoneee** [QMUI/QMUI_Android#131]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

### 具体问题描述 ###
设置开关值是这样设置吗，怎么设置了没效果。。

 Work = groupListView.createItemView("开启接收");
        Work.setSelected(UserInfo.getWorkStatus()); // 这里设置了 true 也是没反应的
        Work.setImageDrawable(ContextCompat.getDrawable(this, R.mipmap.orange_update));
        Work.setAccessoryType(QMUICommonListItemView.ACCESSORY_TYPE_SWITCH);
        Work.getSwitch().setOnCheckedChangeListener(new CompoundButton.OnCheckedChangeListener() {
            @Override
            public void onCheckedChanged(CompoundButton buttonView, boolean isChecked) {
                if(isChecked){
                    //开启了接收
                    Work.setText("关闭接收");
                    UserInfo.setWorkStatus(true);
                }else{
                    //关闭接收
                    Work.setText("开启接收");
                    UserInfo.setWorkStatus(false);

                }
            }
        });

**Comment by cgspine** [comment]
```
Work = groupListView.createItemView("开启接收");
Work.setImageDrawable(ContextCompat.getDrawable(this, R.mipmap.orange_update));
Work.setAccessoryType(QMUICommonListItemView.ACCESSORY_TYPE_SWITCH);
// 需要在 setAccessoryType 之后设置以保证 getSwitch() 不为 null
Work.getSwitch().setChecked(UserInfo.getWorkStatus())
```
