### ISSUE TITLE
关于dialog不能被用户触发关闭

### ISSUE THREAD

**Issue by HappyImp** [QMUI/QMUI_Android#132]
Tipdialog不能通过用户触发返回键关闭，这样的体验很不好，有时候网络状态不好的时候，用户不愿等待那么长时间，要返回退出，却因为dialog不得不杀死应用。

**Comment by cgspine** [comment]
好的，目前设置了setCancelable 为 true，我改一下

**Comment by HappyImp** [comment]
@cgspine 我在baseactivity做了监听，让dialog与activity一起销毁

**Comment by cgspine** [comment]
目前也不要做监听吧，直接在构造出TipDialog后调用tipDialog.setCancelable(true)就可以了。

**Comment by HappyImp** [comment]
好的，知道了
