### ISSUE TITLE
依赖了等级过高的 support 库

### ISSUE THREAD

**Issue by Null-Ouwenjie** [QMUI/QMUI_Android#133]
### 运行环境 ###

- [x] 设备型号：如：`MOTO X`
- [x] 设备系统版本：如 `Android 6.0`
- [x] Gradle 版本：如 `4.1`
- [x] QMUI Android 版本：`1.0.6`

### 具体问题描述 ###
我项目中依赖的 support 库是 25.4.0，使用 QMUI 1.0.4 是正常的，但是在升级到 1.0.6 之后，编译报错了。
提示：Error:(13, 5) No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.

导致该问题的原因可能是 QMUI 使用了过高的 support 库造成的？
因为我使用 
compile ('com.qmuiteam:qmui:1.0.6') {
        exclude group:'com.android.support'
    }
编译是不会报错的。
我建议作为一个 UI 库，即使依赖了一些 support 库，这些库可以提示用户去添加这些依赖，而不是库本身去依赖一个特定的版本。
将你们的 compile 改成 compileOnly 会好点，support 依赖由 APP 的开发者自己添加。

**Comment by cgspine** [comment]
谢谢建议，之前并不知道compile，所以提供给使用者是覆写依赖（参见：[QMUI Q & A](https://github.com/QMUI/QMUI_Android/wiki/QMUI-Q-&-A)）。可以改成 compileOnly 的方式，但是我们会用到 appcompat-v7 的 Theme， 所以它没办法用 compileOnly 的 方式
