### ISSUE TITLE
QMUITabSegment和viewpager绑定死了。感觉不太灵活。

### ISSUE THREAD

**Issue by PantomZ** [QMUI/QMUI_Android#136]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

### 具体问题描述 ###
QMUITabSegment和viewpager绑定死了。感觉不太灵活。

**Comment by cgspine** [comment]
不调用 setupWithViewPager 而调用 notifyDataChanged， 就和 viewpager 没有关系了
