### ISSUE TITLE
使用带有输入框的dialog的时候希望能增加一个设置最大长度的方法

### ISSUE THREAD

**Issue by tx123456** [QMUI/QMUI_Android#138]
### 运行环境 ###

- [ ] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

#### 异常日志（堆栈） ####

希望能在dialog里面增加一个setmaxlength的方法设置输入框的最大输入长度

**Comment by cgspine** [comment]
```
EditTextDialogBuilder builder = new EditTextDialogBuilder(context)
InputFilter[] inputFilters = {new LengthFilter(maxLength)}
builder.getEditText().setInputFilter(inputFilters)
```
Android 中输入框最大输入长度用 InputFilter 实现就好

**Comment by tx123456** [comment]
纠正一下，最后是setFilters而不是setInputFilter
