### ISSUE TITLE
QMUITabSegment

### ISSUE THREAD

**Issue by theoneee** [QMUI/QMUI_Android#139]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

### 具体问题描述 ###
当根据不同的登陆账号（身份）add不同数量的Tab（mTabSegment.addTab（））
某一个身份只有两三个Tab,普通模式即可.
而有的身份有五六个Tab(此时已经超过父容器了，应该用MODE_SCROLLABLE。
如果说直接用MODE_SCROLLABLE，则当Tab数量少的时候宽度无法MATCH_PARENT,无法平分。
我现在做的就是根据不同的身份去查看是否要不要用MODE_SCROLLABLE。
但是觉得这样会很麻烦。
因为我以前用v4的TabLayout直接设置滚动模式，然后就可以根据不同数量的Tab自动匹配是平分还是滚动。
我觉得TabSegment也应该这样。

**Comment by theoneee** [comment]
当根据不同身份是否要用MODE_SCROLLABLE时，在小尺寸的手机是需要，但是在大尺寸的时候就不是了。

**Comment by theoneee** [comment]
@cgspine

**Comment by cgspine** [comment]
设定一个值，当剩余空间存在并且小于这个值就平分空间，当剩余空间大于这个值或者没有剩余空间就保持正常的layout?

**Comment by theoneee** [comment]
TabSegment的宽带小于屏幕的宽度就平分。大于就滚动。

**Comment by theoneee** [comment]
TabSegment的宽度怎么获取啊。@cgspine

**Comment by cgspine** [comment]
它是一个view，一样可以getWidth 和 getMeasuredWidth。 不过需要在onMeasure或onLayout之后才能得到

**Comment by theoneee** [comment]
private void initSegment(boolean beyond) {
        //普通文字颜色
        mTabSegment.setDefaultNormalColor(ContextCompat.getColor(this, R.color.black38_text));
        //选中时文字颜色
        mTabSegment.setDefaultSelectedColor(ContextCompat.getColor(this, R.color.mainColor));
        //是否有 Indicator
        mTabSegment.setHasIndicator(true);
        // Indicator的方向 ture为上方 false为下方
        mTabSegment.setIndicatorPosition(false);
        // 置 indicator的宽度是否随内容宽度变化
        mTabSegment.setIndicatorWidthAdjustContent(true);
        //给每个Tab添加内容
        for (int i = 0; i < tab_title.length; i++) {
            mTabSegment.addTab(new QMUITabSegment.Tab(tab_title[i]));//纯文字
        }
//监听
        mTabSegment.addOnLayoutChangeListener(new View.OnLayoutChangeListener() {
            @Override
            public void onLayoutChange(View v, int left, int top, int right, int bottom, int oldLeft, int oldTop, int oldRight, int oldBottom) {
                //如果mTabSegment的宽度小于屏幕宽度 则重新设置成平分模式（默认为滚动模式）
                if(mTabSegment.getWidth() < getSystemWidth()){
                    mTabSegment.reset();
                    initSegment(false);
                }
            }
        });

        if (beyond) {
//如果超出则使用滚动模式
            int space = QMUIDisplayHelper.dp2px(this, 16);
            mTabSegment.setItemSpaceInScrollMode(space);
            mTabSegment.setMode(QMUITabSegment.MODE_SCROLLABLE);
            mTabSegment.setPadding(space, 0, space, 0);
        }else{
//没有则平分模式
            mTabSegment.setMode(QMUITabSegment.MODE_FIXED);
        }
        mTabSegment.setupWithViewPager(mViewPage, false);
    }

private int getSystemWidth(){
 WindowManager wm = (WindowManager) this
                .getSystemService(Context.WINDOW_SERVICE);

        return wm.getDefaultDisplay().getWidth();
}


这样写使用者就不用再去区分使用模式了吧
