### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by GillX** [QMUI/QMUI_Android#140]
1.建议增加QMUISpanTouchFixTextView与QMUILinkTextView功能上合并的TextView
2.【强烈】建议增加相册+拍照(多图选择与预览放大) 功能【可考虑将手Q或微信的相册相关功能开源 】
3.建议增加类似StickyHeaderListView的FilterView筛选栏
4.建议增加tag流式布局标签
5.建议增加右侧快速定位字母表
6..建议增加banner

非常感谢QMUI的开源，为广大码农带来便利
你们辛苦了！

**Comment by cgspine** [comment]
第2点：可以考虑使用知乎开源的图片选择框架[Matisse](https://github.com/zhihu/Matisse)
第4点：我们提供了QMUIFloatLayout，应该很方便实现tag流式布局标签
第6点：banner应该是高度定制的UI，如果要增加，该实现怎样的功能？

**Comment by chengjs** [comment]
你们这群畜生，恶心到家了，什么，叫开发文档，草。全家死吧。

**Comment by NicodeLee** [comment]
@chengjs api都看不懂水平转行去，嘴真烂。
第5点可能会增加库的重量，不是那么高频的功能应该没必要加吧。（如果能找到基于rv lv都通用的右侧快速定位字母表方案倒是可以考虑）

**Comment by NicodeLee** [comment]
@chengjs 这是开源，爱用不用。还是转行吧，菜还这臭脾气，毫无贡献。

**Comment by chengjs** [comment]
什么叫贡献，连文档都不是给新手看的，就是给个别装B的猪看，在TM的开源，贡献有个P用，别忘了你也是新手的时候，你TM的是怎么心态的，心里清楚，别TM的在这里装B。

**Comment by MoLice** [comment]
@chengjs 请文明发言，已举报你的评论。

有合理的问题我们会解决，而我们在看待问题时也并没有区分“新手问题”或“老手问题”，只要是合理的问题都会去解决。目前的文档 & Demo 完善程度已经是我们有限的精力与理想的需求之间的平衡结果，有欠缺是事实存在的，就算是 Google 官方文档也不可能让你做到不用自己动手、思考就能写出你想要的需求。我们也并没有承担一个“让全世界所有的人都很轻松用上 QMUI 并且遇到任何问题都及时帮你解决”的社会义务，这是一个开源项目，不是一个付费获取服务的项目，你有精力有想法大可自己贡献代码，所有的事情都是等价交换的，不可能不付出而有所得。

最后，谢谢你对 QMUI 的关注。

**Comment by MoLice** [comment]
另外，待 GitHub 官方处理完举报后，我们将会删除不健康的评论。

**Comment by chengjs** [comment]
拜拜，mmp
