### ISSUE TITLE
QMUITabSegment tab颜色问题

### ISSUE THREAD

**Issue by ZzjBeatYou** [QMUI/QMUI_Android#141]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 5`
- [x] 设备系统版本：如 `Android 7.0`
- [x] Gradle 版本：如 `3.0.0`
- [x] QMUI Android 版本：`1.0.0`

### 具体问题描述 ###
你好，QMUITabSegment 当修改tab的normalColor和selectColor后，快速滑动会出现 颜色闪烁的问题

**Comment by ZzjBeatYou** [comment]
好像是修改QMUITabSegment 背景色导致的，只要不为白色 ，动画就会看着比较难受

**Comment by Shimingli** [comment]
啊，哥你代码怎么样的 我也发现了

**Comment by cgspine** [comment]
组件内部的问题， 我今天晚点或明天发个包

**Comment by Evatruy** [comment]
请问此问题怎么解决的，更新版本即可？

**Comment by cgspine** [comment]
更新版本

**Comment by Evatruy** [comment]
本地为1.1.10版，尝试更新至1.1.12版本，依然出现此问题，请问您使用的哪一版本呢

**Comment by cgspine** [comment]
最新版本是1.3.4，可以尝试最新版，看看你出现的问题和已解决的是不是同一个问题
