### ISSUE TITLE
DEMO:QMUIStatusBarHelper oppo r9m 字体改变没有效果

### ISSUE THREAD

**Issue by guangzq** [QMUI/QMUI_Android#143]
### 运行环境 ###

- [x] 设备型号：`oppo r9m`
- [x] 设备系统版本：如 `Android 5.1`
- [x] QMUI Android 版本：`1.0.6`

### 具体问题描述 ###
demo中状态栏字体改变没有效果

**Comment by cgspine** [comment]
Android 5.x 是没办法状态栏改字体颜色的，它只作用于 Android 6.x+， 魅族、小米

**Comment by Shimingli** [comment]
是不是判断下手机设备然后选择是否使用透明的头部 对吧

**Comment by cgspine** [comment]
对，所以 QMUIStatusBarHelper.translucent(Activity activity, @ColorInt int colorOn5x) 支持传第二个参数，在 android 5.x 让状态栏背景半透明
