### ISSUE TITLE
QMUITabSegment addTab 无效

### ISSUE THREAD

**Issue by wudongchen** [QMUI/QMUI_Android#144]
### 运行环境 ###

- [x] 设备型号：如：`模拟器/魅蓝note5`
- [x] 设备系统版本：如 `Android 7.1.1/Android 6.0`
- [x] Gradle 版本：如 `3.0.1`
- [x] QMUI Android 版本：`1.0.6`

### 具体问题描述 ###
QMUITabSegment addTab 无效，不显示Tab
#### 问题截图 ####
![screenshot_1515468610](https://user-images.githubusercontent.com/13791341/34703897-7ca49558-f530-11e7-9eac-aea4e8389d16.png)
<img width="569" alt="wx20180109-112928 2x" src="https://user-images.githubusercontent.com/13791341/34703898-7ce941da-f530-11e7-89e4-de99322b0f71.png">

**Comment by cgspine** [comment]
最后需要调用 notifyDataChanged

**Comment by wudongchen** [comment]
@cgspine 嗯 我是有调用的。很奇怪。

**Comment by cgspine** [comment]
你的tabNavigation添加到视图层级中了吗？是不是宽度为0了？ 可以用Layout Inspector查看一下

**Comment by wudongchen** [comment]
@cgspine setupWithViewPager(vpContent, false); 后面boolean没有传参默认true 😂
