### ISSUE TITLE
QMUITipDialog可以修改弹出背景的圆角么

### ISSUE THREAD

**Issue by tx123456** [QMUI/QMUI_Android#145]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

#### 异常日志（堆栈） ####
我想修改QMUITipDialog弹出背景的圆角该怎么修改

**Comment by cgspine** [comment]
在theme里面覆添加item <item name="qmui_tip_dialog_bg">@drawable/your_tip_dialog_bg</item>

**Comment by cgspine** [comment]
在 them e里添加`<item name="qmui_tip_dialog_bg">@drawable/your_tip_dialog_bg</item>`

**Comment by cgspine** [comment]
在 theme 里添加`<item name="qmui_tip_dialog_bg">@drawable/your_tip_dialog_bg</item>`

**Comment by tx123456** [comment]
ok
