### ISSUE TITLE
List可以修改左侧包含小图标吗？

### ISSUE THREAD

**Issue by kigkrazy** [QMUI/QMUI_Android#146]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

#### 异常日志（堆栈） ####
List可以修改左侧包含小图标吗？

**Comment by cgspine** [comment]
什么意思？修改布局吗？
