### ISSUE TITLE
沉浸式状态栏问题，在Fragment的基础上，add 和 replace同级Fragment，add方法padding失效。

### ISSUE THREAD

**Issue by Koterwong** [QMUI/QMUI_Android#148]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 7.0`
- [x] Gradle 版本：如 `3.0.1`
- [x] QMUI Android 版本：`1.0.6`

### 具体问题描述 ###

沉浸式状态栏问题，在Fragment的基础上，add 和 replace同级Fragment，add方法padding失效。

猜测可能是官方的问题，不知道有没有解决方法？

#### 问题截图 ####

QMUIDemo 里 修改BaseFragmentActivity 的 startFragment方法里面replace为add，就会造成padding失效。 
![qq 20180111142652](https://user-images.githubusercontent.com/16436547/34811394-97cd0e76-f6db-11e7-87f4-a3781bde4458.png)
![qq 20180111142826](https://user-images.githubusercontent.com/16436547/34811412-b7a41186-f6db-11e7-996f-28f8b2f6b48c.png)

**Comment by cgspine** [comment]
![image](https://user-images.githubusercontent.com/7828876/34861128-82764b06-f79d-11e7-990e-fa9f8ec7ad44.png)
onCreate里把 FrameLayout 更改为 QMUIWindowInsetLayout 就可以解决 padding 失效的问题

**Comment by Puppy-Love** [comment]
viewpager 配个多个Fragment 切换呢？

**Comment by cgspine** [comment]
QMUIDemo 里有提供 QMUIViewPager 的使用，就有配套多个 fragment 切换的例子

**Comment by Puppy-Love** [comment]
嗯 按照QMUIViewPager 那个有效果 可是好像那个topbar title 字体布局中向上偏移了``

**Comment by Puppy-Love** [comment]
![qq 20180329161819](https://user-images.githubusercontent.com/16749976/38078233-32313374-336e-11e8-9125-d76a3d467963.png)
