### ISSUE TITLE
QMUIPopup的显示问题

### ISSUE THREAD

**Issue by a512509050** [QMUI/QMUI_Android#149]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

#### 问题截图 ####

![8 24n7jc0u vm py1n3in7a](https://user-images.githubusercontent.com/18045999/34925610-5c738a6e-f9e5-11e7-928b-63aa6eb23f05.png)

**Comment by NicodeLee** [comment]
今天使用也有类似问题，如果是做item menu，一是间距问题，二是，小箭头能不能控制显示与否呢。

**Comment by cgspine** [comment]
1. 构造器传 DIRECTION_NONE 就会没有小箭头
2. 间距主要是背景的阴影导致的，目前可以通过 theme 改掉背景，换一个阴影小的drawable，同时需要调整相关变量：
![image](https://user-images.githubusercontent.com/7828876/34938392-26c2443a-fa23-11e7-9624-3c017fdf91f3.png)

**Comment by NicodeLee** [comment]
get√

**Comment by HancockY** [comment]
搞了一天了, 就是调不好这块...想要小箭头. 所以想把布局往右移动, 但是改了.9图之后, 显示就不对了, 也不知道 相关变量 都要怎么改...

**Comment by HancockY** [comment]
说好的用 QMUILayout重构的呢...

**Comment by HancockY** [comment]
卧槽.. 就在我打这些字的时候, 他居然显示正常了. 我只是把qmui_popup_bg.9图左右空白去掉了
早上就试过了, 有问题啊, 但是刚刚突然就正常了我晕

**Comment by HancockY** [comment]
但是当我想调整上下间距的时 ,修改.9图上下间隔后, 箭头就不见了....

**Comment by cgspine** [comment]
建议用LayoutInspector 查看间距信息来调整。 QMUILayout重构在master，已经重构了，会跟着2.0发布，预估在11月份发

**Comment by HancockY** [comment]
好的, 那就等到11月吧, 我自定义popup已经做完了, 到时候再换 谢谢~~




------------------ 原始邮件 ------------------
发件人: "cgspine"<notifications@github.com>; 
发送时间: 2019年10月21日(星期一) 中午12:40
收件人: "Tencent/QMUI_Android"<QMUI_Android@noreply.github.com>; 
抄送: "Hancock"<516150533@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [Tencent/QMUI_Android] QMUIPopup的显示问题 (#149)




建议用LayoutInspector 查看间距信息来调整。 QMUILayout重构在master，已经重构了，会跟着2.0发布，预估在11月份发
