### ISSUE TITLE
设置了沉淀状态栏，但是标题上移了

### ISSUE THREAD

**Issue by yuwoquan** [QMUI/QMUI_Android#151]
### 运行环境 ###
- [x] 设备型号：如：`小米5`
- [x] 设备系统版本：如 `Android 7.0`
- [x] Gradle 版本：如 `3.0.1`
- [x] QMUI Android 版本：`1.0.6`

**Comment by cgspine** [comment]
你需要 在 layout文件的根节点设置 fitSystemWindows = true

**Comment by yuwoquan** [comment]
还是没能解决。我在mainactivity调用了        QMUIStatusBarHelper.translucent(this); // 沉浸式状态栏。在fragment的Linearlayout或者是topbar设置 fitSystemWindows = true。还是会出现同样的情况。

**Comment by cgspine** [comment]
用的是fragmentManager? 你的 fragment 是 add 还是 replace?

**Comment by yuwoquan** [comment]
FragmentManager fragmentManage = getSupportFragmentManager();
然后add进去

**Comment by yuwoquan** [comment]
我在主页面的RelativeLayout设置了   android:fitsSystemWindows="true"。虽然标题正常了，但是状态栏是白色的。东西全部挡住

**Comment by cgspine** [comment]
主页面设置了 android:fitsSystemWindows， 那么状态栏的背景应该是 主页面的RelativeLayout 的颜色了

**Comment by cgspine** [comment]
add 多个fragment时有这个问题：#148

**Comment by yuwoquan** [comment]
是的，我看了你们demo的沉淀状态栏，你们也是在LinearLayout设置了颜色而已，去掉的话一样会出现的这种空白效果。
