### ISSUE TITLE
自定义textViewStyle，和QMUI发生冲突

### ISSUE THREAD

**Issue by tpnet** [QMUI/QMUI_Android#155]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

### 具体问题描述 ###
自定义textViewStyle，和QMUI发生冲突
```
Error:error: style attribute 'attr/textViewStyle (aka com.shhuoniu.txhui:attr/textViewStyle)' not found.
```
#### 问题截图 ####
![image](https://user-images.githubusercontent.com/17380722/35038434-cbce7e60-fbb5-11e7-8c7a-70e4eeb93b3b.png)
![image](https://user-images.githubusercontent.com/17380722/35038461-d8f03156-fbb5-11e7-9a2a-3fa1cd05eefa.png)
![image](https://user-images.githubusercontent.com/17380722/35038558-28194128-fbb6-11e7-80f1-5ef923e4d843.png)

**Comment by cgspine** [comment]
应该用带 android 前缀的就可以了吧。 另外请教一下：buttonStyle 为何要设置两个？ 我一直都只写有
 android 前缀的，没有遇到过 4.4 以上及以下的兼容问题

**Comment by tpnet** [comment]
@cgspine  例如buttonStyle，如果只用 加android前缀的，，，我在小米2,Android4.4.4的手机上，会没效果，。。。。还有请问一下1.0.6版本 RMUIRoundButton 只设置qmui_radius没效果，，这个问题什么时候修复呢？

**Comment by cgspine** [comment]
其实 1.0.7 版本已经可以下载了，但是我改了 TopBar 主题的设置， 在 github 上我还没 release 和 加更新提示
