### ISSUE TITLE
新手刚来，看了下demo很喜欢这个UI框架，感觉能省事不少，但是好像没看到使用文档

### ISSUE THREAD

**Issue by jayleco** [QMUI/QMUI_Android#159]
1.请问有使用说明文档吗？
2.好像没看到有EditText的UI，如果想使用圆角边框的输入框怎么用呢 
3.我下载了这个源码，使用android studio导入demo出错

**Comment by cgspine** [comment]
1.使用文档见：http://qmuiteam.com/android/page/document.html 。如果你想用某个组件，最好的方式是直接去Demo看使用方式。
2.EditText 想改成圆角边框，写一个 Drawable 作为 EditText 的背景就行：
```
GradientDrawable bg = new GradientDrawable();
bg.setStroke();
bg.setCornerRadius();
bg.setColor();
```
3.请看 https://github.com/QMUI/QMUI_Android/wiki/QMUI-Q-&-A 第4点

**Comment by chanthuang** [comment]
1.使用文档见：README 里的开始使用，以及官网的[功能列表](http://qmuiteam.com/android/page/document.html)
2.EditText 想改成圆角边框，写一个 GradientDrawable 并设置圆角作为 EditText 的背景就行。
3.具体什么错？请看 https://github.com/QMUI/QMUI_Android/wiki/QMUI-Q-&-A 第4点

**Comment by cgspine** [comment]
1. 使用文档见：http://qmuiteam.com/android/page/document.html 。如果你想使用某个控件，最好的方式是去 Demo 看使用方式
2. EditText 想改成圆角边框，写一个 Drawable 作为 EditText 的背景就行：
```
GradientDrawable bg = new GradientDrawable();
bg.setStroke();
bg.setCornerRadius();
bg.setColor();
```
3. 请看 https://github.com/QMUI/QMUI_Android/wiki/QMUI-Q-&-A 第4点

**Comment by goodluckforme** [comment]
鄙人这里做了一下拙劣的总结:
包括基本入门以及简单的组件使用
都是一般项目中可能用到基础组件
[点我的CSDN](http://blog.csdn.net/qq_20330595/article/details/79072580)

**Comment by theoneee** [comment]
@goodluckforme 你这样写。有人又会问，你这是什么语言啊。怎么和我写的Android不一样啊。这里面的都可以直接分离出来。看着Demo代码然后看着Demo APP，哪个功能是怎么实现的一看便知。然后再拿个文件夹装起来，要的时候直接复制粘贴，改需要改的地方即可，有xml也是直接复制xml。
其他的难得也就是style里面重写需要改的方法地方吧。这里需要点击 parent="QMUI.Compat.NoActionBar" 里面去查找你所要改的空间的属性名称，然后再到自己的style里面重写然后更改成自己想要的就行了。


![1](https://user-images.githubusercontent.com/32156330/35492791-eca05a0e-04e9-11e8-8f69-871b528b856c.png)
![2](https://user-images.githubusercontent.com/32156330/35492794-f1fee876-04e9-11e8-82d0-544e9cbc5097.png)
![3](https://user-images.githubusercontent.com/32156330/35493007-37f9d16e-04eb-11e8-95ac-52e6052ee7c7.png)
