### ISSUE TITLE
QMUITopBar能否动态改变标题颜色

### ISSUE THREAD

**Issue by tx123456** [QMUI/QMUI_Android#16]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

#### 异常日志（堆栈） ####

可以新增一个改变标题颜色的方法吗，或者把getTitleView 设置为public

**Comment by cgspine** [comment]
当你调用 setTitle 时， 返回的就是你需要的 TextView，这样可以确保获得的 TextView 不为 null。
