### ISSUE TITLE
小米3状态栏黑色字体

### ISSUE THREAD

**Issue by qq287547806** [QMUI/QMUI_Android#160]
### 运行环境 ###

- [x] 设备型号：如：`小米3`
- [x] 设备系统版本：如 `Android 4.4`
- [x] MUI 版本：如 `9.2.3.0稳定版`
- [x] QMUI Android 版本：`1.0.6`

### 具体问题描述 ###
小米3手机运行示例项目，状态栏设置黑色字体无效。

**Comment by qq287547806** [comment]
研究了下这个问题，发现是MIUI9以后高于6.0版本的采用原生方法改变黑色字体，但MIUI9低于6.0版本还是用的以前的方法，望修复一下。

**Comment by 1993hzw** [comment]
并没有解决哦，还是存在问题．我的手机是红米Note3,MIUI 9.6,Android 6.0.1，设置字体黑色无效．这是官方文档的解释：https://dev.mi.com/console/doc/detail?pId=1159

**Comment by cgspine** [comment]
你用的qmui版本是多少？

**Comment by 1993hzw** [comment]
1.1.7

**Comment by 1993hzw** [comment]
你看看最新的官方文档呀，[https://dev.mi.com/console/doc/detail?pId=1159](https://dev.mi.com/console/doc/detail?pId=1159)，最新的呀，小米官方文档一直更改．（心累．．．不想再跟踪这个问题了，反正我解决了，你们自己看着办吧，别问我了）

3.1. 在新的 MIUI 版本（即基于 Android 6.0 ，开发版 7.7.13 及以后版本）
使用 View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR ，来设置“状态栏黑色字符”效果
同时要设置 WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS，
并且不设置 WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS

**Comment by cgspine** [comment]
改另外两个flag是会影响沉浸式(QMUIStatusBarHelper.transluent)的， 现在修改为 Android 6 以后走官方逻辑
