### ISSUE TITLE
没有导入引用import QDWidgetContainer

### ISSUE THREAD

**Issue by jinxiyang** [QMUI/QMUI_Android#162]
这个类com.qmuiteam.qmuidemo.manager.QDDataManager 没有导入引用import QDWidgetContainer，编译不了qmuidemo

**Comment by cgspine** [comment]
看 https://github.com/QMUI/QMUI_Android/wiki/QMUI-Q-&-A 第 1 点。QDWidgetContainer是编译时生成的，应该是其它环境问题导致不能编译

**Comment by jinxiyang** [comment]
谢谢，好了
