### ISSUE TITLE
红米4.4.2的版本上设置头部透明栏，不管用，应该去拦截，我自己做的时候，判断是红米的mui5，直接拦截掉不做处理

### ISSUE THREAD

**Issue by Shimingli** [QMUI/QMUI_Android#164]
### 运行环境 ###

- [x] 设备型号：如：`红米`
- [x] 设备系统版本：如 `4.4.2`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

**Comment by cgspine** [comment]
MIUI 5 支持透明状态栏？

**Comment by Shimingli** [comment]
不支持哦  小米的mui9 也不支持  难受   现在用小米的手机很多   小米的全部手机都不支持 感觉

**Comment by cgspine** [comment]
MIUI9 支持吧，是实现方式换了，采用了官方的方式
