### ISSUE TITLE
在CoordinatorLayout中使用QMUITopBar 设置app:layout_collapseMode="pin"无效

### ISSUE THREAD

**Issue by tx123456** [QMUI/QMUI_Android#17]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

#### 异常日志（堆栈） ####

希望在CoordinatorLayout中使用也能达到像toolbar那样的效果固定在屏幕顶端不动

**Comment by cgspine** [comment]
请升级到1.0.2， 需要使用 app:qmui_layout_collapseMode 来代替app:layout_collapseMode，其它相关属性使用时也需要添加"qmui_"前缀
