### ISSUE TITLE
oppo状态颜色调用QMUIStatusBarHelper.setStatusBarLightMode(this); 颜色依旧为白色

### ISSUE THREAD

**Issue by chenyang1900** [QMUI/QMUI_Android#170]
### 运行环境 ###

- [x] 设备型号：如：`oppo  R9m`
- [x] 设备系统版本：如 `Android 5.1`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.0.6`

### 具体问题描述 ###
oppo状态颜色调用QMUIStatusBarHelper.setStatusBarLightMode(this); 颜色依旧为白色 。期望调用该方法状态栏的那些字和图标能够变成黑色
#### 问题截图 ####
![259782944677809213](https://user-images.githubusercontent.com/15828867/35550639-5b4eeb0a-05c6-11e8-9164-624d9a4ea464.jpg)
![205006034942699797](https://user-images.githubusercontent.com/15828867/35550643-60bd5e00-05c6-11e8-98aa-75ab2c8070b9.jpg)
![748342191656128670](https://user-images.githubusercontent.com/15828867/35550645-63161eda-05c6-11e8-96a4-b2c4557b6c70.jpg)

**Comment by cgspine** [comment]
Android 5.x 是不支持改黑色的。 一般是在 5.x下给状态栏用一个半透明的黑色

**Comment by chenyang1900** [comment]
谢谢
