### ISSUE TITLE
Dialog里面嵌套Recyclerview,会导致Action不显示

### ISSUE THREAD

**Issue by liunewshine** [QMUI/QMUI_Android#171]
### 运行环境 ###

- [x] 设备型号：如：`所有机型`
- [x] 设备系统版本：如 `Android 6.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.0.6`

### 具体问题描述 ###
Dialog里面嵌套Recyclerview,Recyclerview内容过长时会导致底部的Action按钮不显示
#### 问题截图 ####
![screenshot_20180131-093917](https://user-images.githubusercontent.com/7698511/35600817-ddbd9646-066a-11e8-9b19-d237476c062b.jpg)

**Comment by cgspine** [comment]
你的 RecyclerView 没有限定最大高度吧。 可以参考 QMUIWrapContentListView 重写 RecyclerView 的 onMeasure
