### ISSUE TITLE
Demo 跑不起来

### ISSUE THREAD

**Issue by cai784921129** [QMUI/QMUI_Android#173]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

#### 问题截图 ####
![image](https://user-images.githubusercontent.com/20353284/35659535-b27b2ed0-0741-11e8-8b01-b46f01ca318c.png)
![image](https://user-images.githubusercontent.com/20353284/35659538-b7195ae8-0741-11e8-8a57-a3a2c69f8c77.png)

#### 异常日志（堆栈） ####
Error:(4, 0) For input string: ""
<a href="openFile:D:\Android_Studio_Path\QMUI_Android-master\qmuidemo\build.gradle">Open File</a>

**Comment by yaochangliang159** [comment]
我也跑不起来。。。我把def cmd def gitVersion 删了，，，又提示Error:(22, 0) Gradle DSL method not found: 'google()'。你们这个DEMO太难跑了。。。。跑不起了。。

**Comment by baohexin** [comment]
@yaochangliang159  大兄弟你得在build.gradle里加上google()

`buildscript {
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
        classpath 'com.github.dcendents:android-maven-gradle-plugin:1.5'
        classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.7.2'
    }
}

allprojects {
    repositories {
        jcenter()
        mavenLocal()
        google()
    }

    ext {
        buildToolsVersion = "26.0.2"
        minSdkVersion = 14
        targetSdkVersion = 26
        compileSdkVersion = 26
        supportVersion = "26.1.0"
    }
}`
第二个问题见这个解决办法:
https://github.com/QMUI/QMUI_Android/issues/175

**Comment by baohexin** [comment]
@cai784921129 
见下面这个：
#175

**Comment by cai784921129** [comment]
@baohexin  请教一下，是不是只有 android Studio 3.0才能运行，我的是2.3版本

**Comment by baohexin** [comment]
@cai784921129 跟as版本没关系，3.0gradle配置是发生了变化，你根据之前gradle配置把这个里面build.gradle相应配置一下应该没问题。运行不起来是报什么错误。
