### ISSUE TITLE
问一个低级错误

### ISSUE THREAD

**Issue by pj1993** [QMUI/QMUI_Android#176]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

### 具体问题描述 ###
demo我都跑起来了，但是在自己的项目加入compile 'com.qmuiteam:qmui:1.0.6'后就报下面的错误
#### 问题截图 ####
![image](https://user-images.githubusercontent.com/20423634/35726307-686a69ec-083f-11e8-982f-2004be5691f6.png)

#### 异常日志（堆栈） ####

**Comment by pj1993** [comment]
27的sdk我也更新了

**Comment by cgspine** [comment]
可能是其它库依赖了不同版本的support 包，可以参考 https://github.com/QMUI/QMUI_Android/wiki/QMUI-Q-&-A 第二点，项目采用一个统一的 support version

**Comment by pj1993** [comment]
解决了，配置maven少了一句 maven {  url "https://maven.google.com" }参考的这个文章http://blog.csdn.net/waa_studio/article/details/78732460，不过他的第二步我都用的27
