### ISSUE TITLE
not set in conjunction with -source 1.7

### ISSUE THREAD

**Issue by tenSunFree** [QMUI/QMUI_Android#18]
### 运行环境 ###
![01](https://user-images.githubusercontent.com/23090085/30003871-50e6ff16-90f7-11e7-845c-ddc0fa018117.jpg)

![2017-09-04_075105](https://user-images.githubusercontent.com/23090085/30007632-2c8f1118-9146-11e7-839f-b342d971157d.jpg)

### 具体问题描述 ###
![02](https://user-images.githubusercontent.com/23090085/30003875-5a9fd23a-90f7-11e7-8a69-2161927215b1.jpg)

請教一下, 為什麼會產生這個訊息? 我應該如何解決?

**Comment by cgspine** [comment]
您的 JDK 版本是多少？

**Comment by tenSunFree** [comment]
jdk 1.8.0_91

![2017-09-04_154223](https://user-images.githubusercontent.com/23090085/30016498-fb6df0a8-9187-11e7-9155-b68092e14c48.jpg)

**Comment by cgspine** [comment]
试试这个：

[https://openhome.cc/Gossip/Encoding/SourceFile.html](https://openhome.cc/Gossip/Encoding/SourceFile.html)

[http://430895101.blogspot.com/2015/11/android-studio-unmappable-character-for.html](http://430895101.blogspot.com/2015/11/android-studio-unmappable-character-for.html)
