### ISSUE TITLE
ListPopup显示问题

### ISSUE THREAD

**Issue by PawnLee** [QMUI/QMUI_Android#180]
### 运行环境 ###

- [x] 设备型号：如：小米5
- [x] 设备系统版本：如 `Android 7.0`

### 具体问题描述 ###

QMUIListPopup在手机靠近两侧弹出显示时，显示问题。

#### 问题截图 ####

![screenshot_2018-02-05-09-31-38-995_monitor weather yutian myapplication](https://user-images.githubusercontent.com/25053852/35785010-164dcecc-0a58-11e8-933c-6dc02674c8e5.png)

**Comment by cgspine** [comment]
与 #149 同样，背景阴影导致，如果要调整，需要换切图
