### ISSUE TITLE
弹出软键盘时，键盘升起部分能看到主题色

### ISSUE THREAD

**Issue by sunshine763** [QMUI/QMUI_Android#181]
### 运行环境 ###

- [x] 设备型号：如：`华为mate10`、`红米5A`
- [x] 设备系统版本：如 `Android8.0`、 `Android7.0`
- [x] QMUI Android 版本：`1.0.6`

### 具体问题描述 ###
使用QMUI提供的示例APP，或者将QMUI引入项目时，点击EditText弹出软键盘时，键盘升起部分会显示`app_primary_color`的颜色，如QMUI提供的APP显示蓝色，请问该如何解决键盘上升时出现别的颜色的问题。
另外我看到示例中用法，需要给菜单栏下方的控件都包装一层layout并设置background才能使得下方的背景不是`app_primary_color`的颜色，请问一下还有没有别的方式处理颜色问题。

**Comment by cgspine** [comment]
有啊，可以参考 fragment_about.xml 。使用 QMUITopBarLayout

**Comment by sunshine763** [comment]
谢谢，看到QMUITopBarLayout了。那如果不使用QMUITopBarLayout的话，弹出软键盘的过程中出现的`app_primary_color`颜色能否不显示？你点击QDVerticalTextViewFragment的EditText时可以复现这个情景。

**Comment by cgspine** [comment]
应该不行，对于有键盘交互的，应该还是用 QMUITopBarLayout 这种形式，回头我改改有键盘交互事件的界面

**Comment by sunshine763** [comment]
好的，知道了，谢谢你的回答
