### ISSUE TITLE
QMUIDialog 横屏显示，适配问题

### ISSUE THREAD

**Issue by t1030338120** [QMUI/QMUI_Android#182]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.0.6`

### 具体问题描述 ###
QMUIDialog 横屏显示，dialog宽度适配问题，
没有对width做最大宽度限制，
建议dialog最大宽度，小于或等于竖屏屏幕的宽度

**Comment by cgspine** [comment]
fixed

**Comment by Viperwu** [comment]
MIUI下设置全屏横屏模式，直接崩溃！

**Comment by cgspine** [comment]
给下崩溃信息？
