### ISSUE TITLE
建议 Dialog添加不可消失或者添加消失事件

### ISSUE THREAD

**Issue by TTHHR** [QMUI/QMUI_Android#186]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 4.4`
- [x] Gradle 版本：如 `3.2.0`
- [x] QMUI Android 版本：`1.0.6`

### 具体问题描述 ###
有些数据是用户必填才能进入下一步的
现在的Dialog不能屏蔽返回键，也没有dismiss的事件

**Comment by cgspine** [comment]
```
QMUIDialog dialog = new QMUIDialog.MenuDialogBuilder(getActivity()).create();
dialog.setCancelable(false);
dialog.show();
```

调用 dialog.setCancelable(false); 就可以满足你的需求

**Comment by TTHHR** [comment]
原来需要create()才能setCancelable。。。。Dialog居然不需要create()也能show()

**Comment by cgspine** [comment]
我们在 DialogBuilder 的 show 方法中封装了 create。 其和 Dialog 的 show 方法不是同一回事
