### ISSUE TITLE
Android Studio无法编译

### ISSUE THREAD

**Issue by tianyingzhong** [QMUI/QMUI_Android#187]
### 运行环境 ###
- [x] Gradle 版本：如 `2.3.3`
- [x] QMUI Android 版本：`1.0.7`

### 具体问题描述 ###
集成QMUI后，Android Studio编译项目时报错如下
Error:Failed to resolve: com.android.support:support-annotations:27.0.1
<a href="install.m2.repo">Install Repository and sync project</a><br><a href="openFile:D:/AndroidStudioSpace/Tuhu_Merchant_Android/RetrofitLibrary/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

Error:Failed to resolve: com.android.support:appcompat-v7:27.0.1
<a href="install.m2.repo">Install Repository and sync project</a><br><a href="openFile:D:/AndroidStudioSpace/Tuhu_Merchant_Android/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

Error:Failed to resolve: com.android.support:design:27.0.1
<a href="install.m2.repo">Install Repository and sync project</a><br><a href="openFile:D:/AndroidStudioSpace/Tuhu_Merchant_Android/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

Error:Failed to resolve: com.android.support:cardview-v7:27.0.1
<a href="install.m2.repo">Install Repository and sync project</a><br><a href="openFile:D:/AndroidStudioSpace/Tuhu_Merchant_Android/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

### 问题截图 ###
![as](https://user-images.githubusercontent.com/11611984/36581401-b25ed16e-18a7-11e8-9f67-843e2c8b4193.png)

修改项目的编译版本为
    ext {
        buildToolsVersion = "25.0.2"
        minSdkVersion = 16
        targetSdkVersion = 21
        compileSdkVersion = 25
        supportVersion = "25.3.1"
    }
后，依然报上面的错；

    修改compile 'com.qmuiteam:qmui:1.0.7'
    compile ('com.qmuiteam:qmui:1.0.7') {
           exclude group: 'com.android.support'
    }后，也还是依然报同样的错

 下载QMUI后，修改compile 'com.qmuiteam:qmui:1.0.7' 为   compile project(':qmui')，改了supportVersion后，也依然报这个错。

**Comment by cgspine** [comment]
依赖包冲突的问题吧，可以用 https://github.com/QMUI/QMUI_Android/wiki/QMUI-Q-&-A 第2条
