### ISSUE TITLE
腾讯做的库？

### ISSUE THREAD

**Issue by TCQQ** [QMUI/QMUI_Android#19]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

**Comment by spysoos** [comment]
What the hell you talking about?

**Comment by chanthuang** [comment]
嗯，广研团队出品。
