### ISSUE TITLE
【QMUIFloatLayout】建议扩展支持支持单选、多选

### ISSUE THREAD

**Issue by NicodeLee** [QMUI/QMUI_Android#192]

**Comment by chanthuang** [comment]
`QMUIFloatLayout` 只是提供了一种布局方式，没有额外的功能。请问你说的单选多选是指什么？

**Comment by NicodeLee** [comment]
类似产品标签，用户印象这类的标签单选多选的场景。

**Comment by chanthuang** [comment]
可以写一些标签 View 添加到 QMUIFloatLayout 里面，但这些标签的点击事件是你的项目中自己定的，这样应该也能实现你说的功能。
QMUIFloatLayout 只提供布局方式，类似于 LinearLayout，就像 LinearLayout 也不会给它的子 View 添加点击事件一样。
