### ISSUE TITLE
QMUITabSegment中mIndicator下划线的宽度如何更改呢？

### ISSUE THREAD

**Issue by JetXing** [QMUI/QMUI_Android#193]
### 运行环境 ###

- [x] 设备型号：HUAWEI CAZ-AL10
- [x] 设备系统版本：Android 6.0
- [x] Gradle 版本：2.3.0
- [x] QMUI Android 版本：1.0.1

QMUITabSegment中mIndicator下划线的宽度如何更改呢？

**Comment by cgspine** [comment]
目前只提供了 setIndicatorWidthAdjustContent() 方法，决定 mIndicator 宽度是否根据content长度进行调节
