### ISSUE TITLE
QMUIFragment 应用到 ViewPager ,FragmengStatePagerAdaper 中时，某个时候会空白

### ISSUE THREAD

**Issue by hewking** [QMUI/QMUI_Android#195]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

### 具体问题描述 ###
问题如题，空白是指应该出现页面其实没有,滑动tab 到空白页面 又出现了，想问问这是fragment 的问题还是QMUIFragment 的问题

**Comment by cgspine** [comment]
QMUI Demo 中 QMUIViewPager 有将用 fragment 应用到 ViewPager 里。 在你的手机上， Demo 会出现问题吗？

**Comment by hewking** [comment]
demo 没有出现，这个问题我还没有找到方法复现。请问你用fragment 的过程中有出现这种问题吗，Fragment 嵌套 Fragment 并且有ViewPager ，挺久没用Fragment了 ，可能有使用不当的地方？
