### ISSUE TITLE
紧急... 在 AS3.2版本，gradle 4.5 版本引入QMUI版本1.06 , 报错。。。

### ISSUE THREAD

**Issue by xuhongv** [QMUI/QMUI_Android#196]
### 运行环境 ###

- [x] 设备型号：`红米 note2`
- [x] 设备系统版本：`Android 5.0`
- [x] Gradle 版本： `4.5`
- [x] QMUI Android 版本：`1.0.6`

### 具体问题描述 ###
 
 在 AS3.2版本，gradle4.5版本引入QMUI版本1.06，报错如下：

#### 问题截图 ####
![u ef 74wat8jdckphyx 5td](https://user-images.githubusercontent.com/25237870/37072264-7aa7bada-21fb-11e8-816e-3609627dc36f.png)

#### 异常日志（堆栈） ####
Caused by: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:

**Comment by cgspine** [comment]
https://github.com/QMUI/QMUI_Android/wiki/QMUI-Q-&-A
依赖包冲突？
