### ISSUE TITLE
關於 LauncherActivity

### ISSUE THREAD

**Issue by tenSunFree** [QMUI/QMUI_Android#20]
### 具体问题描述 ###
![2017-09-04_074507](https://user-images.githubusercontent.com/23090085/30007614-82746ae8-9145-11e7-84a4-8328b63d30b0.jpg)

這個Activity 的作用是什麼? 只是單純地跳轉到其它的Activity, 還是有別的用意?

**Comment by cgspine** [comment]
![image](https://user-images.githubusercontent.com/7828876/30009444-0d4ff6f4-915b-11e7-9b63-44807adff936.png)
