### ISSUE TITLE
我想问下 QMUIFragment 怎样优雅的实现 replace 方法

### ISSUE THREAD

**Issue by hewking** [QMUI/QMUI_Android#203]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

### 具体问题描述 ###
你好 我想问下 QMUIFragment 怎样优雅的实现 replace 方法，现在startFragment 直接启动新的fragment。现在需要启动新的fragment后，之前的fragment 可以销毁。类似于finish ，replace 。怎样做比较好

**Comment by cgspine** [comment]
![image](https://user-images.githubusercontent.com/7828876/37501506-a3187bc0-2909-11e8-8f2f-789af9871aab.png)
现在是用的replace。  启动前一个 fragment （不是新的那个）时， 应该不要 addToBackStack 就行。需要自己写一个类似的 startFragment 方法

**Comment by hewking** [comment]
好的 谢谢 这样可以

**Comment by cgspine** [comment]
addToBackStack 存在问题， 请升级到 0.1.0，使用 startFragmentAndDestroyCurrent。
详细分析可以看博文：http://blog.cgsdream.org/2018/04/21/backstack_in_fragment_manager/
