### ISSUE TITLE
请问我该如何修改dialog中的check_mark图标？

### ISSUE THREAD

**Issue by DeveloperHu** [QMUI/QMUI_Android#205]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.0.8`

### 具体问题描述 ###
我在style下进行修改时，想修改dialog中选中的“√”的图标，如下修改无效。请问应该如何修改？
`    <style name="AppTheme" parent="QMUI.Compat.NoActionBar">`
   `       <!-- Customize your theme here. -->`
   `     <item name="qmui_config_color_blue">@color/colorPrimary</item>`
`        <item name="qmui_icon_check_mark">@mipmap/icon_checkmark</item>`
   ` </style>`
#### 异常日志（堆栈） ####
@cgspine

**Comment by chanthuang** [comment]
如果你用的是 `QMUIDialog.MultiCheckableDialogBuilder` 的话，应该是在 style 中加重写：
`<item name="qmui_s_checkbox>@drawable/xxx</item>`

见源码：
`QMUIDialog.MultiCheckableDialogBuilder#addItems` ->
`new QMUIDialogMenuItemView.CheckItemView` ->
` mCheckedView.setImageDrawable(QMUIResHelper.getAttrDrawable(context, R.attr.qmui_s_checkbox))`

**Comment by DeveloperHu** [comment]
我用的是单向选择那个 请问怎么改？

**Comment by cgspine** [comment]
单向选择目前没有主题配置，我会尽快 release 1.1 版本，到时可以通过 theme 配置。
目前你可以在项目drawable目录下添加一个 名称为 qmui_s_dialog_check_mark 的 xml。 可以覆盖 qmui 提供的 drawable

**Comment by DeveloperHu** [comment]
好的感谢
