### ISSUE TITLE
沉浸式状态栏BUG

### ISSUE THREAD

**Issue by a316375** [QMUI/QMUI_Android#207]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

### 具体问题描述 ###
先上代码:
R.layout.activity_main布局文件如下:
<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    >

    <com.qmuiteam.qmui.widget.QMUIAppBarLayout
        android:layout_width="match_parent"
        android:layout_height="256dp"
        android:fitsSystemWindows="true">

        <com.qmuiteam.qmui.widget.QMUICollapsingTopBarLayout
            android:id="@+id/collapsing_topbar_layout"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:layout_scrollFlags="scroll|exitUntilCollapsed"
            app:qmui_collapsedTitleGravity="center"
            app:qmui_contentScrim="?attr/qmui_config_color_blue"
            app:qmui_expandedTitleGravity="center_horizontal|bottom"
            app:qmui_expandedTitleMarginBottom="20dp"
            app:qmui_statusBarScrim="?attr/qmui_config_color_blue">

            <com.qmuiteam.qmui.widget.QMUITopBar
                android:background="@color/colorPrimary"
                android:id="@+id/topbar"
                android:layout_width="match_parent"
                android:layout_height="?attr/qmui_topbar_height"
                android:fitsSystemWindows="true"
                app:qmui_layout_collapseMode="pin"
                app:qmui_topbar_bg_color="@color/qmui_config_color_transparent"
                app:qmui_topbar_need_separator="false"/>

            <ImageView
                android:id="@+id/imageView2"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:contentDescription="这是demo"
                android:fitsSystemWindows="false"
                android:scaleType="centerCrop"
                android:src="@mipmap/ic_launcher"
                app:qmui_layout_collapseMode="parallax"
                app:qmui_layout_collapseParallaxMultiplier="0.7" />
        </com.qmuiteam.qmui.widget.QMUICollapsingTopBarLayout>
    </com.qmuiteam.qmui.widget.QMUIAppBarLayout>

    <android.support.v7.widget.RecyclerView
        android:id="@+id/recyclerView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:scrollbars="none"
        app:layout_behavior="@string/appbar_scrolling_view_behavior"/>
</android.support.design.widget.CoordinatorLayout>

Activity设置如下:
public class MainActivity extends Activity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        QMUIStatusBarHelper.translucent(this);// 沉浸式状态栏
        setContentView(R.layout.activity_main);
        QMUITopBar QMUITopBar=findViewById(R.id.topbar);
        QMUITopBar.setTitle("这是演示");

    }

theme设置如下:
 android:theme="@style/AppTheme"
相关配置如下:
<style name="AppTheme" parent="QMUI.Compat.NoActionBar">
        
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
    </style>

    <style name="QMUI.Compat.NoActionBar" >
        <item name="windowActionBar">false</item>
        <item name="windowNoTitle">true</item>
    </style>
 
.....半小时后解决了,但是..........
解决了可以隐藏图片了,但是没有标题
  <ImageView
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:contentDescription="@string/common_example"
                android:fitsSystemWindows="false"
                android:scaleType="centerCrop"
                android:src="@mipmap/image_big"
                app:qmui_layout_collapseMode="parallax"
                app:qmui_layout_collapseParallaxMultiplier="0.7"/>

#### 问题截图 ####

怎么这个背景图没被隐藏掉?
![screenshot_2018-03-20-22-33-33](https://user-images.githubusercontent.com/16942585/37661325-82b3ec00-2c8f-11e8-97b6-b158cc25df17.png)

解决了问题了:
 <ImageView
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:contentDescription="@string/common_example"
                android:fitsSystemWindows="false"
                android:scaleType="centerCrop"
                android:src="@mipmap/image_big"
                app:qmui_layout_collapseMode="parallax"
                app:qmui_layout_collapseParallaxMultiplier="0.7"/>

,但是没有title,添加以下代码后有两个title;
 QMUITopBar QMUITopBar=(QMUITopBar)findViewById(R.id.topbar);
        QMUITopBar.setTitle("123123456789");

**Comment by cgspine** [comment]
在这种场景下，用 QMUICollapsingTopBarLayout.setTitle(), 不要用 QMUITopBar.setTitle
