### ISSUE TITLE
QMUIFragment 里面有RecyclerView 加载数据后 退出有闪烁卡顿的情况

### ISSUE THREAD

**Issue by hewking** [QMUI/QMUI_Android#209]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6` 
一加5
- [x] 设备系统版本：如 `Android 5.0` 
7.1
- [x] Gradle 版本：如 `2.3.0`
4.4
- [x] QMUI Android 版本：`1.x.x`
最新

### 具体问题描述 ###
如果QMUIFragent 里面是静态页面就正常情况，正常退出正常。如果里面有recyclerview 并且加载了数据。就会出现退出动画卡顿闪烁的情况，很不自然。你有碰到这个情况吗？ 我也想问一下 异步加载数据也会导致进入动画卡顿闪烁

**Comment by cgspine** [comment]
如果在动画过程中进行数据渲染，是会造成卡顿的。读书项目是监听动画完成再渲染数据。这个后续QMUIFragment可以提供支持。

**Comment by hewking** [comment]
嗯 我也在想动画结束在渲染，方便贴一些解决监听的代码吗 谢谢啊

**Comment by cgspine** [comment]
刚刚发布了 arch:0.0.2。 添加了 runAfterAnimation 方法。可以试试

**Comment by hewking** [comment]
好的 多谢 我试试
