### ISSUE TITLE
QMUIListPopup展示不全

### ISSUE THREAD

**Issue by TianDehua** [QMUI/QMUI_Android#210]
### 运行环境 ###

- [x] 设备型号：如：`华为P9`
- [x] 设备系统版本：如 `Android 7.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.0.6`

### 具体问题描述 ###
我写了一个List长按条目时，弹出菜单。使用QMUIListPopup展示菜单内容。发现当条目恰好，处于屏幕底部时，会出现展示不全的问题。
目前是在HuaWei P9上有这个问题。其他手机上还没有发现。
#### 问题截图 ####
![tim 20180321134820](https://user-images.githubusercontent.com/8803718/37696046-9b869654-2d0e-11e8-9d2b-39d9489e672c.png)

**Comment by cgspine** [comment]
其它手机是展示在 item 上面吗？HuaWei P9上展示不全，但可以滚动吗？

**Comment by TianDehua** [comment]
对，展示在item上面（有些像android版微信的效果）。不可以滚动，超过的部分会被裁掉。现在发现在小米5上也有这个问题，也是android 7.0 完整如下图：
![tim 20180322105419](https://user-images.githubusercontent.com/8803718/37748611-6867a1da-2dbf-11e8-8305-dfa2051c533d.png)

**Comment by cgspine** [comment]
使用1.1.0版本还会有这个问题吗？
