### ISSUE TITLE
 QMUICommonListItemView 左右两边能不能自定义设置 字体颜色 和 字体大小？

### ISSUE THREAD

**Issue by as11051105** [QMUI/QMUI_Android#212]
### 运行环境 ###

- [x] 设备型号：如：`一加3`
- [x] 设备系统版本：如 `Android 8.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.0.7`

### 具体问题描述 ###
 QMUICommonListItemView 左右两边能不能自定义设置 字体颜色 和 字体大小？

**Comment by cgspine** [comment]
![image](https://user-images.githubusercontent.com/7828876/37818482-3da447fe-2eb5-11e8-8561-a051463754bf.png)
提供了 get 方法， 直接拿到 TextView。 想修改就比较灵活了

**Comment by as11051105** [comment]
谢谢！
