### ISSUE TITLE
QMUIPopup能扩展自定义背景或者类似QQ的黑色主题样式？

### ISSUE THREAD

**Issue by NicodeLee** [QMUI/QMUI_Android#215]
#### 问题截图 ####
![图片](http://7xlc12.com1.z0.glb.clouddn.com/QQ%E5%9B%BE%E7%89%8720180327104223.png)

**Comment by cgspine** [comment]
如果 RootLayout 的资源文件可以由使用者提供，应该能够满足你的需求吧

**Comment by NicodeLee** [comment]
指示小箭头也有效果吗

**Comment by cgspine** [comment]
指示小箭头也是由 layout 提供的

**Comment by NicodeLee** [comment]
看了下箭头是两个`mArrowUp` `mArrowDown`的Imageview实现的，是在style文件配置？
 layout 提供是指 `mNormalPopup.setContentView();`这里提供？

**Comment by NicodeLee** [comment]
试了下主题配置可以
