### ISSUE TITLE
在build时出现了如图的error

### ISSUE THREAD

**Issue by fanxinglangyue** [QMUI/QMUI_Android#219]
### 运行环境 ###

- [x] 设备型号：如：`honor v9`
- [x] 设备系统版本：如 `Android 8.0`
- [x] Gradle 版本：如 `3.0.1`
- [x] QMUI Android 版本：`1.1.0`

### 具体问题描述 ###
您好，我是纯初学者，今天刚下载的，在build时出现了如图的error，想请教一下这个出现的原因以及如何解决呢？谢谢啦

#### 问题截图 ####
<img width="257" alt="2018-03-29 12 46 41" src="https://user-images.githubusercontent.com/37878002/38043895-d7fd7440-32ea-11e8-9384-d34a61b74c33.png">
<img width="647" alt="2018-03-29 12 46 56" src="https://user-images.githubusercontent.com/37878002/38043898-db61f64c-32ea-11e8-94bc-ed4553e44af5.png">

**Comment by chanthuang** [comment]
见 #93
