### ISSUE TITLE
界面上有两个QMUITabSegment，在点击其中一个触发点击事件后，分别执行selectTab(index)方法,未点击的指示器的位置准确

### ISSUE THREAD

**Issue by Novice9527** [QMUI/QMUI_Android#222]
### 具体问题描述 ###
![tim 20180329165738](https://user-images.githubusercontent.com/35387382/38080014-e72e307a-3372-11e8-9cc7-27e9a55db58b.jpg)

**Comment by chanthuang** [comment]
可能是两个 TagSegment 共用了同一个 Tab 对象？方便贴一下这个界面的两个 TabSegment 相关的代码吗？

**Comment by Novice9527** [comment]
上面的问题在我调用notify之后解决了
