### ISSUE TITLE
引入的QMUIFragment有提供api当AFragment启动BFrament时AFragment finish掉吗

### ISSUE THREAD

**Issue by xh2015** [QMUI/QMUI_Android#223]
引入的QMUIFragment有提供api当AFragment启动BFrament时AFragment finish掉吗。在demo中没有找到，只找到startFragment()和startFragmentForResult()。popBackStack这个方法在startFragment()后调用两个都没有了。

**Comment by cgspine** [comment]
link #203

**Comment by xh2015** [comment]
谢谢

**Comment by cgspine** [comment]
addToBackStack 存在问题， 请升级到 0.1.0，使用 startFragmentAndDestroyCurrent。
详细分析可以看博文：http://blog.cgsdream.org/2018/04/21/backstack_in_fragment_manager/
