### ISSUE TITLE
QMUITopBarLayout  标题出现重叠

### ISSUE THREAD

**Issue by leeyun** [QMUI/QMUI_Android#224]
### 运行环境 ###

- [x] 设备型号：Nexus pixel2
- [x] 设备系统版本：android8.0
- [x] Gradle 版本：3.1.0
- [x] QMUI Android 版本：1.0.7

### 具体问题描述 ###
AFagment startFagment(BFagment)  然后点击返回按钮
QMUITopBarLayout出现显示异常

#### 问题截图 ####

![image](https://user-images.githubusercontent.com/11530379/38132488-dc54f8a2-343d-11e8-95c3-813f1eff7240.png)
![image](https://user-images.githubusercontent.com/11530379/38132493-e00df1f6-343d-11e8-8e36-6e5f7c144129.png)

**Comment by cgspine** [comment]
可以提供下使用代码吗？

**Comment by leeyun** [comment]
@cgspine    我找到问题了  
```
topBar.addRightTextButton("test",R.id.fault_add)
    topBar.addRightTextButton("故障登记", R.id.fault_add)
```
如果出现重复添加的情况就会出现上面的情况。

**Comment by leeyun** [comment]
fragment在kotlin环境下如果使用kotlin-android-extensions  就会出现重复加载addRightTextButton的问题，具体怎么导致的没搞懂......

**Comment by cgspine** [comment]
你在什么时机执行的 addRightTextButton ？

**Comment by leeyun** [comment]
```
override fun onCreateView(): View {
     layout = LayoutInflater.from(activity).inflate(R.layout.fragment_fault_orders,
        null) as RelativeLayout
    layout.topBar.setTitle("故障工单")
    return layout
  }
```
在onActivityCreated中
 ```
   layout.topBar.addRightTextButton("故障登记", R.id.fault_add)//不会出现重叠
    topBar.addRightTextButton("故障登记", R.id.fault_add)//会出现重叠

```
