### ISSUE TITLE
是否考虑分离出精简库？

### ISSUE THREAD

**Issue by minamihoshi** [QMUI/QMUI_Android#227]
### 具体问题描述 ###
是否考虑分离出精简库？
类似Viewpager PullRefresh Listview RecyclerView等开发者很可能有比较成熟的其他方案 全套使用概率低。
是否可能将库分离 精简库中只保留弹窗 按钮 tv 纯色图片等可能使用概率更高的基本控件。

**Comment by MoLice** [comment]
#22 重复
