### ISSUE TITLE
TabSegment  icon 不出现

### ISSUE THREAD

**Issue by naxiaoguang** [QMUI/QMUI_Android#229]
### 运行环境 ###

- [x] 设备型号：如：`红米note 5a `
- [x] 设备系统版本：如 `Android 7`
- [x] Gradle 版本：如 `3.1.0`
- [x] QMUI Android 版本：`1.1.0`

### 具体问题描述 ###
TabSegment 不出现图标，按照提供的案例操作
#### 问题截图 ####
private fun initTabs() {
        tabs.setHasIndicator(false)
        val component = QMUITabSegment.Tab(
                ContextCompat.getDrawable(context!!, R.mipmap.icon_tabbar_component),
                ContextCompat.getDrawable(context!!, R.mipmap.icon_tabbar_component_selected),
                "你好", true
        )

        val util = QMUITabSegment.Tab(
                ContextCompat.getDrawable(context!!, R.mipmap.icon_tabbar_util),
                ContextCompat.getDrawable(context!!, R.mipmap.icon_tabbar_util_selected),
                "你坏", true
        )

        tabs.addTab(component)
        tabs.addTab(util)
    }

**Comment by jiachengliu** [comment]
如果你用的是QMUIPagerAdapter，用 mTabSegment.setupWithViewPager(mViewPager,false,true);
就可以的。而不是mTabSegment.setupWithViewPager(mViewPager);。
