### ISSUE TITLE
是否考虑添加viewpager无限循环滑动的功能？ 感觉蛮常用的功能

### ISSUE THREAD

**Issue by spysoos** [QMUI/QMUI_Android#23]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

**Comment by cgspine** [comment]
无限滚动的功能关键是在 adapter 里 getCount设置一个比较大的值，然后在 instantiateItem 和 destroyItem 层面做数据处理，需要注意的是 getCount 设置为 Integer.MAX_VALUE 会死循环，因此交给业务层面去做会更灵活。

实现可以参考由 alibaba 开源的 UltraViewPager 的 adapter 实现：[https://github.com/alibaba/UltraViewPager/blob/master/ultraviewpager/src/main/java/com/tmall/ultraviewpager/UltraViewPagerAdapter.java](https://github.com/alibaba/UltraViewPager/blob/master/ultraviewpager/src/main/java/com/tmall/ultraviewpager/UltraViewPagerAdapter.java)

**Comment by spysoos** [comment]
文章我看过，先不管有没有无限循环的功能，我的意思是：既然这个库是为了提高UI开发效率，可以考虑加一些一般App使用场景较为普遍的功能，个人拙见
