### ISSUE TITLE
我想问下，更新日志在哪里可以找到，担心更新后有方法冲突

### ISSUE THREAD

**Issue by jiachengliu** [QMUI/QMUI_Android#232]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

**Comment by chanthuang** [comment]
更新日志在 [release 列表](https://github.com/QMUI/QMUI_Android/releases) 中可以看到。如果新版本有不兼容的方法或冲突，会在更新日志中说明的。
