### ISSUE TITLE
QMUIFloatLayout如何获取展示内容的行数

### ISSUE THREAD

**Issue by Demonhuang** [QMUI/QMUI_Android#234]
### 运行环境 ###

- [x] 设备型号：如：`小米mix2`
- [x] 设备系统版本：如 `Android 8.0`
- [x] Gradle 版本：如 `4.1.0`
- [x] QMUI Android 版本：`1.1.1`

### 具体问题描述 ###
QMUIFloatLayout如果是动态填充数据，且每个item的宽度是根据填充内容的宽度自适应的，就会出现每行展示内容不是固定数量，那有什么办法我能知道，一共可以展示多少行呢？

**Comment by Demonhuang** [comment]
如果简单是否可以尽快，这次用到了这个控件，很需要这个方法

**Comment by cgspine** [comment]
可更新到 1.1.2 版本。line count 是在 onMeasure 之后确定的，所以onMeasure 之前调用 getLineCount 会不准确， 因此提供 setOnLineCountChangeListener 来监听行数变化
