### ISSUE TITLE
CustomDialogBuilder 自定义界面怎么获取里面的 自定义按钮的点击事件啊？

### ISSUE THREAD

**Issue by as11051105** [QMUI/QMUI_Android#236]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

### 具体问题描述 ###
CustomDialogBuilder 自定义界面怎么获取里面的 自定义按钮的点击事件啊？

**Comment by cgspine** [comment]
build 出 dialog 后， 通过dialog.findViewById 就行
