### ISSUE TITLE
Activity怎么实现滑动关闭？

### ISSUE THREAD

**Issue by jiachengliu** [QMUI/QMUI_Android#238]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

**Comment by cgspine** [comment]
暂时没有支持单纯的 activity 手势返回。 如果不是 fragment 的管理架构，可以试试https://github.com/bingoogolapple/BGASwipeBackLayout-Android

**Comment by jiachengliu** [comment]
谢谢

**Comment by cgspine** [comment]
现在可以升级到 0.2.0 了, 支持 Activity 手势返回
