### ISSUE TITLE
请问下怎么修改dialog的背景遮罩颜色

### ISSUE THREAD

**Issue by tx123456** [QMUI/QMUI_Android#242]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

### 具体问题描述 ###
怎么修改dialog的背景遮罩颜色，我现在的是透明色，我想要一个半透明的怎么设置

**Comment by cgspine** [comment]
透明色？默认就应该是半透明的吧。

- 如果要全局修改，可以在 theme 中修改 `<item name="qmui_dialog_background_dim_amount">0.6</item>`。

- 如果是要修改某一个 dialog 的，可以在`builder.create(int style)` 中提供一个 style, 并且覆写 `<item name="android:backgroundDimAmount">?attr/qmui_dialog_background_dim_amount</item>` 这一项

之前发现，如果是小米的某些开发版或者某些手机刷机后，半透明遮罩会消失，怎么修改都无法出现的，这种情况就无法修复了，一般是所有 app 的 dialog 都失效，所以可以通过检查微信等app，来区分是否是手机的问题，还是自己的 app 的问题。

**Comment by tx123456** [comment]
感谢回答，刚刚看了微信，发现微信的对话框遮罩也没有了、

**Comment by cgspine** [comment]
那估计是你手机的 ORM 存在问题。 MIUI 9 开发版存在这个问题，他们也在论坛说过是 bug。其它机型就不清楚了
