### ISSUE TITLE
使用QMUI的主题后，EditText的下划线默认颜色变成白色

### ISSUE THREAD

**Issue by caoxingyu** [QMUI/QMUI_Android#245]
使用QMUI的主题后，EditText的下划线默认颜色变成白色，导致看不见，设置colorControlNormal 也没有效果，还有searchView内的搜索图标和清除图标的默认颜色也都变成了白色。

**Comment by cgspine** [comment]
你用的是 <item name="android: colorControlNormal"> 还是 <item name="colorControlNormal"> ? compat 包应该用后者

**Comment by caoxingyu** [comment]
使用最新版本后，默认字体颜色已经不是白色了，但是使用colorControlNormal还是没有效果。确认使用的是colorControlNormal，不是android:colorControlNormal

**Comment by cgspine** [comment]
![image](https://user-images.githubusercontent.com/7828876/39223885-fd033062-4876-11e8-8df6-96e37e799de7.png)
我在 QMUIDemo 里面测试，好像是OK的

**Comment by caoxingyu** [comment]
经过测试使用colorControlActivated是有效的，colorControlNormal没有效果，我把parent="QMUIT.Compat"修改了就有效果了

**Comment by cgspine** [comment]
我测试时，colorControlNormal 也是可以工作的，测试了两个app，都是正常的，会不会是有其它属性影响到了？
