### ISSUE TITLE
QDCollapsingTopBarLayout 

### ISSUE THREAD

**Issue by Theoneee** [QMUI/QMUI_Android#246]
### 运行环境 ###

- [x] 设备型号：如：`PRO 6`
- [x] 设备系统版本：如 `Android 7.0`
- [ ] Gradle 版本：如 `0.0.0`
- [x] QMUI Android 版本：`1.0.5`

### 具体问题描述 ###
ImageView 设置fitsSystemWindows 为true无效。。
这个问题会有什么导致呢。
布局和Demo一样的。
#### 问题截图 ####
![s80423-173020](https://user-images.githubusercontent.com/32156330/39118506-252c6376-471c-11e8-9373-317f5f1e3352.jpg)
![Uploading S80423-173025.jpg…]()

**Comment by theoneee** [comment]
![s80423-173025](https://user-images.githubusercontent.com/32156330/39118554-3fb50d42-471c-11e8-97ab-de6e1c316e91.jpg)

**Comment by cgspine** [comment]
fitsSystemWindows 应该为 false

**Comment by cgspine** [comment]
其次 topbar 应该 不设 title, 否则会重复。QMUICollapsingTopBarLayout 设 title 就好

**Comment by theoneee** [comment]
`<android.support.design.widget.CoordinatorLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <com.qmuiteam.qmui.widget.QMUIAppBarLayout
        android:layout_width="match_parent"
        android:layout_height="256dp"
        android:fitsSystemWindows="true">

        <com.qmuiteam.qmui.widget.QMUICollapsingTopBarLayout
            android:id="@+id/collapsing_topbar_layout"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:qmui_title="@string/index_tv4"
            app:layout_scrollFlags="scroll|exitUntilCollapsed"
            app:qmui_collapsedTitleGravity="center"
            app:qmui_contentScrim="?attr/qmui_config_color_blue"
            app:qmui_expandedTitleGravity="center_horizontal|bottom"
            app:qmui_expandedTitleMarginBottom="20dp"
            app:qmui_statusBarScrim="?attr/qmui_config_color_blue">

            <ImageView
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:fitsSystemWindows="false"
                android:scaleType="centerCrop"
                android:src="@drawable/banner1"
                app:qmui_layout_collapseMode="parallax"
                app:qmui_layout_collapseParallaxMultiplier="0.7"/>

            <com.qmuiteam.qmui.widget.QMUITopBar
                android:id="@+id/topbar"
                android:layout_width="match_parent"
                android:layout_height="?attr/qmui_topbar_height"
                android:fitsSystemWindows="true"
                app:qmui_layout_collapseMode="pin"
                app:qmui_topbar_bg_color="@color/qmui_config_color_transparent"
                app:qmui_topbar_need_separator="false"/>
        </com.qmuiteam.qmui.widget.QMUICollapsingTopBarLayout>
    </com.qmuiteam.qmui.widget.QMUIAppBarLayout>

    <android.support.v7.widget.RecyclerView
        android:id="@+id/recyclerView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:scrollbars="none"
        app:layout_behavior="@string/appbar_scrolling_view_behavior"/>
</android.support.design.widget.CoordinatorLayout>`

**Comment by theoneee** [comment]
这样写的。还是和上面图片情况一样。图片填充不了状态栏。。。

**Comment by cgspine** [comment]
CoordinatorLayout 也应该加 fitSystemWindow = false 吧。 QMUI Demo 是在 重写了 translucentFull() 方法

**Comment by theoneee** [comment]
额。。还是不行。。换另外一个，，

**Comment by theoneee** [comment]
@cgspine 这里的布局RecyclerView可以换成ScrollView嘛。。
