### ISSUE TITLE
Popup 箭头图有半透明白色背景，无法融入非白色背景界面

### ISSUE THREAD

**Issue by hanlyjiang** [QMUI/QMUI_Android#247]
### 运行环境 ###

- [x] 设备型号：如：`Samsung Galaxy Tab S3`
- [x] 设备系统版本：如 `Android 7.0`
- [x] Gradle 版本：如 `3.0.0`
- [x] QMUI Android 版本：`1.0.6`

### 具体问题描述 ###
见截图
#### 问题截图 ####
<img width="121" alt="jietu20180424-093921" src="https://user-images.githubusercontent.com/7868304/39161611-27d716b0-47a4-11e8-9b9b-288bf00db968.png">
<img width="425" alt="jietu20180424-093757" src="https://user-images.githubusercontent.com/7868304/39161622-3429fee6-47a4-11e8-89e4-fe5b97d8a9dc.png">

#### 异常日志（堆栈） ####
无

**Comment by cgspine** [comment]
恩，检查了下，确实是切图失误了，抱歉，你目前先可以通过 theme 换掉上下箭头
![image](https://user-images.githubusercontent.com/7828876/39163355-b51a1272-47ac-11e8-9d9c-aa2a72ea10e3.png)

**Comment by hanlyjiang** [comment]
@cgspine 了解

**Comment by Lindexter** [comment]
那个白色圆角矩形在非白色下面也是不显示圆角

**Comment by cgspine** [comment]
1.1.4 版本修复了这个问题
