### ISSUE TITLE
add&replace

### ISSUE THREAD

**Issue by tenSunFree** [QMUI/QMUI_Android#25]
### 具体问题描述 ###
add
![01](https://user-images.githubusercontent.com/23090085/30016588-57918944-9188-11e7-8308-8803a89c53d6.jpg)

replace
![02](https://user-images.githubusercontent.com/23090085/30016594-5fdcd4a0-9188-11e7-9b2c-b0bde666b89c.jpg)

我有個疑問, 如果將add 修改成replace, 會是比較好的選擇嗎? 為什麼?

**Comment by cgspine** [comment]
![image](https://user-images.githubusercontent.com/7828876/30017389-8cfe23fa-918b-11e7-812e-a471b277d0cc.png)

replace 的本质是 remove 已经 add 的 fragment，然后 add 新的 fragment。如果是第一个 fragment 的话，replace 和 add 最后的效果一样，但 replace 会走更多的逻辑判断。

第二个 fragment 以及之后加入的 fragment 应该用 replace，因为这样可以释放 View， 代码可见
 BaseFragmentActivity.startFragment
