### ISSUE TITLE
设置了QMUITopBar 的PaddingTop，标题没有下移

### ISSUE THREAD

**Issue by chengh2016** [QMUI/QMUI_Android#250]
### 运行环境 ###

- [x] 设备型号：如：`Redmi Note 4X`
- [x] 设备系统版本：如 `Android 7.0`
- [x] Gradle 版本：如 `4.1`
- [x] QMUI Android 版本：`1.0.6`

### 具体问题描述 ###
设置了QMUITopBar 的PaddingTop，标题没有下移，没有找到和返回按钮的对齐方法
#### 问题截图 ####
![tim 20180425105221](https://user-images.githubusercontent.com/18166794/39224077-db8acd04-4877-11e8-830a-7190d1575882.png)

**Comment by jiachengliu** [comment]
有没有添加android:fitsSystemWindows="true"

**Comment by chengh2016** [comment]
加了在QMUITopBar 下，仍然没有效果

**Comment by cgspine** [comment]
可以提供下布局代码吗？

**Comment by chengh2016** [comment]
抱歉，已解决，没有用QMUITopBarLayout

**Comment by xiaoli-style** [comment]
我也遇到了相同的问题，方便贴一下你的topbar布局代码吗？感谢 @chengh2016
