### ISSUE TITLE
关于QMUILinkTextView识别手机号的规则

### ISSUE THREAD

**Issue by magic0908** [QMUI/QMUI_Android#251]
有一个情况，比如QMUILinkTextView里有个微信号“king765920666”，但是QMUILinkTextView却识别到“765920666”是个手机号而高亮显示，手机号通常都是11位数。那么怎么设置只识别11位数字并且是手机号才高亮显示的规则？

**Comment by cgspine** [comment]
QMUILinkTextView，使用了从官方copy而来 Linkify，适配了微信的识别方案，暂时没有更多的自定义功能。如果只是想识别11位数字，可以直接直接用正则匹配 + QMUISpanTouchFixTextView + QMUITouchableSpan 来做就好
