### ISSUE TITLE
混淆代码之后报错，请问怎么配置混淆代码

### ISSUE THREAD

**Issue by keanbin01** [QMUI/QMUI_Android#252]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `3.1.1`
- [x] QMUI Android 版本：`1.x.x`

### 具体问题描述 ###
在库module配置：
// qmui
    api('com.qmuiteam:qmui:1.0.6') {
        exclude group: 'com.android.support'
    }

debug 版本没有问题，release 版本编译出现问题：
........
Warning: com.qmuiteam.qmui.widget.QMUIAppBarLayout: can't find referenced method 'int getChildCount()' in program class com.qmuiteam.qmui.widget.QMUIAppBarLayout
Warning: com.qmuiteam.qmui.widget.QMUIAppBarLayout: can't find referenced method 'android.view.View getChildAt(int)' in program class com.qmuiteam.qmui.widget.QMUIAppBarLayout
Note: com.google.gson.internal.UnsafeAllocator: can't find dynamically referenced class sun.misc.Unsafe
Note: com.qmuiteam.qmui.util.QMUIDeviceHelper: can't find dynamically referenced class android.os.SystemProperties
Note: com.qmuiteam.qmui.util.QMUIDisplayHelper: can't find dynamically referenced class com.android.internal.R$dimen
Note: com.qmuiteam.qmui.util.QMUIStatusBarHelper: can't find dynamically referenced class android.view.MiuiWindowManager$LayoutParams
Note: com.qmuiteam.qmui.util.QMUIStatusBarHelper: can't find dynamically referenced class com.android.internal.R$dimen
Note: kotlin.internal.PlatformImplementationsKt: can't find dynamically referenced class kotlin.internal.jdk8.JDK8PlatformImplementations
Note: kotlin.internal.PlatformImplementationsKt: can't find dynamically referenced class kotlin.internal.JRE8PlatformImplementations
Note: kotlin.internal.PlatformImplementationsKt: can't find dynamically referenced class kotlin.internal.jdk7.JDK7PlatformImplementations
Note: okhttp3.internal.platform.AndroidPlatform: can't find dynamically referenced class com.android.org.conscrypt.SSLParametersImpl
Note: okhttp3.internal.platform.AndroidPlatform: can't find dynamically referenced class org.apache.harmony.xnet.provider.jsse.SSLParametersImpl
Note: okhttp3.internal.platform.AndroidPlatform$CloseGuard: can't find dynamically referenced class dalvik.system.CloseGuard
Note: okhttp3.internal.platform.ConscryptPlatform: can't find dynamically referenced class org.conscrypt.ConscryptEngineSocket
Note: okhttp3.internal.platform.Platform: can't find dynamically referenced class sun.security.ssl.SSLContextImpl
Note: com.google.gson.internal.UnsafeAllocator accesses a declared field 'theUnsafe' dynamically
Note: com.qmuiteam.qmui.util.QMUIDisplayHelper accesses a field 'status_bar_height' dynamically
Note: com.qmuiteam.qmui.util.QMUIStatusBarHelper accesses a field 'EXTRA_FLAG_STATUS_BAR_DARK_MODE' dynamically
Note: com.qmuiteam.qmui.util.QMUIStatusBarHelper accesses a field 'status_bar_height_large' dynamically
Note: com.qmuiteam.qmui.util.QMUIStatusBarHelper accesses a field 'status_bar_height' dynamically
Note: kotlin.reflect.jvm.internal.KClassImpl$Data$objectInstance$2 accesses a declared field 'INSTANCE' dynamically
........
Warning: there were 2 unresolved references to program class members.
         Your input classes appear to be inconsistent.
         You may need to recompile the code.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedprogramclassmember)
Warning: Exception while processing task java.io.IOException: Please correct the above warnings first.
Thread(Tasks limiter_1): destruction
:app:transformClassesAndResourcesWithProguardForRelease FAILED

**Comment by cgspine** [comment]
> A program class is referring to a field or a method that is missing from another program class. The warning lists both the referencing class and the missing referenced class member. Your compiled class files are most likely inconsistent. Possibly, some class file didn't get recompiled properly, or some class file was left behind after its source file was removed. Try removing all compiled class files and rebuilding your project.

有试过链接提供的方式吗？QMUI 并没有特殊的配置，应该一般默认的 ProGuard 配置就可行的
