### ISSUE TITLE
style 中覆盖 textAppearance 样式不起作用

### ISSUE THREAD

**Issue by Shu-Ji** [QMUI/QMUI_Android#257]
### 运行环境 ###

- [x] 设备型号：如：`Mi 5`
- [x] 设备系统版本：如 `Android 7.0`
- [x] Gradle 版本：如 `3.1.2`
- [x] QMUI Android 版本：`1.1.0`

### 具体问题描述 ###

在 styles.xml 根 theme 中覆盖样式不生效：

`qmui_bottom_sheet_list_item_height` 可以覆盖成功，但是 `qmui_bottom_sheet_list_item_text_appearance` 不起作用。

#### 问题截图 ####

代码：

![image](https://user-images.githubusercontent.com/1127594/39346802-893d3fda-4a22-11e8-8a5c-df0f9789f710.png)

效果（可以看到高度确实生效了，但是文字颜色等均没有生效）：

![image](https://user-images.githubusercontent.com/1127594/39346866-d4aeea54-4a22-11e8-8937-1196c01c9df5.png)

将 QMUI 源码 `qmui_bottom_sheet_list_item.xml` 中的 `textAppearance` 修改为 `style` 之后，起作用了。

修改的位置：

![image](https://user-images.githubusercontent.com/1127594/39347048-9605b868-4a23-11e8-8e16-c184b9425a11.png)

![image](https://user-images.githubusercontent.com/1127594/39347033-841c3f96-4a23-11e8-8987-433be292c627.png)

**Comment by cgspine** [comment]
我在demo测试改颜色和字体大小都能正常工作。我猜会不会是覆写 android:textViewStyle 导致的。

**Comment by Shu-Ji** [comment]
@cgspine 估计是，懒得测了，最后自定义了一个 builder 自己控制显示的样式。感谢！
