### ISSUE TITLE
刘海屏获取状态栏高度问题

### ISSUE THREAD

**Issue by simplezhli** [QMUI/QMUI_Android#258]
### 运行环境 ###

- [x] 设备型号：如：`模拟器`
- [x] 设备系统版本：如 `Android 9.0`
- [x] Gradle 版本：如 `3.0.1`
- [x] QMUI Android 版本：`1.1.1`

### 具体问题描述 ###

在9.0的模拟器下，我将刘海设置出来后。使用**getStatusbarHeight**获取状态栏高度错误。查看源码发现在**initStatusBarHeight**方法有判断如果获取的状态高度大于2倍25dp的话，则返回默认高度的25dp。（刘海屏手机状态栏高度普遍大于2倍，且没有统一规范。）建议暂时去除该判断。

**Comment by cgspine** [comment]
我暂时去掉了。不过适配刘海屏推荐还是用 fitSystemWindows 那一套。
