### ISSUE TITLE
QMUI沉浸式状态栏颜色渐变问题

### ISSUE THREAD

**Issue by xiaoli-style** [QMUI/QMUI_Android#259]
### 运行环境 ###

- [x] 设备型号：MI5
- [x] 设备系统版本：Android7.0
- [x] Gradle 版本：3.1.2
- [x] QMUI Android 版本：1.0.6

### 具体问题描述 ###
想实现如QQ标题栏的颜色渐变，但我没有找到相关方法，我目前只能通过设置**topbar.setBackgroundResource**来实现渐变，但状态栏只能设置纯色，比较苦恼，请问有办法可以实现下图的效果吗？
### 问题截图 ###
![1212](https://user-images.githubusercontent.com/35419620/39529742-fbf186fe-4e59-11e8-8c3e-59be74e9f78c.png)

**Comment by xiaoli-style** [comment]
已经解决这个问题了，但是产生了新的问题。Topbar的Title往上移了。

activity代码中使用
**QMUIStatusBarHelper.translucent(this);**
并且设置了**Topbar.setPadding(top);**

Topbar的布局
![top](https://user-images.githubusercontent.com/35419620/39537260-959696c6-4e6b-11e8-8c5b-8a461b5a1ac8.png)


## 最终效果
![111](https://user-images.githubusercontent.com/35419620/39537288-aa3ce756-4e6b-11e8-81c9-d8c5da361ba7.png)

请问一下这个问题应该怎么处理呢？

**Comment by cgspine** [comment]
你这个 paddingTop 设置在 QMUITopBarLayout 应该就不会有这个问题吧。paddingTop最好也是用fitSystemWindow的方式来解决最好

**Comment by cgspine** [comment]
![image](https://user-images.githubusercontent.com/7828876/39562784-18b6fac2-4ee0-11e8-8767-419c9f388b99.png)
以 QMUIDemo 的 QDAboutFragment 为例子，设置一个渐变背景就可以实现类似的效果

**Comment by xiaoli-style** [comment]
谢谢，已经解决，如果有人遇到跟我一样的问题。请使用我的解决方案：
1、使用QMUITopBarLayout包围QMUITopBar，并在QMUITopBarLayout里增加android:fitsSystemWindows="true"
2、Activity使用QMUIStatusBarHelper.translucent(this);方法
3、QMUITopBarLayout设置好渐变的shape

**Comment by China-Android** [comment]
假如是fragment该咋办
