### ISSUE TITLE
topBar添加右边按钮或者文字的时候，左边也对应的出现

### ISSUE THREAD

**Issue by WinWang** [QMUI/QMUI_Android#260]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.1.2`

### 具体问题描述 ###
topBar添加右边按钮或者文字的时候，左边也对应的出现
#### 问题截图 ####
![2345 20180504151356](https://user-images.githubusercontent.com/19348069/39616443-ff353162-4fad-11e8-93e9-aa3b5290151c.png)
![2345 20180504151423](https://user-images.githubusercontent.com/19348069/39616446-0296b9de-4fae-11e8-9a13-71aa3ddfd521.png)

**Comment by xiaoli-style** [comment]
![j6 8f xcft9v s 8qe 0gk](https://user-images.githubusercontent.com/35419620/39624576-715a4cbe-4fcc-11e8-930f-5e4e377d8e00.png)
小伙子，你同时添加了左右两个ImageButton

**Comment by WinWang** [comment]
尴尬了，api看错了。。。。。
