### ISSUE TITLE
listview不显示滚动条

### ISSUE THREAD

**Issue by qiuh1016** [QMUI/QMUI_Android#261]
### 运行环境 ###

- [x] 设备型号：华为荣耀8、魅蓝note2
- [x] 设备系统版本：5.1、 7.0
- [x] Gradle 版本：3.0.1
- [x] QMUI Android 版本：1.0.6

### 具体问题描述 ###

ListView不显示滚动条

加上android:scrollbars="vertical"、android:scrollbarSize="10dp"或者代码里设置滚动条为true也都没有用

但是下载的demo app 里面是有的

**Comment by cgspine** [comment]
是否是java代码里调用了 `setScrollbarFadingEnabled `呢？

**Comment by qiuh1016** [comment]
没有加```setScrollbarFadingEnabled```哦，我还特意去重新建了个工程，然后最简单的显示一个listview，也没有滚动条，我就很奇怪了。难道你们都是好的😂

**Comment by cgspine** [comment]
listview 里的数据够多然后可以滚动？

**Comment by qiuh1016** [comment]
是的 可以滚动

**Comment by cgspine** [comment]
我新建一个项目，好像也没有任何问题😂

**Comment by qiuh1016** [comment]
我说一下我的步骤吧：

1. android studio 新建工程
2. gradle 添加 ```implementation 'com.qmuiteam:qmui:1.0.6'```
3. styles.xml 中 改 ```parent="QMUI.Compat" ```
4. MainActivity 中添加最简单的ListView， 添加数据让ListView能滚动
5. 运行

然后就没有滚动条 😂，我还让同事也搞了一下，也没有。。。style设置不对吗

**Comment by cgspine** [comment]
我做了尝试，把 qmui 版本升级到最新的 1.1.2 就不会有问题，但 1.0.6 版本后并没有改动过相关的 theme。我估计是 1.0.6 版本依赖的 appcompat-v7:27.0.1 存在问题。最新版依赖的是 27.1.0，不会有问题

**Comment by qiuh1016** [comment]
ok 解决了，非常感谢
