### ISSUE TITLE
QMUIGroupListView如何取消点击的水波纹特效

### ISSUE THREAD

**Issue by taoxinyi** [QMUI/QMUI_Android#263]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

### 具体问题描述 ###
QMUIGroupListView如何取消点击的水波纹特效，只想让用户点击右侧按钮时生效，而不是点击item的任意位置。

**Comment by cgspine** [comment]
1. 调用 `QMUIGroupListView.setSeparatorStyle(SEPARATOR_STYLE_NORMAL)`
2. 调用 `QMUIGroupListView.newSection(context).setSeparatorDrawableRes()` 设置自定义背景 drawable。 四个参数分别是四种情况下的背景 drawable
