### ISSUE TITLE
EditTextDialog的setInputType方法有的不管用

### ISSUE THREAD

**Issue by zilingyao** [QMUI/QMUI_Android#264]
### 运行环境 ###

- [x] 设备型号：如：`mi6`
- [x] 设备系统版本：如 `Android 8.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

### 具体问题描述 ###
InputType.TYPE_NUMBER_FLAG_DECIMAL 无效果

**Comment by cgspine** [comment]
`InputType.TYPE_CLASS_NUMBER | InputType.TYPE_NUMBER_FLAG_DECIMAL`
