### ISSUE TITLE
在fragment中沉浸式问题

### ISSUE THREAD

**Issue by xiaoli-style** [QMUI/QMUI_Android#266]
### 运行环境 ###

- [x] 设备型号：MI5
- [x] 设备系统版本：android7.0
- [x] Gradle 版本：3.1.2
- [x] QMUI Android 版本：1.0.6

### 具体问题描述 ###
TopBar布局使用android:fitsSystemWindows="true"在activity中正常，但是在fragment中就不正常了，fitsSystemWindows失效，请问这个有什么好的解决方案吗？
#### 问题截图 ####
![qq_pic_merged_1525765265846](https://user-images.githubusercontent.com/35419620/39744262-40106578-52d6-11e8-84a0-dbdabdaf8748.jpg)

**Comment by xiaoli-style** [comment]
我的fragment是getSupportFragmentManager()
然后add进去的，topbar也已经添加了android:fitsSystemWindows="true"
在activity中是正常的

**Comment by yuwoquan** [comment]
com.qmuiteam.qmui.widget.QMUIWindowInsetLayout貌似用这个就可哟

**Comment by xiaoli-style** [comment]
@yuwoquan 

> <com.qmuiteam.qmui.widget.QMUIWindowInsetLayout
            android:id="@+id/content"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:fitsSystemWindows="true">
        </com.qmuiteam.qmui.widget.QMUIWindowInsetLayout>

这是布局，我用add(R.id.content, fragment)添加fragment，但是依旧是如上图那样的。

**Comment by cgspine** [comment]
R.id.content 是 QMUIWindowInsetLayout 吗？如果 R.id.content 为 QMUIWindowInsetLayout， fragment 的 view 添加 fitsSystemWindows="true"，应该可以

**Comment by xiaoli-style** [comment]
@cgspine 
依旧是没有效果的，R.id.content 是 QMUIWindowInsetLayout
然后fragment的view的布局，每个都引用了topbar
<include layout="@layout/topbar" />

topbar的布局已经添加了android:fitsSystemWindows="true"

也就是说每个布局都有fitsSystemWindows
