### ISSUE TITLE
想全屏预览图片，状态栏没法透明

### ISSUE THREAD

**Issue by Puppy-Love** [QMUI/QMUI_Android#267]
### 运行环境 ###

- [x] 设备型号：如：`魅族 Note 3`
- [x] 设备系统版本：如 `Android 7.0`
- [x] Gradle 版本：如 `3.3.1`
- [x] QMUI Android 版本：`1.1.0`

**Comment by xiaoli-style** [comment]
可以隐藏状态栏呀

**Comment by Puppy-Love** [comment]
@xiaoli-style 恩 没有这个方法吧？你是说setFull 全屏吗？

**Comment by cgspine** [comment]
使用 QMUIStatusBarHelper.translucent() ?
