### ISSUE TITLE
QMUIGroupListView能滑动吗？

### ISSUE THREAD

**Issue by androidflying** [QMUI/QMUI_Android#273]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

### 具体问题描述 ###
QMUIGroupListView添加的条目超出屏幕时，不能滑动
#### Layout Inspector 文件([如何获取](https://github.com/QMUI/QMUI_Android/wiki/%E6%8F%90%E4%BE%9B-Layout-Inspector-%E6%96%87%E4%BB%B6)) ####
<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/tab_panel_bg">

    <FrameLayout
        android:id="@+id/frameLayout"
        android:layout_width="match_parent"
        android:layout_height="240dp">

        <ImageView
            android:id="@+id/fragment_user_header"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:scaleType="centerCrop" />

        <LinearLayout
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="center"
            android:gravity="center"
            android:orientation="vertical">

            <com.qmuiteam.qmui.widget.QMUIRadiusImageView
                android:id="@+id/iv_user_header"
                android:layout_width="64dp"
                android:layout_height="64dp"
                android:scaleType="centerCrop"
                android:src="@mipmap/ic_launcher_round"
                app:qmui_border_width="0dp"
                app:qmui_is_circle="true" />

            <TextView
                android:id="@+id/tv_name"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:paddingTop="8dp"
                android:textColor="@color/white"
                android:textSize="@dimen/sp_12" />
        </LinearLayout>

    </FrameLayout>

    <ScrollView
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:orientation="vertical"
        android:background="@color/qmui_config_color_background"
        android:scrollbars="none"
        app:layout_constraintTop_toBottomOf="@+id/frameLayout">

        <com.qmuiteam.qmui.widget.grouplist.QMUIGroupListView
            android:id="@+id/groupListView"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />

    </ScrollView>

</android.support.constraint.ConstraintLayout>

**Comment by cgspine** [comment]
QMUIGroupListView 的 layout_height 为 wrap_content ?

**Comment by androidflying** [comment]
@cgspine 也不行，最开始用的就是wrap_content。

**Comment by androidflying** [comment]
@cgspine 单独写的时候可以

<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".ui.OpenSourceActivity">
<ScrollView
    android:layout_width="match_parent"
    android:layout_height="match_parent">
    <com.qmuiteam.qmui.widget.grouplist.QMUIGroupListView
        android:id="@+id/groupListView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>
</ScrollView>
</android.support.constraint.ConstraintLayout>

**Comment by cgspine** [comment]
如果scrollView 补上 app:layout_constraintBottom_toBottomOf="parent" 呢？

**Comment by androidflying** [comment]
@cgspine 可以了。Thanks
