### ISSUE TITLE
QMUI activity滑动切换问题

### ISSUE THREAD

**Issue by xiaoli-style** [QMUI/QMUI_Android#277]
### 运行环境 ###

- [x] Gradle 版本：666
- [x] 设备型号：MI5
- [x] 设备系统版本：Android7.0
- [x] QMUI Android 版本：1.0.6

### 具体问题描述 ###
我看QMUI demo里面，它载入窗口后可以像微信那样手指按住窗口边缘右滑关闭，请问下该功能是QMUI自带的吗？还是说怎么实现的？

**Comment by cgspine** [comment]
http://blog.cgsdream.org/2018/01/14/about-android-swipe-back/
这是 qmui-arch 模块实现的功能
