### ISSUE TITLE
無法關閉App

### ISSUE THREAD

**Issue by tenSunFree** [QMUI/QMUI_Android#28]
### 具体问题描述 ###
![2017-09-04_175519](https://user-images.githubusercontent.com/23090085/30021652-a516366c-919a-11e7-8cf9-2ad6ef81d5a7.jpg)

請教一下, 紅框內的程式碼 是用來產生主畫面的, 如果在主畫面按下手機的返回鍵, 會關閉此App

我剛剛把紅框內的程式碼先刪掉, 然後運行, 顯示的是白屏 是可以理解的, 因為紅框內的代碼不在
但是此時 我反覆按下手機的返回鍵, 卻無法結束此App, 是什麼原因?

**Comment by cgspine** [comment]
因为我们重写了 BaseFragmentActivity.onBackPressed 来实现 fragment 的 返回操作，但判断逻辑有遗漏。
