### ISSUE TITLE
SwipeBack兼容性问题。滑动返回的时候，底层界面白板。

### ISSUE THREAD

**Issue by zichen-jiao** [QMUI/QMUI_Android#280]
### 运行环境 ###

- [x] 设备型号：如：`nova 2s`
- [x] 设备系统版本：如 `Android 8.0`
- [x] Gradle 版本：如 `4.4`
- [x] QMUI Android 版本：`1.1.2`

### 具体问题描述 ###
在Android8.0系统版本上，滑动返回时，下边的界面不能透明显示，看到的是白板界面。直到下面的界面显示出来之后，才会恢复正常显示。
#### 问题截图 ####
![1526637869029](https://user-images.githubusercontent.com/5227656/40229213-2b16d89e-5ac6-11e8-9b92-1c44a0e10116.jpg)

**Comment by cgspine** [comment]
arch 版本多少？ 0.1.0？ 0.1.0应该没有这个问题

**Comment by zichen-jiao** [comment]
之前是0.0.1，换成0.1.0 之后好了。感谢。
