### ISSUE TITLE
QMUIRadiusImageView demo中圆角矩形 显示的是圆形

### ISSUE THREAD

**Issue by zijinzhiyun** [QMUI/QMUI_Android#284]
### 具体问题描述 ###
默认为圆形
#### 问题截图 ####
![screenshot_20180521-163245](https://user-images.githubusercontent.com/21994586/40298183-d4ca486c-5d14-11e8-95f8-b4613c724ea8.png)

**Comment by cgspine** [comment]
谢谢反馈，默认主题不该添加 qmui_is_circle 为 true。
