### ISSUE TITLE
QMUITabSegment内容自适应问题

### ISSUE THREAD

**Issue by zijinzhiyun** [QMUI/QMUI_Android#285]
### 具体问题描述 ###
QMUI demo中 如果“内容自适应，超过父容器则滚动”这个页面的tab较少，就会漏出背景色。截图为我修改为3个tab
#### 问题截图 ####
![img_20180521_185005](https://user-images.githubusercontent.com/21994586/40304204-595d9544-5d28-11e8-8813-9976cafb686d.png)

**Comment by cgspine** [comment]
请更新至 v1.1.3
