### ISSUE TITLE
build 出错

### ISSUE THREAD

**Issue by zijinzhiyun** [QMUI/QMUI_Android#286]
### 具体问题描述 ###
Error:(121, 33) 错误: 不兼容的类型: View无法转换为SwipeToLoadLayout
#### 问题截图 ####
<img width="471" alt="image" src="https://user-images.githubusercontent.com/21994586/40311176-b2595f84-5d41-11e8-9611-e0b9c3ac54e5.png">
<img width="577" alt="image" src="https://user-images.githubusercontent.com/21994586/40311263-e38790bc-5d41-11e8-9f88-57c789942051.png">

**Comment by cgspine** [comment]
support包没有用到27之前，findViewById 是需要强制转换类型的

**Comment by zijinzhiyun** [comment]
没有引用compile 'com.qmuiteam:qmui:1.1.2' 可以正常使用，引用后，就会报错，需要怎么修改呢
