### ISSUE TITLE
 QMUIGroupListView能设置透明背景吗

### ISSUE THREAD

**Issue by yuwoquan** [QMUI/QMUI_Android#287]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

### 具体问题描述 ###
 QMUIGroupListView.newSection(getContext())
                .setSeparatorDrawableRes(R.drawable.bg)能设置背景图片，但是设置他的background是不起作用的，依旧是白色，请问能通过什么方法的设置透明背景吗

**Comment by cgspine** [comment]
这里要求传入一个drawable的resId，所以你可以建立一个xml，写一个透明的shape传入进去就行：
![image](https://user-images.githubusercontent.com/7828876/40340876-3954024c-5db4-11e8-8120-132e5d166f5c.png)

**Comment by yuwoquan** [comment]
感谢。

**Comment by yuwoquan** [comment]
![image](https://user-images.githubusercontent.com/26847367/40369560-c8e4e064-5e10-11e8-9551-22da0f1f3cf1.png)
添加之后第一个item跟最后一个item还是无法改变颜色
   QMUIGroupListView.newSection(getContext())
                .setTitle("Section 1: 默认提供的样式")
                .setDescription("Section 1 的描述")
                .addItemView(normalItem, onClickListener)
                .addItemView(itemWithDetail, onClickListener)
                .addItemView(itemWithDetailBelow, onClickListener)
                .addItemView(itemWithChevron, onClickListener)
                .addItemView(itemWithSwitch, onClickListener)
                .setSeparatorDrawableRes(R.drawable.grouplistview_bg)
                .addTo(mGroupListView);
在官网demo修改

**Comment by dws2016** [comment]
`setSeparatorDrawableRes 方法有两个,一个参数的那个是设置中间middle的样式, 要设置全部的得分别设置single,top,bottom,midlle这四个位置的样式,我也是从主题中查到的,具体参考主题 QMUI.Compat 的 qmui list item bg 里的内容设置`
