### ISSUE TITLE
主题会直接覆盖colorPrimaryDark？

### ISSUE THREAD

**Issue by vihuela** [QMUI/QMUI_Android#29]
### 运行环境 ###

- [x] 设备型号：nexus 5x
- [x] 设备系统版本：7.0
- [x] Gradle 版本：4.1
- [x] QMUI Android 版本：1.0.1

### 具体问题描述 ###
主题直接继承：QMUI.Compat.NoActionBar，发现qmui_config_color_blue会直接覆盖掉colorPrimaryDark

**Comment by cgspine** [comment]
是的，如果需要更改colorPrimaryDark， 需要在自己的主题下再次覆盖

**Comment by vihuela** [comment]
@cgspine 只要覆盖qmui_config_color_blue就可以了，原理是什么，源码是通过代码获取qmui_config_color_blue写入colorPrimaryDark么？，没找到

**Comment by cgspine** [comment]
![image](https://user-images.githubusercontent.com/7828876/30099588-bc95320a-9318-11e7-91d7-1674e4794b64.png)

**Comment by vihuela** [comment]
可以，谢谢
