### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by baohexin** [QMUI/QMUI_Android#290]
LauncherActivity,QDMainActivity有内存泄漏问题

**Comment by cgspine** [comment]
是用 LeakCanary 检测出的和 InputMethodManager 相关的泄漏？这个应该是 Android 系统的原因，讨论见 https://stackoverflow.com/questions/34631818/leakcanary-report-leak-in-inputmethodmanager。

**Comment by diricse** [comment]
我刚下的，在手机上运行也内存泄漏，在手机上自动生成一个内存泄漏的图标，我的手机是华为荣耀7
