### ISSUE TITLE
QMUIBottomSheet在Grid下如何设置每行个数

### ISSUE THREAD

**Issue by dingputongxi** [QMUI/QMUI_Android#291]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

### 具体问题描述 ###
QMUIBottomSheet在Grid下如何设置每行个数,比如现在每行默认是4个，如何修改为其他个数

**Comment by cgspine** [comment]
你是指的是每行多少个可以刚好撑满空间？

**Comment by dingputongxi** [comment]
是的，表述不太好，呵呵

**Comment by cgspine** [comment]
在 theme 中重写 qmui_bottom_sheet_grid_item_mini_width/qmui_bottom_sheet_grid_item_icon_size 等属性，应该可满足需求

**Comment by dingputongxi** [comment]
好的，谢谢！
