### ISSUE TITLE
coordinatorlayout + recyclerview 最后一个item显示不全

### ISSUE THREAD

**Issue by wolfworld** [QMUI/QMUI_Android#293]
### 运行环境 ###

- [x] 设备型号：如：`荣耀9`
- [x] 设备系统版本：如 `Android 8.0`
- [x] Gradle 版本：如 `3.1.2`
- [x] QMUI Android 版本：`1.x.x`

### 具体问题描述 ###
CoordinatorLayout布局中嵌套recyclerview ，recyclerview 的最后一个item显示不全，QMUI官方的demo也有这个问题。

#### 
问题截图 ####
![_20180528002849](https://user-images.githubusercontent.com/17454328/40588323-6539efc6-620e-11e8-97b1-836f04d88e14.jpg)

**Comment by androidflying** [comment]
在 CollapsingToolbarLayout.中添加android:minHeight="?actionBarSize” 属性

**Comment by cgspine** [comment]
谢谢反馈。补上 android:minHeight="?attr/qmui_topbar_height" 就可以了
