### ISSUE TITLE
QMUIPullRefreshLayout 配合 RecyclerView 使用下拉刷新滑动问题

### ISSUE THREAD

**Issue by ToGallop** [QMUI/QMUI_Android#294]
### 运行环境 ###

- [x] 设备系统版本： `Android 7.0`
- [x] QMUI Android 版本：`1.1.2`

### 具体问题描述 ###
1. QMUIPullRefreshLayout 配合 RecyclerView 使用，下拉刷新，在没有下拉刷新完成前就执行开始下一次刷新（第二次下拉是手指始终在屏幕上没有抬起的），待上一次刷新结束后，手指在屏幕上动一下，手指没有离开屏幕。QMUIPullRefreshLayout 马上会执行下拉，而且下拉的高度和第二次手指的位置有关。
2. 当设置 RecyclerView 的 `nestedScrollingEnabled = false` 或者 `isNestedScrollingEnabled = false` 就不会有这个问题

**Comment by cgspine** [comment]
请更新至 v1.1.3

**Comment by mrme2014** [comment]
更新到 v1.1.3   依旧存在问题哦

下拉刷新，在没有下拉刷新完成前就执行开始下一次刷新（第二次下拉是手指始终在屏幕上没有抬起的），待上一次刷新结束后，手指在屏幕上动一下，手指没有离开屏幕。QMUIPullRefreshLayout 马上会执行下拉，而且下拉的高度和第二次手指的位置有关。

**Comment by cgspine** [comment]
什么机型？android 版本多少？ support library 版本多少？（我这边不能重现）

**Comment by mrme2014** [comment]
> 什么机型？android 版本多少？ support library 版本多少？（我这边不能重现）

三星s8+，android8.0系统，support 26.稳定复现上面的问题


可否加个微信，我录视频给你看？
或者最新的bugfix的分支是哪个？

**Comment by cgspine** [comment]
我的微信： 13760840278
qmui 最新版本为 1.1.11 了，目前都在master上开发和做bugfix的
