### ISSUE TITLE
弹起输入法后TopBar异常增高

### ISSUE THREAD

**Issue by xiaoli-style** [QMUI/QMUI_Android#296]
### 运行环境 ###

- [x] 设备型号：MI5
- [x] 设备系统版本：Android 7.0
- [x] Gradle 版本：3.1.2
- [x] QMUI Android 版本：1.0.6

### 具体问题描述 ###
界面上有个EdditText，点击它弹起了输入法后，TopBar异常增高如下图，关闭输入法后恢复正常。这个是神马情况
![1](https://user-images.githubusercontent.com/35419620/40740476-8a456cb8-647b-11e8-8627-6f7a3a4f7648.png)

#### 问题截图 ####
![6wz2rkplkfh qal p 0vta](https://user-images.githubusercontent.com/35419620/40740429-6b9cdb0c-647b-11e8-8d2f-03ae89846e76.png)

**Comment by cgspine** [comment]
升级下版本？，最新已经 1.1.3 了

**Comment by xiaoli-style** [comment]
@cgspine 已经升级了，问题确实还存在

**Comment by xiaoli-style** [comment]
问题已经得到解决，QMUITopBarLayout的android:layout_width设置为wrap_content就可以了，如果设置为match_parent就会出现上面的问题，不知道是库的bug还是哪方面问题

**Comment by cgspine** [comment]
那样确实会存在问题， 因为键盘区域也是 windowInset。 如果只有 QMUITopBarLayout 是 fitSystemWindows = true， 那么 键盘区域的高度也由它消耗，因此 QMUITopBarLayout 会异常。最好 Activity 或者 fragment 的 最外层 View 为 QMUIWindowInsetLayout, 这样键盘区域就会被 QMUIWindowInsetLayout 消耗。  这样才能模仿 windowSoftInputMode = adjustResize 的效果， 目前你的界面，应该 adjustResize 也失效了。

**Comment by xiaoli-style** [comment]
@cgspine 最外层用了QMUIWindowInsetLayout还是存在这个问题，因为我的EditText是放在ScrollView里面的，如果不使用ScrollView没有任何问题

**Comment by xiaoli-style** [comment]
topbar增高的问题暂时解决了，但是出现了新的问题。也是异常增高，弹起输入法后布局留空很多
![056ymp b it j lsvho f](https://user-images.githubusercontent.com/35419620/40776221-b5a1def6-64fc-11e8-8369-f03ae1303e39.png)

标题栏的布局：
<?xml version="1.0" encoding="utf-8"?>
<com.qmuiteam.qmui.widget.QMUIWindowInsetLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    app:qmui_layout_collapseMode="parallax"

    >
<com.qmuiteam.qmui.widget.QMUITopBarLayout
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/topbar_layout"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:paddingBottom="0dp"
    android:paddingLeft="0dp"
    android:paddingRight="0dp"
    android:paddingTop="0dp"
    android:fitsSystemWindows="true"
    >

        <com.qmuiteam.qmui.widget.QMUITopBar
            android:id="@+id/topbar"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:paddingBottom="0dp"
            android:paddingLeft="0dp"
            android:paddingRight="0dp"
            android:paddingTop="0dp"
            app:qmui_topbar_bg_color="@color/qmui_config_color_blue" />
        </com.qmuiteam.qmui.widget.QMUITopBarLayout>
</com.qmuiteam.qmui.widget.QMUIWindowInsetLayout>


界面的布局用了ScrollView+LinearLayout

**Comment by cgspine** [comment]
这不应该呀，我在QD 的 About 界面 做测试，也是 ScrollView+LinearLayout， 但并没有出现问题

**Comment by xiaoli-style** [comment]
@cgspine 具体的我也说不太清楚，我创建了一个demo用来展示这个问题，下载链接[http://apk-1251183729.file.myqcloud.com/MyApplication.zip](url)

**Comment by cgspine** [comment]
![image](https://user-images.githubusercontent.com/7828876/40784638-cbefbd60-6518-11e8-960e-c817703371d4.png)
QMUIWindowInsetLayout 要作为最外层的View，然后里面的包裹 QMUITopbarLayout 和业务View, 业务View也要 fitSystemWindow。这个比较死了。

**Comment by xiaoli-style** [comment]
@cgspine demo您看过了吧，难道真的没有好的解决方案了吗

**Comment by cgspine** [comment]
应该没了吧，fitSystemWindow  必须在最外层拦截。另外的方案，可能需要像 QMUIWindowInsetLayout 一样重写 Topbar 的 fitSystemWindow 的处理逻辑，但可能存在更多的坑点

**Comment by GorCat** [comment]
我遇到了相同的问题，这个 issue 很好的解决了我的疑问
