### ISSUE TITLE
oppo vivo 华为手机 适配吗

### ISSUE THREAD

**Issue by tianshaokai** [QMUI/QMUI_Android#298]
1. 看源码 主要是 针对 小米 魅族 做了一些系统适配
2.现在都出现了刘海屏屏幕，是否支持适配呢

**Comment by xiaoli-style** [comment]
刘海屏也没什么的吧，我猜主要是状态栏的高度变化了，这个应该不需要适配啊，你可以用云真机调试一下

**Comment by tianshaokai** [comment]
@cgspine 关于QMUI_Android 有没有qq群呢，大家交流一下如何使用QMUI_Android

**Comment by cgspine** [comment]
恩，刘海屏主要是全屏下需要适配，之后应该会加一个 helper 类吧。 目前没有 qq 群，用 issue 来交流和管理应该足够了吧

**Comment by tianshaokai** [comment]
好的谢谢

**Comment by thirtyyuan** [comment]
请问现在有各厂商刘海屏的适配方案吗？比如上面说的 helper 类。我看文档还没提到刘海屏。

**Comment by cgspine** [comment]
QMUINotchHelper，用于适配刘海屏，可以看 demo 中的例子。 文档后续会补充上。
