### ISSUE TITLE
QMUIPopup弹出层的背景色

### ISSUE THREAD

**Issue by xiaoli-style** [QMUI/QMUI_Android#299]
### 运行环境 ###

- [x] 设备型号：MI5
- [x] 设备系统版本：Android 7.0
- [x] Gradle 版本：3.1.2
- [x] QMUI Android 版本：1.1.3

### 具体问题描述 ###
请问下QMUIPopup如何设置弹出层的背景色？目前QMUIPopup只提供了setBackgroundDrawable方法，设置后效果如下图。
另外如何设置弹出的位置，目前默认是弹出在界面的中间位置，想让它弹在右侧

#### 问题截图 ####
![81c 8ly9 9q _ 8 u1 7a2q](https://user-images.githubusercontent.com/35419620/40853712-a6eafa7c-6601-11e8-96b5-9d6bce2826ba.png)

**Comment by cgspine** [comment]
1. 更改背景色见：[组件的全局配置与特殊处理](https://github.com/QMUI/QMUI_Android/wiki/%E7%BB%84%E4%BB%B6%E7%9A%84%E5%85%A8%E5%B1%80%E9%85%8D%E7%BD%AE%E4%B8%8E%E7%89%B9%E6%AE%8A%E5%A4%84%E7%90%86)
2. 弹出的位置默认居中，目前只提供了 `setPositionOffsetX` 等几个方法来做偏移

**Comment by xiaowangjunfighting** [comment]
在window离屏幕右边缘比较近时，setPositionOffsetX 方法为50,100,150均没有生效(不符合预期)，设置为-50,-100,-150均可以向左偏移(符合预期)。请问，如何才能使setPositionOffsetX 方法为50,100,150生效？

**Comment by cgspine** [comment]
popupWindow 是没办法偏移到屏幕外的
