### ISSUE TITLE
demo apk install error

### ISSUE THREAD

**Issue by ragnraok** [QMUI/QMUI_Android#3]
Failed to install qmui_1.0.0.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl821929968.tmp/base.apk: META-INF/CERT.SF indicates /data/app/vmdl821929968.tmp/base.apk is signed using APK Signature Scheme v2, but no such signature was found. Signature stripped?]

**Comment by chanthuang** [comment]
签名问题导致无法安装，已更新官网的安装包，重新安装即可。
