### ISSUE TITLE
编译时冲突

### ISSUE THREAD

**Issue by yulinwoniu666** [QMUI/QMUI_Android#30]
### 运行环境 
AS2.3编译时冲突
### 具体问题描述 ###
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(25.3.1) from [com.android.support:design:25.3.1] AndroidManifest.xml:27:9-31
	is also present at [com.android.support:appcompat-v7:26.0.0-alpha1] AndroidManifest.xml:27:9-38 value=(26.0.0-alpha1).
	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:25:5-27:34 to override.

**Comment by cgspine** [comment]
见#5
