### ISSUE TITLE
请问TopBar高度如何设置？

### ISSUE THREAD

**Issue by Marvin-mxl** [QMUI/QMUI_Android#300]

**Comment by cgspine** [comment]
theme 里面覆盖 `<item name="qmui_topbar_height">56dp</item>`

**Comment by AlvinQiang** [comment]
目前使用的1.1.3版本，theme 里面覆盖 <item name="qmui_topbar_height">56dp</item>失效了，发现父级里边没有qmui_topbar_height属性

**Comment by AlvinQiang** [comment]
目前使用的1.1.3版本，theme 里面覆盖 <item name="qmui_topbar_height">48dp</item>失效了，发现父级里边没有qmui_topbar_height属性

**Comment by cgspine** [comment]
qmui_topbar_height 一直存在啊
