### ISSUE TITLE
状态栏

### ISSUE THREAD

**Issue by Theoneee** [QMUI/QMUI_Android#301]
### 运行环境 ###

- [x] 设备型号：如：

M15
- [x] 设备系统版本：如 `Android 7.1.1
- [x] Gradle 版本：如 `3.1.2`
- [x] QMUI Android 版本：`1.1.3`

### 具体问题描述 ###

状态栏不知道怎么回事就变成了灰色的了。。不知道改了什么导致的。刚开始的时候和TopBar颜色一样的。

**Comment by theoneee** [comment]
图片上传不了。。。

**Comment by cgspine** [comment]
目前有找到问题的原因吗？
