### ISSUE TITLE
【反馈】TabSegment在人为的调用selectTab方法下，indicator并不会跟着移动到正确位置。

### ISSUE THREAD

**Issue by DamniVic** [QMUI/QMUI_Android#308]
### 运行环境 ###

- [x] 设备系统版本：'Android 4.4'
- [x] Gradle 版本：'4.1'
- [x] Gradle tools版本：'3.0.0'
- [x] QMUI Android 版本：'1.1.0'

### 具体问题描述 ###
  TabSegment在人为的调用selectTab方法下，indicator并不会跟着移动到正确位置。

**Comment by cgspine** [comment]
bug fixed in version 1.1.5
