### ISSUE TITLE
to check APIs compiled with API25

### ISSUE THREAD

**Issue by tenSunFree** [QMUI/QMUI_Android#31]
### 运行环境 ###
Android Studio的軟體設定
![03](https://user-images.githubusercontent.com/23090085/30158000-5d43f000-93f6-11e7-8bcc-8cd87e43f332.jpg)

Module build.gradle
![01](https://user-images.githubusercontent.com/23090085/30158048-89807d5a-93f6-11e7-851c-efd22d19fa92.jpg)

Project build.gradle
![02](https://user-images.githubusercontent.com/23090085/30158111-b8103b7e-93f6-11e7-93e4-80af2cfb03fe.jpg)

### 具体问题描述 ###
![2017-09-07_163101](https://user-images.githubusercontent.com/23090085/30158147-d797af90-93f6-11e7-8fa2-a37727401aa2.jpg)

請教一下, 以上2個問題發生的原因是什麼? 我應該如何去解決它們?

**Comment by cgspine** [comment]
![image](https://user-images.githubusercontent.com/7828876/30160676-153f3ab2-9400-11e7-893d-193ad64cbf84.png)
你应该需要升级SDK platform-tools

**Comment by tenSunFree** [comment]
升级SDK platform-tools, 確實可以解決問題1, 謝謝

另外想問一下, 你使用的製圖軟體是哪一款? 覺得效果很好看

**Comment by cgspine** [comment]
我是mac机，用的是 snip 截图
