### ISSUE TITLE
Android Studio编译项目失败

### ISSUE THREAD

**Issue by disenr** [QMUI/QMUI_Android#310]
### 运行环境 ###

android studio 3.0
gradle 4.4

#### 问题截图 ####
![image](https://user-images.githubusercontent.com/10415354/41267776-6f27e81c-6e2f-11e8-90e3-6b887ea31c27.png)

**Comment by adustdu2015** [comment]
![image.png](https://upload-images.jianshu.io/upload_images/5718533-6af70b43b72826e2.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

1.出现这个问题，可以在项目的根路径下的build.gradle 的 allprojects修改内容

``` gradle
allprojects {
    repositories {
        maven{url"https://maven.google.com"}
        mavenCentral()
        jcenter()
        google()
        maven{url 'https://jitpack.io'}
    }
}
```
注意maven的顺序问题;
