### ISSUE TITLE
QMUIDialog的Message不能自定义

### ISSUE THREAD

**Issue by xiaoli-style** [QMUI/QMUI_Android#311]
### 运行环境 ###

- [x] 设备型号：MI5
- [x] 设备系统版本：Android 7.0
- [x] Gradle 版本：3.1.2
- [x] QMUI Android 版本：1.1.3

### 具体问题描述 ###
QMUIDialog的setMessage能传入view吗？因为消息文本我想自定义一些东西，比如解析HTML文本之类的？

```
QMUIDialog.MessageDialogBuilder dialog = new QMUIDialog.MessageDialogBuilder(context);
                        dialog.setTitle("提示");
                        dialog.setMessage("内容");
                        dialog.addAction("确定", new QMUIDialogAction.ActionListener() {
                            @Override
                            public void onClick(QMUIDialog dialog, int index) {
                                dialog.dismiss();
                            }
                        });
                        dialog.show()
```

**Comment by cgspine** [comment]
如果你需要这种自定义，可以构造一个继承于 QMUIDialogBuilder  的 Builder, 重写 onCreateContent 就行

**Comment by xiaoli-style** [comment]
@cgspine 如果要设置消息文本的字体颜色大小等信息，也必须要构造一个继承于 QMUIDialogBuilder 的 Builder吗

**Comment by cgspine** [comment]
不用啊，你可以在 theme 中重写 qmui_dialog_message_content_style 改全局，或者 create 时传入一个新的 theme。 可以参考 Demo 的 QDDialogFragment， 右上角提供了更改 theme 的实现

**Comment by cgspine** [comment]
你还可以传入一个 SpannableString
