### ISSUE TITLE
无法给TopLayout 设置图片背景 

### ISSUE THREAD

**Issue by hezhihu89** [QMUI/QMUI_Android#32]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

#### 异常日志（堆栈） ####
TopBarLayout 无法设置图片背景

**Comment by chanthuang** [comment]
因为 TopBarLayout 内部实现背景颜色和分割线时使用了 background 属性，所以目前只能支持背景纯色（在 xml 中使用 qmui_topbar_bg_color 属性）和分割线（在 xml 中使用 qmui_topbar_separator_color 属性）。

**Comment by hezhihu89** [comment]
我进行了修改  将qmui_topbar_bg_color 设置透明 然后给ToolbarLayout  添加了一张图片背景

**Comment by hezhihu89** [comment]
现在发现一个新的问题 
当键盘顶上去的时候 toolbar 里面的文字也被顶上去 了 toolbar 中的内容区域就没了

**Comment by chanthuang** [comment]
能否贴一下你的布局 xml 文件？

**Comment by hezhihu89** [comment]
<?xml version="1.0" encoding="utf-8"?>
<com.qmuiteam.qmui.widget.QMUIWindowInsetLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:background="@color/qmui_config_color_white"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="com.isuno2.live.activity.MainActivity">

    <LinearLayout
        android:orientation="vertical"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <com.isuno2.live.widget.MToolbar
            android:fitsSystemWindows="true"
            app:qmui_topbar_bg_color="@color/qmui_s_transparent"
            android:id="@+id/main_top_bar_contain"
            android:layout_width="match_parent"
            android:layout_height="@dimen/toolBar_hight">


        </com.isuno2.live.widget.MToolbar>

        <com.qmuiteam.qmui.widget.QMUITabSegment
            android:paddingTop="4dp"
            android:textSize="12sp"
            app:qmui_tab_icon_position="top"
            android:layout_alignParentBottom="true"
            android:id="@+id/main_Naviga"
            android:layout_width="match_parent"
            android:layout_height="@dimen/indicarot_hight">

        </com.qmuiteam.qmui.widget.QMUITabSegment>

        <android.support.v4.view.ViewPager
            android:id="@+id/main_page"
            android:layout_below="@+id/main_top_bar_contain"
            android:layout_above="@+id/main_Naviga"
            android:layout_width="match_parent"
            android:layout_height="match_parent">

        </android.support.v4.view.ViewPager>



    </LinearLayout>
</com.qmuiteam.qmui.widget.QMUIWindowInsetLayout>

MToolbar 为我为了加背景图片继承的一个公共类
public class MToolbar extends QMUITopBarLayout{

    public MToolbar(Context context) {
        super(context);
    }

    public MToolbar(Context context, AttributeSet attrs) {
        super(context, attrs);
        setBackground(new ColorDrawable(Color.RED));//可以是资源图片
    }
}

**Comment by chanthuang** [comment]
## 解决方法 
将 `MToolbar` 移到 `LinearLayout` 的外面能解决问题。如下：
```
<com.qmuiteam.qmui.widget.QMUIWindowInsetLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent" >

    <com.isuno2.live.widget.MToolbar
        android:fitsSystemWindows="true"
        app:qmui_topbar_bg_color="@color/qmui_s_transparent"
        android:id="@+id/main_top_bar_contain"
        android:layout_width="match_parent"
        android:layout_height="@dimen/toolBar_hight">

    <LinearLayout
        android:orientation="vertical"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <!-- TagSegment 和 ViewPager -->

    </LinearLayout>
</com.qmuiteam.qmui.widget.QMUIWindowInsetLayout>
```

## 原因 ##
键盘升起时，系统会对 View 树做 windowInset 的派发，由于键盘导致的 insetBottom 会将 `fitsSystemWindows=true` 的 View 的内容顶上去导致看不到。

而 `QMUIWindowInsetLayout` 为了解决这个问题，会接管派发过程，对于 `fitsSystemWindows=true` 的子 View 会将键盘升起引起的 insetBottom 置为0，以保证子 View 的内容不会被顶走。

但因为你的 layout 文件中，`MToolbar` 不是 `QMUIWindowInsetLayout` 的直接子 View，所以 `QMUIWindowInsetLayout` 无法解决这个问题。

所以建议将 `MToolbar` 作为 `QMUIWindowInsetLayout` 的直接子 View。

**Comment by hezhihu89** [comment]
有一个问题   QMUIWindowInsetLayout 是 继承自 framLayout
这样似乎是不行的

**Comment by hezhihu89** [comment]
使用margin吗

**Comment by cgspine** [comment]
对，给 LinearLayout 设置 marginTop。

**Comment by hezhihu89** [comment]
有更好的方案吗  感觉挺当疼挺奇怪的

**Comment by hezhihu89** [comment]
有一点 QMUITopBar 和QMUITopBarLayout 有什么区别呢
我看你们是使用QMUIToolbar 但是也是配合  QMUIWindowInsetLayout 使用
但是 文档里面描述的又是  QMUITopBarLayout 和 QMUIWindowInsetLayout 配合使用才有沉浸式状态栏

**Comment by cgspine** [comment]
fitSystemWindow 本来就挺蛋疼的，另一个方案是你参考 QMUIWindowInsetLayout，在 MToolbar 中覆写 fitSystemWindows 和 使用 setOnApplyWindowInsetsListener 来做自定义处理。

**Comment by hezhihu89** [comment]
方便加qq 什么的联系不
发现巨混乱的问题 好痛苦
qq  2854918124
