### ISSUE TITLE
代码编码错误

### ISSUE THREAD

**Issue by kigkrazy** [QMUI/QMUI_Android#320]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

#### 问题截图 ####
![image](https://user-images.githubusercontent.com/11622206/41653673-663d3f96-74b9-11e8-9bb5-2dc428405095.png)

**Comment by cgspine** [comment]
试试这个：[解决android studio Gradle: 警告:编码 GBK 的不可映射字符的真正方法](http://chaofan.io/archives/%E8%A7%A3%E5%86%B3android-studio-gradle-%E8%AD%A6%E5%91%8A%E7%BC%96%E7%A0%81-gbk-%E7%9A%84%E4%B8%8D%E5%8F%AF%E6%98%A0%E5%B0%84%E5%AD%97%E7%AC%A6%E7%9A%84%E7%9C%9F%E6%AD%A3%E6%96%B9%E6%B3%95)

**Comment by kigkrazy** [comment]
这个我知道解决，就是跟你们反馈下。。。
