### ISSUE TITLE
有考虑加上类似微信的左右上角菜单显示吗？或者例子在哪个类我自己看下

### ISSUE THREAD

**Issue by kigkrazy** [QMUI/QMUI_Android#322]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

#### 问题截图 ####
![image](https://user-images.githubusercontent.com/11622206/41696455-cdb5ed66-7546-11e8-8d42-9f6e9439c5f9.png)

**Comment by theoneee** [comment]
QMUIPopup

**Comment by kigkrazy** [comment]
好的谢谢，顺边问下那个小尖角有接口可以去掉吗？

**Comment by theoneee** [comment]
可以的

**Comment by kigkrazy** [comment]
请问是哪个接口呢··
