### ISSUE TITLE
PullRefreshLayout 可以增加点样式吗。

### ISSUE THREAD

**Issue by Theoneee** [QMUI/QMUI_Android#324]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

**Comment by cgspine** [comment]
每个 App 需求都不一致吧， 重写 createRefreshView() 进行自定义就好
