### ISSUE TITLE
CheckBoxMessageDialogBuilder 报错

### ISSUE THREAD

**Issue by chengh2016** [QMUI/QMUI_Android#325]
### 运行环境 ###

- [x] 设备型号：如：`红米note4X`
- [x] 设备系统版本：如 `Android 7.0`
- [x] Gradle 版本：如 `4.1`
- [x] QMUI Android 版本：`1.1.3`

### 具体问题描述 ###
您好，我在使用 CheckBoxMessageDialogBuilder的时候程序挂掉，报错如下

#### 异常日志（堆栈） ####
android.view.InflateException: Binary XML file line #17: Binary XML file line #17: Error inflating class com.qmuiteam.qmui.widget.dialog.QMUIDialogView
 Caused by: android.view.InflateException: Binary XML file line #17: Error inflating class com.qmuiteam.qmui.widget.dialog.QMUIDialogView

**Comment by cgspine** [comment]
没有使用 QMUI 提供的 theme ?

**Comment by chengh2016** [comment]
我明白了，对不住，我的项目里有多个theme
