### ISSUE TITLE
不清楚R.id.topbar_right_change_button在代码中的具体用途是？

### ISSUE THREAD

**Issue by pokon548** [QMUI/QMUI_Android#326]
### 运行环境 ###

- [x] 设备型号：如：`红米 1S`
- [x] 设备系统版本：如 `Android 6.0.1`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.3.0`

### 具体问题描述 ###
您好。我在使用该库中QMUITopBar的addRightImageButton方法时对第二个参数viewID存疑，不清楚其具体含义是什么
按照demo中的方法，我直接在idx.xml中加入了ID后，直接在代码中引用该ID作为第二个参数无效，界面右上角还是没有图像按钮

**Comment by cgspine** [comment]
控件内部 layout 会用到，如果你需要加入一些自定义view， 例如显示红点，就可以发挥错用了。其次就是自动化测试
