### ISSUE TITLE
添加topBar的话，界面的主体在预览的时候就会变成黑色的，去掉的话又能变成白色了

### ISSUE THREAD

**Issue by WinWang** [QMUI/QMUI_Android#333]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

### 具体问题描述 ###
![2345 20180628103337](https://user-images.githubusercontent.com/19348069/42009894-dc492c62-7abe-11e8-8d96-4ecfe4d75d3a.png)

**Comment by ahao123ok** [comment]
代码中手动设置一下 topbar的背景透明就行

**Comment by cgspine** [comment]
qmui 用了 theme 做了大量配置，导致 xml 在预览中的效果并不准确，暂时还没找到解决方案
