### ISSUE TITLE
Fragment退出没有隐藏输入法

### ISSUE THREAD

**Issue by javakam** [QMUI/QMUI_Android#334]
[QUMIFragment](https://github.com/QMUI/QMUI_Android/blob/master/arch/src/main/java/com/qmuiteam/qmui/arch/QMUIFragment.java)

`  
swipeBackLayout.addSwipeListener(new SwipeBackLayout.SwipeListener() {
            private QMUIFragment mModifiedFragment = null;
            @Override
            public void onScrollStateChange(int state, float scrollPercent) {
//TODO 隐藏输入法
                Log.i(TAG, "SwipeListener:onScrollStateChange: state = " + state + " ;scrollPercent = " + scrollPercent);
                ViewGroup container = getBaseFragmentActivity().getFragmentContainer();
                int childCount = container.getChildCount();
...
`

**Comment by cgspine** [comment]
update to 1.1.7
