### ISSUE TITLE
沉浸式TopBar样式与Demo不符

### ISSUE THREAD

**Issue by XinwenCheng** [QMUI/QMUI_Android#336]
### 运行环境 ###

- [x] 设备型号：如：三星S8、红米3S
- [x] 设备系统版本：Android 8.0.0、6.0.1
- [x] Gradle 版本：4.4
- [x] QMUI Android 版本：`1.1.5`

### 具体问题描述 ###
采用QMUITopBar和QMUIStatusBarHelper.translucent()，沉浸式状态栏距离屏幕顶部少了通知栏的高度，见下图。试过各种方式都无法做到想Demo中的沉浸式状态栏那样的高度，其实就是沉浸式状态来的上边缘不是与通知栏下边缘相接，而是直接顶到屏幕最顶端去了。检查了好几遍demo的代码，也没有发现任何不同地方。请各位帮忙看看是什么问题，谢谢！

代码如下：

> Layout
```xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/app_color_background"
    android:orientation="vertical">

    <com.qmuiteam.qmui.widget.QMUITopBar
        android:id="@+id/tbTopSignIn"
        android:layout_width="match_parent"
        android:layout_height="?attr/qmui_topbar_height"/>
</LinearLayout>
```

> Activity onCreate()
```java
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        QMUIStatusBarHelper.translucent(this, Color.TRANSPARENT);
        setContentView(R.layout.activity_sign_in);
    }
```

#### 问题截图 ####
![wx20180706-185120](https://user-images.githubusercontent.com/795334/42375478-418473e4-814e-11e8-81e2-71f5787ac130.png)

**Comment by cgspine** [comment]
沉浸式场景推荐用 QMUITopBarLayout, 参考 QDAboutFragment

**Comment by XinwenCheng** [comment]
@cgspine 感谢！已解决问题。
