### ISSUE TITLE
白底黑字疑问

### ISSUE THREAD

**Issue by weinierfei** [QMUI/QMUI_Android#34]
### 具体问题描述 ###
单独使用QMUIStatusBarHelper实现状态栏白底黑字,发现颜色不太一致,是不是缺了啥?
#### 问题截图 ####
![image](https://user-images.githubusercontent.com/11873816/30199199-3a26503c-94a4-11e7-965c-96246b930c7c.png)

**Comment by cgspine** [comment]
"不一样"的比较对象是？字体和图标的颜色是由系统决定的

**Comment by weinierfei** [comment]
感谢回复  我指的是状态栏的颜色色值,设置了沉浸式和黑字模块;通过改变colorPrimaryDark值,状态栏的颜色一直都是我截图上不变

**Comment by cgspine** [comment]
设置沉浸式后，布局时延伸到状态栏下面，所以状态栏背景颜色是有布局的背景色决定的，colorPrimaryDark 已经无法生效了。
图中背景为灰色，应该是你 Activity（Fragment）最外层 View 的背景色。

**Comment by weinierfei** [comment]
我引入你们的库,将项目的theme继承 QMUI.Compat;然后啥也不该,就不会出现图片中的问题;所以不太明白,是不是主题里有什么设置

**Comment by cgspine** [comment]
这个是 QMUIStatusBarHelper.translucent 带来的影响，它会使得布局延伸到状态栏下面。

**Comment by weinierfei** [comment]
是的,这个我明白的;我的疑问是:同样适用QMUIStatusBarHelper类,继承你们的主题QMUI.Compat,就不会出现图片中状态栏和布局颜色不一样的问题;继承Theme.AppCompat.Light.DarkActionBar就会有图片中的问题?

**Comment by cgspine** [comment]
请问你只是使用了QMUIStatusBarHelper.setStatusBarLightMode()吗？还有，使用 colorPrimaryDark 时，是使用 `<item name="colorPrimaryDark">#ffffff</item>` 还是 `<item name="android:colorPrimaryDark">#ffffff</item>`?

**Comment by weinierfei** [comment]
QMUIStatusBarHelper.translucent()  然后调用了setStatusBarLightMode(); colorPrimaryDark 配置如图:
![image](https://user-images.githubusercontent.com/11873816/30262622-311b5cd2-9704-11e7-8282-3b099bf2d7a4.png)

**Comment by cgspine** [comment]
如果调用了QMUIStatusBarHelper.translucent()， 那状态栏的背景完全由layout的背景决定了啊，我测试时两个主题的表现是一致的，可以贴下你的xml布局吗？

**Comment by weinierfei** [comment]
不好意思,回复晚了;会不会是因为我使用了ActionBar的原因?我把复现的代码放到了github:(https://github.com/weinierfei/TinkerDemo) ,里头的MainActivity就是,劳烦帮忙看一下,谢啦

**Comment by cgspine** [comment]
确实是 ActionBar所引起的，可以从getSupportActionBar() 进行追踪到 WindowDecorActionBar:
![image](https://user-images.githubusercontent.com/7828876/30698117-9093531a-9f13-11e7-8865-9f4cd4568ebd.png)
![image](https://user-images.githubusercontent.com/7828876/30698165-b22aaa50-9f13-11e7-973e-86a35db14997.png)

再结合uiautomatorviewer工具查看视图结构，可以看到 decor_content_parent 会消耗掉 WindowInsets，所以状态栏下面的背景实际上是 decor_content_parent 的背景，也就是 Activity 的背景。内容依旧是从状态栏下开始布局的。如果在 theme 添加 background 属性，就更明显了：
![image](https://user-images.githubusercontent.com/7828876/30698467-a94b8390-9f14-11e7-88c5-8407c6e1c9e7.png)

你之前用 QMUI.Compat 没有问题，只是恰恰好其 background 为白色而你的内容也是白色而已。

**Comment by weinierfei** [comment]
确实如此;当时使用ActionBar是因为不想在每个布局中添加一个toolbar,所以使用了ActionBar在baseactivity中统一处理了;有没有不在AppTheme中添加android:background的办法处理下这个问题,因为如果添加的的话,所有的dialog之类的会有问题

**Comment by cgspine** [comment]
可以不使用QMUIStatusBarHelper.translucent， 直接用 window.setStatusBarColor去控制状态栏的背景色。小米、魅族、Android 6+设置成白色，android 5.x设置成灰色或者彩色（android 5.x 以及 Android 6 的 ZUK1/ZTKC2016 不支持改状态栏icon和字体的颜色，所以背景不能为白色）

**Comment by weinierfei** [comment]
非常感谢

**Comment by weinierfei** [comment]
好像不行啊,window.setStatusBarColor只有在21的时候才行啊,其他的不能设置啊

**Comment by cgspine** [comment]
setStatusBarColor支持21及其以上吧

**Comment by weinierfei** [comment]
不调用translucent,小米4上状态栏竟然是黑色的,看来还得调用;

**Comment by cgspine** [comment]
你可以在 API21 以上调用 setStatusBarLightMode 。 否则的话，估计只能放弃ActionBar，在BaseActivity上封装 ToolBar 或者 QMUITopBar了

**Comment by weinierfei** [comment]
好的,我在研究研究;非常感谢您耐心解答!
