### ISSUE TITLE
DialogFragment使用沉浸式，怎么设置字体模式是深色

### ISSUE THREAD

**Issue by wjianchen13** [QMUI/QMUI_Android#342]
在项目中使用了DialogFragment，然后状态栏字体设置了深色，状态栏设置成透明，每次打开dialogfragment时，状态栏都会变成黑色，字体变成白色，怎样让它保持状态栏是透明，字体还是报纸深色？

**Comment by cgspine** [comment]
在 DialogFragment 中调用 QMUIStatusBarHelper.translucent(dialog.getWindow()) 。 qmui 1.1.6 版本的 translucent 才支持传 window
