### ISSUE TITLE
QMUIDialog.EditTextDialogBuilder 中 EditText 下划线颜色不是 colorAccent

### ISSUE THREAD

**Issue by MAIMIHO** [QMUI/QMUI_Android#343]
### 运行环境 ###

- [x] 设备型号：如：`非特定型号`
- [x] 设备系统版本：如 `非特定版本`
- [x] Gradle 版本：如 `非特定版本`
- [x] QMUI Android 版本：`1.1.5`

### 具体问题描述 ###
QMUIDialog.EditTextDialogBuilder 中 EditText 下划线颜色不是 colorAccent, 找了各种theme配置没发现. 
最后在{@link EditTextDialogBuilder#onCreateContent(QMUIDialog, ViewGroup, Context)}代码里面看到如下代码. 

```
mMainLayout.setBackgroundResource(R.drawable.qmui_edittext_bg_border_bottom);
......
mEditText.setBackgroundResource(0);
```
请教一下大佬, 这个地方为什么不做成可配置的呢? 
或者怎么把Dialog里面的EditText下划线变成colorAccent

谢谢!

#### 问题截图 ####
![image](https://user-images.githubusercontent.com/18633356/43060032-c77d3608-8e81-11e8-8d95-21fe4d82dff6.png)

![image](https://user-images.githubusercontent.com/18633356/43060124-1508007e-8e82-11e8-841a-b8357f7327fd.png)

**Comment by cgspine** [comment]
目前可以直接提供一个 qmui_edittext_bg_border_bottom 的 drawable 来覆盖。后期会改成配置项

**Comment by MAIMIHO** [comment]
谢谢大佬
