### ISSUE TITLE
PullRefreshLayout 

### ISSUE THREAD

**Issue by Theoneee** [QMUI/QMUI_Android#345]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 7.1.1`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.0.5`

### 具体问题描述 ###

  <style name="AppTheme" parent="QMUI.Compat.NoActionBar">
       
 <item name="qmui_config_color_blue">@color/white</item>
   
 </style>

然后 刷新图标就变成了白色的了。。刷新的图标没有单独的设置颜色的地方吗。

**Comment by theoneee** [comment]
升级到1.1.5了。然后状态栏变成了灰色。。

**Comment by theoneee** [comment]
1.0.6  <item name="qmui_config_color_blue">@color/colorAccent</item>  状态栏跟这个颜色一样。1.1.0之后就直接变成了灰色的了。状态栏字体是白色的。。

**Comment by theoneee** [comment]
qmui_config_color_blue

**Comment by cgspine** [comment]
`<item name="colorAccent"></item>`  有去掉 android 前缀吗？

**Comment by theoneee** [comment]
` <style name="AppTheme" parent="QMUI.Compat.NoActionBar">
        
        <item name="qmui_config_color_blue">@color/colorAccent</item>
    </style>

 <color name="colorAccent">#ff5c5c</color>`

这样子的。

**Comment by theoneee** [comment]
。。。为什么发布完整。。

**Comment by theoneee** [comment]
![1](https://user-images.githubusercontent.com/32156330/43109952-f540db22-8f1b-11e8-82f0-16acc225c3f0.png)
![2](https://user-images.githubusercontent.com/32156330/43109957-fa88fa92-8f1b-11e8-97ca-82107eecaf47.jpg)

**Comment by theoneee** [comment]
![3](https://user-images.githubusercontent.com/32156330/43109981-19d4a2de-8f1c-11e8-8ac0-9672c8b8d174.png)

**Comment by theoneee** [comment]
qmui_config_color_blue  改成什么颜色，下拉刷新那个就是什么颜色。状态栏不知道怎么的一直都是灰色。但是我想要的是状态栏是白色，黑色的图标。然后下拉刷新是我自己定义的颜色。。。大佬看看能怎么解决吗。感谢·~

**Comment by cgspine** [comment]
使用沉浸式方案： QMUIStatusBarHelper.translucent() 配合  QMUIStatusBarHelper.setStatusBarLightMode() ?

如果不用沉浸式， window.setStatusBarColor() 也可以改状态栏背景色
