### ISSUE TITLE
Dialog

### ISSUE THREAD

**Issue by shaohui93** [QMUI/QMUI_Android#346]
您好，请问一下会不会增加ios风格的Dialog啊？特别是消息类型的对话框，总是会被要求根ios统一。

**Comment by cgspine** [comment]
你可以在主题里配置啊，在 demo 里 QDDialogFragment 右上角提供了一个切换 theme 的选项，其自定义样式就比较接近 ios 的效果。你可以参考一下

**Comment by shaohui93** [comment]
ok,感谢
