### ISSUE TITLE
QMUITopBar的setCenterView无效？

### ISSUE THREAD

**Issue by hujiaweibujidao** [QMUI/QMUI_Android#35]
### 运行环境 ###

- [x] 设备型号：`Google Pixel`
- [x] 设备系统版本：`Android 7.1`
- [x] Gradle 版本：`2.3.1`
- [x] QMUI Android 版本：`1.0.2`

### 具体问题描述 ###

看了下QMUITopBar的源码，默认CenterView是一个TextView，并且支持setCenterView来设置自定义的View，但是我试了下如果将CenterView设置为一个button可以，但是设置为TextView却没有生效，Topbar中间部分没有显示任何东西。不知为何，能帮忙看下吗？

#### 代码片段 ####

下面是一段测试代码，测试将CenterView设置为一个TextView，但是没能生效

```java
TextView textView = new TextView(this);
textView.setGravity(Gravity.CENTER);
textView.setText("测试");
mTopBar.setCenterView(textView);
```

**Comment by chanthuang** [comment]
这是正确的使用方式。方便的话麻烦贴一下你的 topbar 所在的布局 xml 文件，方便定位问题。谢谢。

**Comment by hujiaweibujidao** [comment]
没事了，上面问题是因为没有设置TextSize导致的
