### ISSUE TITLE
QMUIDialog.CustomDialogBuilder 有个地方有点矛盾

### ISSUE THREAD

**Issue by MAIMIHO** [QMUI/QMUI_Android#350]
### 运行环境 ###

- [x] 设备型号：非特定型号
- [x] 设备系统版本：非特定版本
- [x] Gradle 版本：非特定版本
- [x] QMUI Android 版本：`1.1.5`

### 具体问题描述 ###
大佬你好: 
当Dialog ActionListener里面需要获取自定义Layout中控件的值的时候有些矛盾的地方. 
builder.setLayout(layoutResId)后需要create()后才能通过dialog.findViewById()拿到控件.
这个时候用builder.addAction()实际上不会添加这个Action

```
QMUIDialog.CustomDialogBuilder builder = new QMUIDialog.CustomDialogBuilder(getContext());
        QMUIDialog dialog = builder.setLayout(R.layout.dialog_xxx)
                .create();
        EditText editText = dialog.findViewById(R.id.editText);

        //这个Action实际上没有添加
        builder.addAction("确定", new ActionListener() {
            @Override
            public void onClick(QMUIDialog d, int index) {
                String name = editText.getText().toString();
            }
        });
        dialog.setOnShowListener(dialog1 -> {
            //doAction
        });
        dialog.show();
```
builder.addAction()后再create() ActionListener 里面又拿不到控件

```
QMUIDialog.CustomDialogBuilder builder = new QMUIDialog.CustomDialogBuilder(getContext());
        QMUIDialog dialog = builder.setLayout(R.layout.dialog_xxx)
                .addAction("确定", new ActionListener() {
                    @Override
                    public void onClick(QMUIDialog d, int index) {
                        //这样无法拿到EditText
                        String name = editText.getText().toString();
                    }
                })
                .create();
        EditText editText = dialog.findViewById(R.id.editText);

        dialog.setOnShowListener(dialog1 -> {
            //doAction
        });
        dialog.show();
```

请问是我哪里理解有误吗? 

谢谢!

**Comment by MAIMIHO** [comment]
我现在在onClick(QMUIDialog dialog, int index)中 用ActionListener的第一个参数QMUIDialog, 再次 findViewById()拿到控件, 这样能拿到, 但是有点别扭

**Comment by chanthuang** [comment]
大佬好：
Builder 的存在是为了方便对 dialog 做各种参数定制，例如：
```
builder.setTitle();
builder.addAction()
```

以及各种更底层的 Builder 带来的更详细的定制，例如
```
MessageDialogBuilder#setMessage()
EditTextDialogBuilder#setDefaultText()
```

然后再创建 Dialog：
```
builder.create()
```

通过 Builder 添加的内容只记录在 Builder 中，用来创建 Dialog。一旦 Dialog 创建，一般就不会再改变，也就脱离了 Builder 的控制，参照设计模式中的 Builder 模式。所以你在 `builder.create()` 之后继续 `builder.addAction()` 是不会影响 Dialog 的。

如果你需要对 Dialog 做复杂的控制，可以继承 `QMUIDialog.CustomDialogBuilder` 实现自己的子类，重写 `onCreateContent` 方法，在里面往 `parent` 添加自定义的子 View。这样，自定义的子 View 就完全受你控制，并在 Dialog 被 create 之前就可以获取到想要的 View。

**Comment by MAIMIHO** [comment]
谢谢
