### ISSUE TITLE
在使用 QMUITabSegment 与 ViewPager 中 tab 切换 最后一个 tab 沉浸式状态栏 padding 消失 

### ISSUE THREAD

**Issue by tielan** [QMUI/QMUI_Android#352]
### 运行环境 ###

- [x] 设备型号：如：`mi6`
- [x] 设备系统版本：如 `Android 7.0`
- [x] Gradle 版本：如 `4.4`
- [x] QMUI Android 版本：`1.1.5`

### 具体问题描述 ###
在使用 QMUITabSegment 与 ViewPager 中 tab 切换 最后一个 tab 沉浸式状态栏 padding 消失 
#### 问题截图 ####

![image](https://user-images.githubusercontent.com/5001253/43500138-a898b904-9581-11e8-813b-012b94522c5a.png)
![image](https://user-images.githubusercontent.com/5001253/43500139-b013b6d4-9581-11e8-91b4-5ad61c27da16.png)

#### Layout Inspector 文件
[com.qmuiteam.qmuidemo_2018.08.01_11.55.zip](https://github.com/QMUI/QMUI_Android/files/2247972/com.qmuiteam.qmuidemo_2018.08.01_11.55.zip)

目前的解决办法：
![image](https://user-images.githubusercontent.com/5001253/43500280-4f9b9622-9582-11e8-861d-1bf2b55025b7.png)

**Comment by cgspine** [comment]
update to 1.1.7
