### ISSUE TITLE
CreateProcess error=2, 系统找不到指定的文件。

### ISSUE THREAD

**Issue by chenxiaofei910714** [QMUI/QMUI_Android#357]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`3.1.3`

#### 问题截图 ####
编译不通过

**Comment by cgspine** [comment]
参考这个[issue](https://github.com/nickbutcher/plaid/issues/17), 是否是你的 git 不在 path 路径下？
