### ISSUE TITLE
你们怎么知道怎么用的？哪里有文档

### ISSUE THREAD

**Issue by LZKDreamer** [QMUI/QMUI_Android#358]
哪里有文档啊？不知道怎么用。

**Comment by ctyyy** [comment]
同问啊，没找到详细文档，只有每个组件类的描述

**Comment by MoLice** [comment]
例如哪些控件的哪些信息你觉得需要说明，但目前没有的？

**Comment by chanthuang** [comment]
在 github 仓库 README 中有列出了组件的功能列表，以及引入 QMUI 的方法。具体组件类的使用方法，建议下载代码运行起来，对照代码和运行的效果来看组件如何使用。

**Comment by LZKDreamer** [comment]
在项目里有一个qmuidemo，建议下载一个QMUI APP，对照APP的效果在qmuidemo中找相应的代码。
