### ISSUE TITLE
QMUIEmptyView setButton后，只在LinearLayout中可以点击

### ISSUE THREAD

**Issue by XinwenCheng** [QMUI/QMUI_Android#359]
### 运行环境 ###

- [x] 设备型号：三星S8
- [x] 设备系统版本：Android 8.0.0
- [x] Gradle 版本：3.1.3
- [x] QMUI Android 版本：1.1.5

### 具体问题描述 ###
QMUIEmptyView实例在通过setButton方法设置了文字和点击事件后，如果该实例在一个LinearLayout中，则点击事件能响应，如果将Container换成FrameLayout或RelativeLayout，则点击事件不响应。

#### 问题截图 ####
N/A
#### 异常日志（堆栈） ####
N/A

**Comment by cgspine** [comment]
是否是因为被遮挡了？ 可以 Tools -> Layout Inspector 查看下

**Comment by XinwenCheng** [comment]
@cgspine 奇怪了，我把代码恢复到之前的状态，现在又可以响应点击了，试了好几种方式，都正常，但是现在的代码状态和之前出错的时候一样，暂时无法确定当时是什么原因了。不好意思！
