### ISSUE TITLE
在CoordinatorLayout中怎么把图片沉浸式上去

### ISSUE THREAD

**Issue by tx123456** [QMUI/QMUI_Android#36]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

#### 问题截图 ####
这是我的布局，我对着demo写的，发现沉浸不了，是不是我什么地方写错了

<android.support.design.widget.CoordinatorLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto">

    <android.support.design.widget.AppBarLayout
        android:id="@+id/app_bar"
        android:layout_width="match_parent"
        android:layout_height="200dp"
        android:fitsSystemWindows="true">

    <com.qmuiteam.qmui.widget.QMUICollapsingTopBarLayout
        android:id="@+id/collapsing_topbar_layout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:layout_scrollFlags="scroll|exitUntilCollapsed"
        app:qmui_contentScrim="?attr/qmui_config_color_blue"
        app:qmui_statusBarScrim="?attr/qmui_config_color_blue"
        app:qmui_titleEnabled="false">

        <ImageView
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:scaleType="centerCrop"
            android:src="@mipmap/bg_my"
            app:qmui_layout_collapseMode="parallax"
            app:qmui_layout_collapseParallaxMultiplier="0.7"
            android:fitsSystemWindows="false"
            />

        <LinearLayout 。。。>
        <com.qmuiteam.qmui.widget.QMUITopBar
            android:id="@+id/qmui_topbar"
            android:layout_width="match_parent"
            android:layout_height="?attr/qmui_topbar_height"
            app:qmui_layout_collapseMode="pin"
            app:qmui_topbar_bg_color="@color/qmui_config_color_transparent"
            app:qmui_topbar_need_separator="false"
            android:fitsSystemWindows="true"/>

    </com.qmuiteam.qmui.widget.QMUICollapsingTopBarLayout>
    </android.support.design.widget.AppBarLayout>

    <android.support.v7.widget.RecyclerView
        android:id="@+id/recycle"
        app:layout_behavior="@string/appbar_scrolling_view_behavior"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>

</android.support.design.widget.CoordinatorLayout>

**Comment by cgspine** [comment]
请问你的 Activity 有调用 `QMUIStatusBarHelper.translucent(this);`吗？

**Comment by tx123456** [comment]
添加了，这是activity里面的设置
QMUIStatusBarHelper.setStatusBarLightMode(_mActivity);
QMUIStatusBarHelper.translucent(_mActivity);
 qmuiTopbar.setTitle("My");

**Comment by cgspine** [comment]
这个界面的是tab+viewpager的结构，我猜想是因为viewpager或者viewpager的父view设置了fitSytemWindows = true。

**Comment by cgspine** [comment]
如果想要在viewpager里实现你想要的效果，需要对viewpager的onApplyWindowInset做支持，目前 qmui 没有支持到，我会尽快适配这一类需求。

**Comment by tx123456** [comment]
额，我这个是radiobutton加fragment的，没有viewpager,这个界面可以当成一个普通的fragment

**Comment by cgspine** [comment]
那你存放fragment的那个view有没有设置 fitSytemWindows = true ？

**Comment by cgspine** [comment]
请更新至1.0.3，如果fragment+ radiobutton是由QMUIWindowInsetLayout包裹的话，应该能正常工作

**Comment by xiaoli-style** [comment]
@tx123456
