### ISSUE TITLE
请问有提供离线jar包的下载地址么？

### ISSUE THREAD

**Issue by cuihee** [QMUI/QMUI_Android#360]
### 具体问题描述 ###
我的AS报错Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.qmuiteam:qmui:1.1.3.
（项目中使用到的所有包我都是用的离线jar包（泪目））

（我知道应该解决我的环境问题，但是无能啊）

所以希望提供QMUI的离线jar包，供我这种笨笨使用

**Comment by cgspine** [comment]
https://jcenter.bintray.com/com/qmuiteam/qmui/1.1.3/
可以直接去 jcenter 或者其镜像网站下载 jar 包
