### ISSUE TITLE
QMUITopBar如果添加Drawable字体图标

### ISSUE THREAD

**Issue by ctyyy** [QMUI/QMUI_Android#362]
### 运行环境 ###

- [x] 设备型号：huawei
- [x] 设备系统版本：android7.0
- [x] Gradle 版本：2.3.3
- [x] QMUI Android 版本：1.1.5

### 具体问题描述 ###
QMUITopBar如何再左右添加Drawable对象，放iconify字体图标

#### 问题截图 ####
![20180809171932](https://user-images.githubusercontent.com/14940814/43890197-9d4b60b0-9bf8-11e8-8da5-2b3dc80b7d55.jpg)

**Comment by cgspine** [comment]
addRightImageButton 就是传参 drawbleResourse。 默认没有支持到字体图标， 你可以通过 addRightView 传入支持字体图标的自定义view
