### ISSUE TITLE
QMUTopBar 怎么设置标题栏 左右textbutton以及中间title的字体颜色

### ISSUE THREAD

**Issue by pantongren** [QMUI/QMUI_Android#363]
#QMUTopBar 怎么设置标题栏 左右textbutton以及中间title的字体颜色

**Comment by cgspine** [comment]
方案1： 在 theme 里设置，参考Demo `<item name="QMUITopBarStyle">@style/QDTopBar</item>` 。
方案2： setTitle 返回的是TextView, 左右 textButton 构造时有传入 id，可以通过 id 寻找到相应 view。
推荐方案1。
