### ISSUE TITLE
qmui.arch

### ISSUE THREAD

**Issue by mrerhuo** [QMUI/QMUI_Android#367]
### 运行环境 ###

- [x] 设备型号：如：开发`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.1.3`

### 具体问题描述 ###
qmui.arch这个项目在1.1.3里面没有，然后又没啥好的文档，请问如何解决我在1.1.3里面使用？

**Comment by mrerhuo** [comment]
我import module提示已存在项目。

**Comment by cgspine** [comment]
`implementation "com.qmuiteam:arch:0.1.2`
