### ISSUE TITLE
QMUICollapsingTopBarLayout需要监听Scrim的变化

### ISSUE THREAD

**Issue by niulinguo** [QMUI/QMUI_Android#37]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

### 具体问题描述 ###

QMUICollapsingTopBarLayout需要监听Scrim的变化

QMUITopBar的标题要求根据Scrim的变化进行显示和隐藏，
能不能将QMUICollapsingTopBarLayout的ValueAnimator暴露出来，或者可以设置动画监听，让应用可以监听到Scrim的变化

**Comment by cgspine** [comment]
请更新至1.0.3

**Comment by niulinguo** [comment]
谢谢
