### ISSUE TITLE
Demo1.1.6版本出现闪退

### ISSUE THREAD

**Issue by androidflying** [QMUI/QMUI_Android#371]
### 运行环境 ###

- [x] 设备型号：如：`小米6`
- [x] 设备系统版本：如 `Android 8.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.1.6`

### 具体问题描述 ###
QMUITabSegment中，点击“内容自适应，超过父容器则滚动”闪退。
QMUIQQFaceView中，点击“性能观测”闪退。

**Comment by cgspine** [comment]
谢谢反馈，现在代码已经 fix，近期会发布新版本

**Comment by androidflying** [comment]
ok，祝越做越好
