### ISSUE TITLE
一个严重的BUG，使用ARCH框架，一个Activity拖多个Fragments，在Fragment和Fragment频繁切换的时候会出现APP直接“卡死”

### ISSUE THREAD

**Issue by HuaZaiWuDi** [QMUI/QMUI_Android#373]
### 运行环境 ###

- [x] 设备型号：如：`小米Mix2，华为P10`
- [x] 设备系统版本：如 `Android 8.0.0`
- [x] Gradle 版本：如 `4.4.1`
- [x] QMUI Android 版本：`com.qmuiteam:arch:0.1.1`

### 具体问题描述 ###
一个严重的BUG，使用ARCH框架，一个Activity拖多个Fragments，在Fragment和Fragment频繁切换的时候会出现APP直接“卡死”，APP不触发点击触摸等事件了，界面卡死不动，控制不了，然后手机并无卡顿，正常返回，没有黑屏，经过多次测试，发现是在GC频繁回收内存时可能触发，每次出现上诉问题，都是在GC回收之后。

希望能够时效反馈下，现在已经集成到应用内了，项目将要上线，但是出现这个严重的BUG

#### 异常日志（堆栈） ####
没有错误日志返回，点击屏幕APP的触摸事件无响应，AS打印系统级的触摸事件。使用官方的示例项目也会出现这个问题

**Comment by cgspine** [comment]
升级至 0.1.3 ？

**Comment by HuaZaiWuDi** [comment]
但是还是感觉性能好像并没有很好，或者可能是我代码的问题。总觉得没有Activity的性能好啊

**Comment by cgspine** [comment]
relpace 也是压入栈的，替换是指替换掉界面上的 View，而 Add 是往界面加 View 而不移除旧的 View, 如果导航层级过深，界面就会堆积很多 View，绘制性能还会差很多。 hide 方式没有做过尝试

**Comment by cgspine** [comment]
目前改用 cache 住 onCreateView 返回的 View，这样可以一直 cache 住主要到 View， 也避开了转场动画的坑。
