### ISSUE TITLE
QMUICollapsingTopBarLayout 只能设置title的内容？

### ISSUE THREAD

**Issue by mrerhuo** [QMUI/QMUI_Android#374]
QMUICollapsingTopBarLayout 设置了标题了。然后代码里面设置字体颜色。我就没法设置字体大小，字体粗细？？？我把代码里面的字体颜色属性根据经验拿到XML里面去设置颜色，然而没用。

**Comment by cgspine** [comment]
可以通过 xml 设置 `qmui_expandedTitleTextAppearance` 和 `qmui_collapsedTitleTextAppearance`
或者 java 设置 `setExpandedTitleTextAppearance` 和 `setCollapsedTitleTextAppearance`。

接口确实少了快捷设置字体大小的接口， 设置字体粗细可以通过 `setCollapsedTitleTypeface` 去做。
