### ISSUE TITLE
arch:0.1.3,返回页面空白.

### ISSUE THREAD

**Issue by A-Heavy-Rain** [QMUI/QMUI_Android#379]
### 运行环境 ###

- [x] 设备型号：如：`mi5s`
- [x] 设备系统版本：如 `Android 7.0`
- [x] Gradle 版本：如 3.1.4`
- [x] arch：`:0.1.3`

### 具体问题描述 ###
不太清楚0.1.2到0.1.3做了什么变化,导致我的应用出了些问题.
#### 问题截图 ####
![screenshot_2018-09-03-11-17-55-471_com hooli hool](https://user-images.githubusercontent.com/20280717/44966072-97539980-af6b-11e8-8f26-058b8be552b0.png)
这是最开始的一个Fragment嵌套一个列表fragment和一个筛选的fragment,点击一个recyclerview的item会通过startfragment跳转到另一个页面,返回时列表fragment为空白页面,筛选的fragment的toolbar颜色也变了,见下图(在0.1.2没有这些问题,是不是mCacheView机制做了更改?).
![screenshot_2018-09-03-11-18-02-146_com hooli hool](https://user-images.githubusercontent.com/20280717/44966166-2e205600-af6c-11e8-9b8a-7926b97b2678.png)
![screenshot_2018-09-03-11-18-05-635_com hooli hool](https://user-images.githubusercontent.com/20280717/44966170-31b3dd00-af6c-11e8-88d9-bf1f335eb578.png)

**Comment by cgspine** [comment]
这个版本修改了 mCacheView机制， 现在更不容易被 mCacheView cache住了，主要原因是 1.1.2 的 cache 策略在快速返回时会造成整个界面假死。

你那边这个问题是必现吗？

**Comment by cgspine** [comment]
我这边发现一个可以复现的场景， mCacheView 没有 cache 到，然后重新进入 onCreateView() 生成 View。 每次 onCreateView 的 View 的 ViewPager 都复用了同一个 Adapter。

![image](https://user-images.githubusercontent.com/7828876/44979929-05668380-afa1-11e8-899d-172aad25cb7a.png)

我做了这样的操作就没有问题了，请问你是否可以用同样的思路 debug 下？

**Comment by A-Heavy-Rain** [comment]
找到原因了,应该是每次都没有cache到,因此每次返回都走了onCreateView(),而我在onCreateView()中会给recyclerview设置Adapter,这样每次返回都被初始化为空列表. 但是0.1.2版本不会发生这种每次都cache不到,0.1.3可以做下修改避免这种情况吗?

**Comment by cgspine** [comment]
我现在直接 cache 住 onCreateView() 的结果，而不仅仅 cache 住 SwipeBackLayout。这样可以避免转场动画过程中退化的问题。

**Comment by cgspine** [comment]
可以升级到 0.1.4

**Comment by A-Heavy-Rain** [comment]
感谢!问题已解决,我在看看源码理解下.
