### ISSUE TITLE
QMUITabSegment 显示小红点问题

### ISSUE THREAD

**Issue by imliujun** [QMUI/QMUI_Android#381]
正常显示小红点逻辑是在QMUITabSegment初始化完成后，请求接口数据判断是否显示小红点，
这时调用 showSignCountView 方法不会显示小红点，还需要调用notifyDataChanged方法将小红点控件添加到TabItemView中。
导致每次显示小红点都得去调用一下notifyDataChanged方法，这样是不是不太好

**Comment by cgspine** [comment]
`showSignCountView` 这个方法以及会为你调用 `notifyDataChanged` 啊。 view 是复用的，应该也不会有性能消耗，有更好的建议？

**Comment by imliujun** [comment]
不好意思了，我直接调用 Tab 的 showSignCountView 方法，之前没看到QMUITabSegment也提供了showSignCountView方法。
