### ISSUE TITLE
mCollapsingTopBarLayout有没有控制展开和收缩的方法

### ISSUE THREAD

**Issue by androidflying** [QMUI/QMUI_Android#390]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

**Comment by cgspine** [comment]
外层控制: QMUIAppBarLayout.setExpanded

**Comment by androidflying** [comment]
Thanks
