### ISSUE TITLE
QMUIProgressBar

### ISSUE THREAD

**Issue by Theoneee** [QMUI/QMUI_Android#396]
### 运行环境 ###

- [x] 设备型号：如：MIEZU 15
- [x] 设备系统版本：如 `Android 7.1.1`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.1.5`

### 具体问题描述 ###

 mQMUIProgressBar.setProgress(percent);

如图所示，上面的是一般的Progress，下面的是QMUI的。
正常的Progress都已经显示了，但是QMUI的还是不没有更新进度。

ps: 网络慢进度更新的速度慢时不会出现此情况。

// 更新进度
`   int percent = intent.getIntExtra(UpdateApkService.UPDATE_PROGRESS_PERCENT, 0);
    tvDes.setText(percent + "%");
    mProgress.setProgress(percent);
    mQMUIProgressBar.setProgress(percent);`

#### 问题截图 ####
![s80919-174801](https://user-images.githubusercontent.com/32156330/45745917-832ebe00-bc34-11e8-9154-68736d3696ad.jpg)

**Comment by Theoneee** [comment]
![s80919-175415](https://user-images.githubusercontent.com/32156330/45746141-1b2ca780-bc35-11e8-943e-c8386043a230.jpg)
这是网络慢时，显示的是正常的。

**Comment by Theoneee** [comment]
Demo里显示时没问题的。   parseValueToWidth 这个方法没有吧。。。

大佬有什么要问的测试的说一下就行了。请不要说您。。。这是我们这群受益者应该做的。

**Comment by cgspine** [comment]
![image](https://user-images.githubusercontent.com/7828876/46252858-6484be80-c4a1-11e8-8828-6c4415f83309.png)
如果没有刷新，应该是 drawRect 没被调用，或者 parseValueToWidth 计算出错了

**Comment by WinnieZy** [comment]
请问这个是怎么解决？我这里也出现这样的问题，网速快的时候基本上都没看到出进度条
