### ISSUE TITLE
错误: 找不到符号，类 QDWidgetContainer[自动编译生成类]无法生成

### ISSUE THREAD

**Issue by wangweiwell** [QMUI/QMUI_Android#398]
### 运行环境 ###

- [x] 设备型号：如：`Mi 6`
- [x] 设备系统版本：如 `Android 8.0.0`
- [x] Gradle 版本：如 `3.1.4`
- [x] QMUI Android 版本：`1.1.7`

**### 具体问题描述 ###**
错误: 找不到符号
符号:   类 QDWidgetContainer
位置: 类 QDDataManager

#### 问题截图 ####
已查看此类问题相关Issues，但是问题依然存在，实在无解，故在此求助！
![1](https://user-images.githubusercontent.com/36321770/45916398-161b6280-be98-11e8-8a30-4329051d4e05.png)
app的build.gradle相关配置如下：
    //QMUI
    implementation project(':lib')
    implementation 'com.qmuiteam:qmuilint:1.0.1'
    implementation 'com.qmuiteam:arch:0.1.4'
    implementation 'com.qmuiteam:qmui:1.1.7'
    annotationProcessor project(':compiler')
可以看出，fragment下面的都自动编译生成了类文件，
![2](https://user-images.githubusercontent.com/36321770/45916429-ace81f00-be98-11e8-9a74-a3f69605019b.png)
唯独QDWidgetContainer没有生成，不管怎么配置，操作，百度Google，都搞不好
![3](https://user-images.githubusercontent.com/36321770/45916449-0a7c6b80-be99-11e8-82da-3ba87dec705a.png)
很无解，不知道问题出在哪里，请指教！
想删掉QDDataManager，但该类被引用46次，又不能删，我就想知道怎么把这个类编译出来

#### 异常日志（堆栈） ####

@cgspine 感谢提供帮助！

**Comment by cgspine** [comment]
![image](https://user-images.githubusercontent.com/7828876/46191861-a855b780-c32b-11e8-9ac4-51ce21b3bb53.png)

compiler 的 Processor 里目前写死了一些 package 路径，你更改了 package 路径，因此可能这里生成失败了。
