### ISSUE TITLE
建议分离成多个库

### ISSUE THREAD

**Issue by JakeWoki** [QMUI/QMUI_Android#4]
毕竟不是每个都需要的。另设置状态栏黑色字体图标setStatusBarLightMode，建议返回是否设置成功。QMUIEmptyView应该增加图片，loading最好可以自定义

**Comment by cgspine** [comment]
40d2a02f1e6ca5a540eee9c1dad42971d4553b89 add return value for method setStatusBarLightMode

**Comment by MoLice** [comment]
#22 重复
