### ISSUE TITLE
QMUICollapsingTopBarLayout 小米手机问题

### ISSUE THREAD

**Issue by zhengjianan1993** [QMUI/QMUI_Android#40]
### 运行环境 ###

- [x] 设备型号：如：红米2
- [x] 设备系统版本： Android 4.4.4，MIUI 9
- [x] QMUI Android 版本：`1.0.3`

### 具体问题描述 ###
在小米手机上(4.4.4) Demo 程序中的QMUICollapsingTopBarLayout会出现白色的情况，QMUIViewPager的文字挤到了状态栏上面；如下图：
#### 问题截图 ####
![image](https://user-images.githubusercontent.com/12541653/30545778-39db38ce-9cbd-11e7-9f87-490a5e601b6c.png)
![image](https://user-images.githubusercontent.com/12541653/30545825-57be83f0-9cbd-11e7-8413-136e37735816.png)

**Comment by cgspine** [comment]
fixed in version 1.0.4
