### ISSUE TITLE
只支持Fragement滑动退出？Activity呢？

### ISSUE THREAD

**Issue by KomoriWu** [QMUI/QMUI_Android#409]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

**Comment by cgspine** [comment]
可以看看 #238 。 暂时只支持 Fragement。

**Comment by cgspine** [comment]
现在可以升级到 0.2.0 了, 支持 Activity 手势返回

**Comment by KomoriWu** [comment]
ok 。谢谢哈
