### ISSUE TITLE
是否会有QMUIRecycleView系列

### ISSUE THREAD

**Issue by NicodeLee** [QMUI/QMUI_Android#41]
### 使用建议 ###

- QMUI系列有好几个ListView系列如：QMUIAnimationListView、QMUICommonListItemView、QMUIGroupListView，是否会有QMUIRecycleView呢。

**Comment by chanthuang** [comment]
目前没有，是因为暂时还没有遇到特别有封装价值、可复用性高的功能。
很乐意交流一下，如果有，那么你期望 QMUIRecyclerView 会包含功能呢？

**Comment by NicodeLee** [comment]
- 一般常用的场景点击、长按、分割线、快速滚动条（希望有这个，官方一直没有）

- 动画、head、foot、这些RecyclerView库子已经很多

- 其他可能跟QMUILiveView差不多

**Comment by cgspine** [comment]
fastScroll官方的已经来了 https://developer.android.com/topic/libraries/support-library/revisions.html#26-0-0

![image](https://user-images.githubusercontent.com/7828876/30574101-6030307a-9d2a-11e7-9916-b8d804441710.png)
