### ISSUE TITLE
QMUISegment怎么单独使用

### ISSUE THREAD

**Issue by Theoneee** [QMUI/QMUI_Android#411]
只做TAB使用，不关联ViewPager

 
` 
addTab( R.drawable.index_stock_icon,"库存");
addTab( R.drawable.index_recipes_today_icon,"今日食谱");
addTab( R.drawable.index_image_center_icon,"影像中心");
addTab( R.drawable.index_notice_icon,"公告");
addTab( R.drawable.index_scan_code,"扫一扫");
 mTabSegment.setMode(QMUITabSegment.MODE_FIXED);
 //普通文字颜色
 mTabSegment.setDefaultNormalColor(ContextCompat.getColor(_mActivity, the.one.anastasia.R.color.white));
//选中时文字颜色
mTabSegment.setDefaultSelectedColor(ContextCompat.getColor(_mActivity, the.one.anastasia.R.color.white));
 //是否有 Indicator
mTabSegment.setHasIndicator(false);

 mTabSegment.setOnTabClickListener(new QMUITabSegment.OnTabClickListener() {
            @Override
            public void onTabClick(int index) {

            }
        });
    }

    private void addTab(int resId,String title){
        mTabSegment.addTab(new QMUITabSegment.Tab(
                ContextCompat.getDrawable(_mActivity, resId),
                null,
                title, false
        ));
    }`

**Comment by androidflying** [comment]
github挂了

**Comment by cgspine** [comment]
`addTab` 后调用 `notifyDataChanged` 就可以触发 View 更新

**Comment by Theoneee** [comment]
好的。非常感谢~
