### ISSUE TITLE
怎么单独使用QMUISegment

### ISSUE THREAD

**Issue by Theoneee** [QMUI/QMUI_Android#413]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

### 具体问题描述 ###

不结合ViewPager使用。正常配置后无法显示。。。

**Comment by cgspine** [comment]
`addTab` 后需要主动调用 `notifyDataChanged`
