### ISSUE TITLE
我被屏蔽了嘛，怎么发布了Issue

### ISSUE THREAD

**Issue by Theoneee** [QMUI/QMUI_Android#414]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

**Comment by cgspine** [comment]
没有屏蔽啊，这不是发布 issue 成功了吗？
