### ISSUE TITLE
下拉刷新对recyclerview存在一定问题

### ISSUE THREAD

**Issue by wangshaolei** [QMUI/QMUI_Android#42]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6P`
- [x] 设备系统版本：如 `Android 6.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.0.0`

### 具体问题描述 ###
下拉刷新组件里面包listview 或 other view 下拉触摸灵敏度 要高于里面包 recyclerview
比如里面我放了个recyclerview添加了 一个header，我触摸item下滑  和 触摸header下滑，灵敏度明显不一样。
不知道你们有没有感觉
#### 问题截图 ####
无法截图，只能靠感觉

**Comment by cgspine** [comment]
恩，确实存在这种感觉，我改改

**Comment by wangshaolei** [comment]
@cgspine good

**Comment by cgspine** [comment]
fixed in version 1.0.4

**Comment by wangshaolei** [comment]
@cgspine thanks
