### ISSUE TITLE
QMUITopBarLayout在style中设置qmui_topbar_height高度后沉浸式状态栏会有问题

### ISSUE THREAD

**Issue by as15108412898** [QMUI/QMUI_Android#424]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 6.0`
- [x] Gradle 版本：如 `3.1.2`
- [x] QMUI Android 版本：`1.1.3`

### 具体问题描述 ###
style中设置qmui_topbar_height高度后出现问题 , 请问要怎么解决
#### 问题截图 ####
![image](https://user-images.githubusercontent.com/22098557/47765045-0d257880-dd03-11e8-962e-aa03402f0e27.png)
![image](https://user-images.githubusercontent.com/22098557/47765067-24fcfc80-dd03-11e8-970b-6f04804624e0.png)
![image](https://user-images.githubusercontent.com/22098557/47765076-2dedce00-dd03-11e8-9c9b-9b19d8c401b2.png)

**Comment by cgspine** [comment]
你在 QMUITopBarLayout 上设置的背景？ 我猜是设置背景导致padding丢失导致的，可以用 `QMUIViewHelper.setBackgroundKeepingPadding`

**Comment by as15108412898** [comment]
已经找到问题所在 , 是图片的原因 ...
