### ISSUE TITLE
QMUITopBarLayout增加搜索

### ISSUE THREAD

**Issue by sollyu** [QMUI/QMUI_Android#425]
### 运行环境 ###

- [x] 设备系统版本： `5.1.0`
- [x] 设备型号：`雷电模拟器`
- [x] Gradle 版本： `3.2.0`
- [x] QMUI Android 版本：`1.1.6`

### 具体问题描述 ###
请问怎么添加搜索功能？

**Comment by cgspine** [comment]
`addLeftView`, `addRightView`,`setCenterView` 均可以传入一个自定义的 View，你可以根据需要传入自定义的搜索 View
