### ISSUE TITLE
消息类型的对话框操作按钮被挤走，显示不全

### ISSUE THREAD

**Issue by MZCretin** [QMUI/QMUI_Android#430]
### 运行环境 ###

- [x] 设备型号：如：`Redmi 5 Plus`
- [x] 设备系统版本：如 `Android 7.1.2`
- [x] Gradle 版本：如 `3.2.0`
- [x] QMUI Android 版本：`1.1.3`

### 具体问题描述 ###
使用如下的方式创建一个消息类型的对话框，当内容超过一定行数的时候，测试为10行的时候，下面的操作按钮会被挤下去，如图01；当内容非常多的时候，对话框内容区又会被撑开，操作按钮又会回来，如图02。
#### 问题截图 ####
![图01](https://upload-images.jianshu.io/upload_images/2356659-9f0dc263629a3d25.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![图02](https://upload-images.jianshu.io/upload_images/2356659-e91f29cdde886d5c.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

#### 异常日志（堆栈） ####
无

**Comment by MZCretin** [comment]
1.1.6已经修复了

**Comment by Payphone7** [comment]
> 1.1.6已经修复了

我用的1.2.0也出现这个问题，小米mix2s  android 9.0

**Comment by Payphone7** [comment]
1.1.6确实没问题了，但是1.2.0还是这样
