### ISSUE TITLE
关于使用QMUIBottomSheet.BottomGridSheetBuilder报错android.view.InflateException:Binary XML file line #8: Failed to resolve attribute at index 0: TypedValue{t=0x2/d=0x7f01001c a=-1}

### ISSUE THREAD

**Issue by Demonhuang** [QMUI/QMUI_Android#432]
### 运行环境 ###

- [x] 设备型号：小米Mix2
- [x] 设备系统版本：Android8.0
- [x] Gradle 版本：3.1.1
- [x] QMUI Android 版本：`1.1.3`

### 具体问题描述 ###
如题

#### 问题截图 ####
![image](https://user-images.githubusercontent.com/11385157/48455946-24329300-e7f8-11e8-949a-5585ca801d8e.png)

**Comment by cgspine** [comment]
context error
