### ISSUE TITLE
QMUIRoundButton禁用效果

### ISSUE THREAD

**Issue by kingsollyu** [QMUI/QMUI_Android#434]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

### 具体问题描述 ###
看了`QMUIRoundButton`注释说如下，之前enable的效果都是用background实现的，现在该如何实现禁用效果呢？
```
注意: 因为该控件的圆角采用 View 的 background 实现, 所以与原生的 <code>android:background</code> 有冲突。
```

**Comment by cgspine** [comment]
用 qmui_backgroundColor 代替， 一样可以传 selector

**Comment by kingsollyu** [comment]
好的，还没有尝试，回头尝试一下，暂时关闭
