### ISSUE TITLE
Theme中修改QMUIRoundButton属性没有生效

### ISSUE THREAD

**Issue by TianDehua** [QMUI/QMUI_Android#44]
### 运行环境 ###

- [x] 设备型号：如：`小米 5`
- [x] 设备系统版本：如 `Android 7.0`
- [x] Gradle 版本：如 `2.2.0`
- [x] QMUI Android 版本：`1.0.3`

### 具体问题描述 ###
你好，我基于demo在style.xml theme中修改qmui_round_btn_text_color属性，期望改变按钮的默认颜色，我修改了s_btn_blue_text.xml如下：
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:color="@color/app_color_blue_disabled" android:state_enabled="false" />
    <item android:color="@color/app_color_blue_pressed" android:state_pressed="true" />
    <item android:color="@color/qmui_config_color_black" />****
</selector>
但是没起作用，运行结果字体颜色并没有发生改变。还是 QMUI.Compat.NoActionBar 中的样式。

#### 问题截图 ####
![20170922134214](https://user-images.githubusercontent.com/8803718/30730743-da471572-9f9b-11e7-92d1-4297dc7573a0.png)

**Comment by cgspine** [comment]
fixed in version 1.0.4
