### ISSUE TITLE
如何更改popup 中 arrow up箭头的颜色？

### ISSUE THREAD

**Issue by zhangxinars** [QMUI/QMUI_Android#441]
### 运行环境 ###

- [x] QMUI Android 版本：`1.1.7`

### 具体问题描述 ###

请问如何更改popup 中 arrow up箭头的颜色？

**Comment by cgspine** [comment]
```
<attr name="qmui_popup_bg" format="reference"/>
<attr name="qmui_popup_arrow_down" format="reference"/>
<attr name="qmui_popup_arrow_up" format="reference"/>
<attr name="qmui_popup_arrow_up_margin_top" format="dimension"/> <!-- 一般与qmui_popup_bg上阴影相等 -->
<attr name="qmui_popup_arrow_down_margin_bottom" format="dimension"/> <!-- 一般与qmui_popup_bg下阴影相等 -->
```

在 theme 里面提供相应的资源覆盖 qmui 的就可以了

**Comment by zhangxinars** [comment]
@cgspine 
我这样实现了...自己切了一个不同颜色的三角形
ImageView arrowUp = popup.getDecorView().findViewById(R.id.arrow_up);
arrowUp.setImageDrawable(getResources().getDrawable(R.mipmap.triangle));
感谢您的解答
