### ISSUE TITLE
沉浸式状态栏问题

### ISSUE THREAD

**Issue by leeyun** [QMUI/QMUI_Android#448]
### 运行环境 ###

- [x] 设备型号：如：`Pixel 2`
- [x] 设备系统版本：如 `Android 9.0`
- [x] Gradle 版本：如 `3.2.1`
- [x] QMUI Android 版本：`1.1.7`

### 具体问题描述 ###
单Activity多fragment，第一个fragment添加进来状态栏是正常的，第二个fragment的状态栏却消失了
#### 问题截图 ####
![image](https://user-images.githubusercontent.com/11530379/49005713-58b43080-f1a2-11e8-92ea-08fd7a1f8301.png)
![image](https://user-images.githubusercontent.com/11530379/49006129-556d7480-f1a3-11e8-8f73-dcbb32336fb8.png)
![image](https://user-images.githubusercontent.com/11530379/49006171-6c13cb80-f1a3-11e8-98b3-ca18effaeeeb.png)

Activity中的设置（layout中的代码

```
<com.qmuiteam.qmui.widget.QMUIWindowInsetLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/container"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MainActivity"
    >
</com.qmuiteam.qmui.widget.QMUIWindowInsetLayout>
```
）
#### Layout Inspector 文件([如何获取](https://github.com/QMUI/QMUI_Android/wiki/%E6%8F%90%E4%BE%9B-Layout-Inspector-%E6%96%87%E4%BB%B6)) ####
问题页面信息
[com.ls.android_2018.11.26_17.37.li.zip](https://github.com/QMUI/QMUI_Android/files/2614837/com.ls.android_2018.11.26_17.37.li.zip)

**Comment by cgspine** [comment]
在第二个 fragment onCreateView(三参数) 或者 onActivityCreated 里调用了 `ViewCompat.requestApplyInsets(view); ` 没?

**Comment by leeyun** [comment]
@cgspine   ```
 if (activity != null) {
      Timber.e("requestApplyInsets")
      QMUIViewHelper.requestApplyInsets(activity?.window)
    }
```
basefragment有进行调用的

**Comment by cgspine** [comment]
![image](https://user-images.githubusercontent.com/7828876/49066325-b35d9300-f25b-11e8-8658-78d6dd0f2b22.png)

`QMUIWindowInsetLayout` 只能管理它的直接子 view。 而你的 `fitSystemWindows = true` 应该添加在了 `QMUITopBarLayout` 上，所以没被 `QMUIWindowInsetLayout` 管理到。

你可以把 `linearLayout` 改为 `QMUIWindowInsetLayout`，不过这样要更改布局方式, 可以参考 QMUIDemo。 或者你可以实现自定义的 `LinearLayout`，实现 `IWindowInsetLayout` 接口,  可参考 `QMUIWindowInsetLayout` 。

**Comment by leeyun** [comment]
我好的懂了，我调整下结构。
