### ISSUE TITLE
Android 组件跟IOS不统一，IOS的写得比较全面，Android 组件数量和效果稍微差了一点

### ISSUE THREAD

**Issue by rmtic** [QMUI/QMUI_Android#45]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

**Comment by MoLice** [comment]
QMUI 在 Web / iOS / Android 3 个平台有其分别的框架，框架的设计思路及要解决的场景问题是一致的，但不同平台的框架之间并不存在“表现统一”的需求，短期内我们也不会将其作为 QMUI 的发展目标之一，所以 Android 和 iOS 的组件不统一是正常的。

另外你的提问里有两个点需要确认：
1. 你提到的 Android 的组件不够全面，具体是指有什么组件你认为很常用但在 QMUI Android 里没提供呢？
2. Android 组件效果稍微差了一点，你指的效果是指 UI 表现上的效果？代码上的使用方式不合理？还是组件本身的代码实现写得质量欠佳？

**Comment by rmtic** [comment]
QMUI，很好，很适用于快速开发。但是，我在使用IOS和Android的Demo后，只是体验上，感觉IOS的效果比较理想，组件涵盖的范围比较广，更能提显QMUI对开发者的帮助。比方说，我开发Android，我其实是不想界面，功能跟IOS差太远，甚至是部分功能或则效果IOS有,而Android 没有。
我觉得UI和功能不能统一，QMUI也就没有存在的意义。多参考IOS的DEMO和功能，他写的确实不错。
还有一点，QMUI官方文档写的不是很详细。

**Comment by MoLice** [comment]
嗯是的，抛开具体的框架实现方式，按我的理解，你预期的解决方案应该是“最好能保证我的 App 在不同的平台下拥有相同的表现”，换句话说，是否类似“一套代码通吃多个平台”？如果是的话，那是否用 RN 会比用 QMUI 更合适？

因为在我们日常的开发中，“不同平台交互、设计保持一致”并非是主要着力点，我们倾向于在不同平台使用平台自身特有的风格，所以可能在“你的预期和 QMUI 的目标”这两点上是存在分歧的。
