### ISSUE TITLE
QMUIRadiusImageView 使用 glide时第一次不显示

### ISSUE THREAD

**Issue by vihuela** [QMUI/QMUI_Android#46]
### 运行环境 ###

- [x] 设备型号：nexus 5x、5
- [x] 设备系统版本：Android 7.1
- [x] Gradle 版本：4.1
- [x] QMUI Android 版本：1.0.2

### 具体问题描述 ###
QMUIRadiusImageView 使用 glide时第一次不显示，表现为第一次运行时
xml:
<com.qmuiteam.qmui.widget.QMUIRadiusImageView
                android:layout_width="96dp"
                android:id="@+id/iv_head"
                android:layout_height="wrap_content"
                android:clickable="true"
                android:src="@mipmap/ic_default_head"
                app:qmui_border_width="0dp"
                />

**Comment by vihuela** [comment]
Picasso没有这个问题

**Comment by littlejigege** [comment]
用了placeholder吧，glide一直都有这个问题，glide github readme有说的

**Comment by vihuela** [comment]
@littlejigege 看到了，谢谢

**Comment by tpnet** [comment]
@littlejigege @vihuela   我加了placeholder，，第一次加载也不显示，老铁，救命

**Comment by vihuela** [comment]
@tpnet 用picasso就好了

**Comment by tpnet** [comment]
@vihuela  不能随便换啊，，有解决方法吗?   @cgspine

**Comment by tpnet** [comment]
into的时候用SimpleTarget吧，可以解决

**Comment by lianghuiyong** [comment]
使用SimpleTarget的话，就失去了glide的优势了

**Comment by tianshaokai** [comment]
glide 有这个issues 吗？有没有链接地址
