### ISSUE TITLE
Demo中fragment页面切换动画问题

### ISSUE THREAD

**Issue by LuckyStar521** [QMUI/QMUI_Android#47]
### 运行环境 ###

- [x] 设备型号：小米6
- [x] 设备系统版本：Android 7.1.1
- [x] Gradle 版本：2.3.3
- [x] QMUI Android 版本：1.0.3

### 具体问题描述 ###
在Demo中随便点击一个item打开页面，快速按返回键关闭页面，也就是在Fragment动画执行中快速关闭页面会导致上一个界面所有按钮无法点击，没有响应

**Comment by cgspine** [comment]
fixed in version 1.0.4

**Comment by LuckyStar521** [comment]
请问下这个问题是怎么解决的，源码没看到相关的代码啊

**Comment by cgspine** [comment]
之前的这个提交在support版本27之前是可以正常工作的。但是27版本support包更改了fragmentManager的实现。之前的fix也失效了。

之所以有问题，是因为我想复用View，就是切换到新界面再切换回来，View不用重新构造。bug造成的原因是View 的 dettach 和 attach 遇到动画会出现混乱，我在[这里](http://cgsdream.org/record?tag=598a653b8a43164218ddcc88)又记录

![image](https://user-images.githubusercontent.com/7828876/34372063-20ff9338-eb0d-11e7-80cc-20f835ec3a90.png)

升级到support 27后，原本的 hack 修复已经不能正常使用，只得放弃复用view，将onCreate的逻辑移到onCreateView中

**Comment by LuckyStar521** [comment]
嗯，感谢回复，我也复用了view出现的这个问题，但是不复用view的话使用fragment replace的方式打开新的fragment并add回退栈，然后popBackStack就会导致上一个页面的动态加载的一些view和数据丢失，目前准备使用hide、show来解决，不知有没有更好的方式

**Comment by LuckyStar521** [comment]
之前的版本的hack解决方式也看到了，但是如你所说在新版的support中失效了

**Comment by cgspine** [comment]
onResume里重新绑定数据到View上就可以了吧
