### ISSUE TITLE
集成sdk的时候会有values属性冲突，可能是集成了不同版本的android support库，建议分离出来

### ISSUE THREAD

**Issue by longpenghn** [QMUI/QMUI_Android#5]

**Comment by JakeWoki** [comment]
compile('com.qmuiteam:qmui:1.0.0', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
可以这样引用

**Comment by chanthuang** [comment]
如 JakeWoki 所说的，如果项目已引入了 android support 库，可以 exclude

**Comment by longpenghn** [comment]
@JakeWoki @chanthuang 是的   已经这么干了

**Comment by JakeWoki** [comment]
@chanthuang 弄成aar更好点
