### ISSUE TITLE
 java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by yinhe-zeng** [QMUI/QMUI_Android#50]
### 运行环境 ###

- [x] 设备型号：荣耀 CHM-CL00 
- [x] 设备系统版本：Android 6.0.1,level 23
- [x] QMUI Android 版本：1.0.3
#### 异常日志（堆栈） ####
 java.lang.UnsupportedOperationException
Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x7f010065 a=3}
com.qmuiteam.qmui.widget.dialog.QMUIDialogBuilder.create(QMUIDialogBuilder.java:234)

真实使用情况与demo有点差距，非常不灵活，折腾一下午，放弃了......

**Comment by cgspine** [comment]
你没有继承 QMUI.Compat 主题？

**Comment by yinhe-zeng** [comment]
哦！是的！继承了就正常了~~
