### ISSUE TITLE
提一点小小的个人建议

### ISSUE THREAD

**Issue by BigExcalibur** [QMUI/QMUI_Android#51]
框架非常好，流畅度高，而且挺好看的。

但是可插拔性不太好，各组件对于主题等依赖严重。个人建议可以稍微把组件耦合程度降低，便于修改源码以方便自定义，毕竟UI这个东西做得越死用处越小。

**Comment by chanthuang** [comment]
> 可插拔性不太好，各组件对于主题等依赖严重

目前确实有这个问题。我们也会在这方面进行优化，感谢建议。

**Comment by xingxingxiaoyu** [comment]
我刚发现不设主题的话，里面的东西貌似都不能用，会有资源找不到，控件的xml属性定义的资源，设置了主题就可以了

**Comment by cgspine** [comment]
对，QMUI目前强依赖于主题
