### ISSUE TITLE
PRO 6 在9月26号升级了Flyme6.2.0.0A,基于Android 7.0; 状态栏颜色设置为 白色 改变不了

### ISSUE THREAD

**Issue by xiaozhang-carl** [QMUI/QMUI_Android#53]
### 运行环境 ###

- [x] 设备型号：Meizu Pro6
- [x] 设备系统版本： `Android 7.0`
- [x] Gradle 版本：如 `2.3.3`

**Comment by xiaozhang-carl** [comment]
布局文件
<LinearLayout        
      android:id="@+id/llRoot"         
      android:layout_width="match_parent"         
      android:layout_height="match_parent"        
      android:background="#ffffff"
      android:fitsSystemWindows="true"
      android:orientation="vertical">

activity 代码设置
        QMUIStatusBarHelper.translucent(this); // 沉浸式状态栏
        QMUIStatusBarHelper.setStatusBarLightMode(this);

**Comment by cgspine** [comment]
fixed in version 1.0.4
