### ISSUE TITLE
多选对话框的选择，当item数量过多会无法滚动，是否考虑做一个滚动列表

### ISSUE THREAD

**Issue by qq781548819** [QMUI/QMUI_Android#54]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

**Comment by cgspine** [comment]
恩，这应当当做 bug 来修复

**Comment by cgspine** [comment]
fix in version [1.0.5](https://github.com/QMUI/QMUI_Android/releases/tag/1.0.5)
