### ISSUE TITLE
QMUIFloatLayout 居左布局时换行逻辑 bug

### ISSUE THREAD

**Issue by chanthuang** [QMUI/QMUI_Android#61]
### 运行环境 ###

- [x] QMUI Android 版本：`1.0.4`

### 具体问题描述 ###

`QMUIFloatLayout` 换行时的Y轴偏移值计算错误

#### 问题截图 ####
![screen_20171010_153546](https://user-images.githubusercontent.com/1695414/31374496-d663adaa-ad63-11e7-88e0-19108e82a9e1.png)

**Comment by cgspine** [comment]
fix in version [1.0.5](https://github.com/QMUI/QMUI_Android/releases/tag/1.0.5)
