### ISSUE TITLE
单选菜单类型对话框在华为mate9上不显示选中状态

### ISSUE THREAD

**Issue by imliujun** [QMUI/QMUI_Android#62]
### 运行环境 ###

- [x] 设备型号：华为 mate9
- [x] 设备系统版本：Android 7.0
- [x] Gradle 版本：如 `2.2.3`
- [x] QMUI Android 版本：`1.0.4`

### 具体问题描述 ###
在华为mate9上显示单选菜单型对话框只有初始化时调用了setCheckedIndex()的默认选中项有选中状态，其他的Item都没有选中状态
官方demo和我自己项目里面集成在华为mate9上面都有这个问题
其他手机正常显示没有问题

#### 问题截图 ####
![2017-10-13 12_57_34](https://user-images.githubusercontent.com/9779970/31531053-1211cf74-afaa-11e7-8cda-92c83217b988.gif)

**Comment by amszsthl** [comment]
我也遇到这个问题。目前有好的解决办法吗？

**Comment by cgspine** [comment]
1.0.8 修复了这个问题，可以试试
