### ISSUE TITLE
5.0系统以下，右边ImageView不支持SVG图片

### ISSUE THREAD

**Issue by t1030338120** [QMUI/QMUI_Android#65]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

#### 异常日志（堆栈） ####
1.0.4版本

在android 4.4系统上设置右边图片时使用SVG格式的不显示，希望QMUIAlphaButton/QMUIAlphaImageButton/QMUIAlphaTextView控件，直接继承
AppCompatxxx

**Comment by t1030338120** [comment]
1.0.4版本

**Comment by cgspine** [comment]
changed in new version
