### ISSUE TITLE
CheckableDialogBuilder not support slide when item count too many

### ISSUE THREAD

**Issue by yz1309** [QMUI/QMUI_Android#67]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

**Comment by jijiaman** [comment]
nikankkn  di    oirewniosfopwr  a IWIPQWL SF

**Comment by cgspine** [comment]
fix in version [1.0.5](https://github.com/QMUI/QMUI_Android/releases/tag/1.0.5)
