### ISSUE TITLE
QMUITabSegment中如何在弹出的子framgent中更新QMUITabSegment子页面中的控件

### ISSUE THREAD

**Issue by nanzexu** [QMUI/QMUI_Android#70]
### 运行环境 ###

- [x] 设备型号：如：`mate9`
- [x] 设备系统版本：如 `Android 7.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.0.4`

我的QMUITabSegment页面中有个子framlayout:HomeMyController【系统设置】,在这个界面中有个会startFragment一个设置打印机的Fragment：DeviceListFragmetn.
现在我需要在DeviceListFragmetn完成并关闭后，修改HomeMyController界面上的一个textView的值，如何做到？
我现在的方法比较土，在DeviceListFragmetn中
 @Override
    protected void popBackStack() {
        super.popBackStack();

        //刷新tab页面的数据，虽然很土，但是真不知道要如何解决
        HomeFragment homeFragment= (HomeFragment) getBaseFragmentActivity().getCurrentFragment();
        homeFragment.mTabSegment.selectTab(1);
        homeFragment.mTabSegment.selectTab(2);
        Log.i("test:",getBaseFragmentActivity().getCurrentFragment().getTag());
    }
并修改PagerAdapter中的
 @Override
        public Object instantiateItem(final ViewGroup container, int position) {

            HomeController page = mPages.get(Pager.getPagerFromPositon(position));
            ViewGroup.LayoutParams params = new ViewGroup.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT);
            container.addView(page, params);
            page.refurbish();//界面自己刷新
            return page;
        }

除此之外有没有更简便的方法？

**Comment by cgspine** [comment]
处理这类问题，我觉得如果使用EventBus或者RxBus，会优雅一点
