### ISSUE TITLE
QMUITabSegment 初始滚动问题

### ISSUE THREAD

**Issue by GaryMr** [QMUI/QMUI_Android#71]
### 运行环境 ###

- [x] 设备型号：如：`魅族MX5`
- [x] 设备系统版本：如 `Android 5.1`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.0.4`

### 具体问题描述 ###
QMUITabSegment 模式为滚动时，viewpager通过代码初始选择最后一个tab，QMUITabSegment显示不正确，还是在第一屏，没有移动。

**Comment by cgspine** [comment]
fix in version [1.0.5](https://github.com/QMUI/QMUI_Android/releases/tag/1.0.5)
