### ISSUE TITLE
是否考虑添加QMUIDropDown（多条件筛选下拉菜单View）

### ISSUE THREAD

**Issue by NicodeLee** [QMUI/QMUI_Android#78]
### 具体问题描述 ###

下拉菜单这个场景挺普遍的，类似美团，掌上生活等各类的综合咨询，平台购物类的app都遇到。
刚想用`QMUIPopup`扩展下拉菜单，发现宽高不能适配。
另外，GitHub搜索下，也有实现的（[search DropDown](https://github.com/search?l=Java&o=desc&q=DropDown&s=stars&type=Repositories&utf8=%E2%9C%93) ）总想看下如果你们来做会怎样实现。
冒昧提issues，是否会考虑添加`QMUIDropDown`

**Comment by cgspine** [comment]
QMUIPopup扩展过程有什么问题？

**Comment by NicodeLee** [comment]
扩展遇到的问题：
1. 弹出的view不全屏，会有小角标
2.内容view的宽高适配不了。

![图片描述](http://7xlc12.com1.z0.glb.clouddn.com/65CCE787-235A-4A2A-834D-D97CC4A60094.png)

**Comment by cgspine** [comment]
1. 那个小三角形的位置错误主要是由于Popup背景有阴影,而你的箭头太靠边了，可以在 theme 中改qmui_popup_bg，提供小的阴影
2. PopupWindow 必须要提供一个定宽的 view，这点需要改进。 我在使用定宽的QMUIFloatLayout 时，并不会出现高度错误，您内部的用的 View 是？

**Comment by NicodeLee** [comment]
- 内部是Recyclerview。

- 其实个人觉得Popupwindow也挺好用（网上说法会阻塞主线程这说法有点误导，按这说Dialog也阻塞了）。

- QMUI好像也有很多类型的【弹窗】【浮层】比如，QMUIViewHelper，QMUITipDialog（嘿，本来还以为是Toast），QMUIPopup，QMUIDialog（对应系统的Dialog），QMUIBottomSheet。
不知道再抽象出一个类似系统的Popupwindow是否会重复上面view或者偏离了本库的范畴。

**Comment by cgspine** [comment]
QMUIPopup 内部用的是 Popupwindow，现在在继续改造 QMUIBasePopup，修复它现在存在的一些问题
