### ISSUE TITLE
miui9状态栏黑色字体无效

### ISSUE THREAD

**Issue by AriesHoo** [QMUI/QMUI_Android#8]
### 运行环境 ###

- [x] 设备型号：如：`mi 6`
- [x] 设备系统版本：如 `Android 7.1.1`
- [x] Gradle 版本：如 `2.3.3`
- [x] QMUI Android 版本：`1.0`

### 具体问题描述 ###
mi6 android7.1.1 状态栏黑色无效，因为miui9改回原生黑白切换方案了

**Comment by AriesHoo** [comment]
mi6   android7.1.1  状态栏黑色无效，因为miui9改回原生黑白切换方案了

**Comment by zhangchaoxu** [comment]
MIUI 9「状态栏黑色字符」实现方法变更
7.7.13兼容Android原生方法

具体见：https://dev.mi.com/console/doc/detail?pId=1159

**Comment by AriesHoo** [comment]
这个我知道的

**Comment by chanthuang** [comment]
下个版本将修复这个问题。

**Comment by cgspine** [comment]
@AriesHoo 我安装官方文档所说，修改了实现，目测没有问题。不过由于刷 MIUI9 时，BL解锁需要等待审核，并没有用真机验证，你手上是否有 MIUI9 的机器？帮忙验证下？多谢

**Comment by cgspine** [comment]
1.0.1 版本已经 release

**Comment by tpnet** [comment]
@cgspine  你好，最新的QMUI  1.0.4在小米2最新miui9.7.11.9开发版、Android5.0 状态栏的文字颜色还是改不了，其他手机可以。

**Comment by cgspine** [comment]
好的，我找台小米2看看
