### ISSUE TITLE
能不能请你们在你们的Demo上多加点注释啊？想研读下你们的代码，谢谢了

### ISSUE THREAD

**Issue by xingxingxiaoyu** [QMUI/QMUI_Android#80]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

**Comment by cgspine** [comment]
我们会尽量完善注释信息。如果你觉得哪里不是很清晰，也欢迎提 issue 或者发邮件

**Comment by xingxingxiaoyu** [comment]
好的，谢谢了~
