### ISSUE TITLE
是否考虑QMUIGroupListView添加左边有图标的行样式

### ISSUE THREAD

**Issue by tpnet** [QMUI/QMUI_Android#81]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

### 具体问题描述 ###
QMUIGroupListView的行样式中，没有发现 可以在左边添加图标。考虑添加吗

**Comment by cgspine** [comment]
![image](https://user-images.githubusercontent.com/7828876/32943415-012b39e6-cbc7-11e7-9cf7-c1e0179ebd22.png)
调用 setImageDrawable 可以添加左边的图标

**Comment by tpnet** [comment]
@cgspine 好的，谢谢，有QMUI的Android交流群吗

**Comment by cgspine** [comment]
暂时没有，感觉 Github issue 基本足够，后期可能会考虑添加其它交流方式
