### ISSUE TITLE
QMUICommonListItemView的DetailText能否支持设置CharSequence

### ISSUE THREAD

**Issue by a512509050** [QMUI/QMUI_Android#83]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

### 具体问题描述 ###
目前只有
```
setDetailText(StringBuilder text);
setDetailText(String text);
```
这样无法支持SpannableString。

或者说DetailText的位置可不可以添加一个设置图片的方法

**Comment by cgspine** [comment]
fix in [1.0.5](https://github.com/QMUI/QMUI_Android/releases/tag/1.0.5)
