### ISSUE TITLE
QMUITipDialog的扩展性是否不足？

### ISSUE THREAD

**Issue by tpnet** [QMUI/QMUI_Android#88]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

### 具体问题描述 ###

现在的TipDialog，只能通过Buiilder去生成，而且生成之后，不能修改， 例如我想修改提示的文字。。就需要去重新build一个Dialog出来。这样子的话，每次显示都new的话，是否对性能有影响？

**Comment by cgspine** [comment]
个人认为 TipDialog 是一个轻量级的组件，每次重新 new 应该没有多大的影响，系统的toast也是每次都重新 new 的

**Comment by AbstractPeople** [comment]
我只想偷个懒，想通过直接修改提示文字达到提示上传进度的效果，源码点进去，却发现没有一个控件设置Id

**Comment by cgspine** [comment]
使用 CustomBuilder 自定义布局？

**Comment by AbstractPeople** [comment]
> 使用 CustomBuilder 自定义布局？
