### ISSUE TITLE
请问NavigationView中Menu的颜色设置

### ISSUE THREAD

**Issue by ixxxxxx** [QMUI/QMUI_Android#89]
### 运行环境 ###

- [x] 设备型号：`Nexus 6P`
- [x] 设备系统版本：`Android 8.0`
- [x] Gradle 版本：`3.0.0`
- [x] QMUI Android 版本：`1.0.4`

### 具体问题描述 ###
你好，我在Activiy里面使用NavigationView作为侧边栏，然后menu布局里面的item都是使用的系统自带的图标，类似这样的
```
        <item
            android:id="@+id/nav_home"
            android:icon="@drawable/ic_menu_home"
            android:title="Home" />
```
现在使用QMUI后侧边栏item图标和文字颜色都改变了，我想重新设置为其他颜色，没有找到QMUI.Compat里面哪个属性是改变这个值的。

**Comment by cgspine** [comment]
![image](https://user-images.githubusercontent.com/7828876/33376802-10dcbb44-d54a-11e7-9773-9659bab406d3.png)
看它的源码，你可以在theme中更改 textColorSecondary 和 textColorPrimary 去改变图标和文字的默认颜色。 或者在 NavigationView 的 xml 添加 itemIconTint 和 itemTextColor 改当前 NavigationView 的
 item 的图标和文字颜色

**Comment by ixxxxxx** [comment]
感谢回复，这个textColorSecondary是android自带的吧？
使用QMUI之后，这个颜色就改变了，我还以为QMUI里面有个属性是改变这个值的。
