### ISSUE TITLE
build出错

### ISSUE THREAD

**Issue by david1025** [QMUI/QMUI_Android#9]
### 运行环境 ###

- [x] Gradle 版本：3.0.0-beta2
- [x] QMUI Android 版本：1.0.0

### 具体问题描述 ###
build出错
#### 问题截图 ####
![image](https://raw.githubusercontent.com/david1025/images/master/TIM%E6%88%AA%E5%9B%BE20170830223358.png)

**Comment by army650663** [comment]
+1

**Comment by cgspine** [comment]
Android Studio 3 Preview下才会存在这个问题。

StackOverflow 上的讨论：[https://stackoverflow.com/questions/45952607/error-style-attribute-androidattr-windowexitanimation-not-found](https://stackoverflow.com/questions/45952607/error-style-attribute-androidattr-windowexitanimation-not-found)

如 StackOverflow 上所讨论，目前可以通过在  gradle.properties 里添加 android.enableAapt2=true 解决。

**Comment by david1025** [comment]
请问，有计划解决在Android Studio 3 Preview出现的这个问题么？

**Comment by chanthuang** [comment]
会在下个版本解决这个问题。

**Comment by cgspine** [comment]
1.0.1 版本 fix 这个问题，请更新
