### ISSUE TITLE
编译不通过

### ISSUE THREAD

**Issue by xuqinghao1991** [QMUI/QMUI_Android#93]
### 运行环境 ###
Windows 10
- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `4.1`
- [x] QMUI Android 版本：`1.0.3`

#### 异常日志（堆栈） ####
C:\Users\xqh\Desktop\QMUI_Android-master\qmuidemo\build.gradle
Error:(4, 0) CreateProcess error=2, 系统找不到指定的文件。
<a href="openFile:C:\Users\xqh\Desktop\QMUI_Android-master\qmuidemo\build.gradle">Open File</a>

**Comment by xieyucheng** [comment]
gitVersion = cmd.execute().text.trim().toInteger()  把这句注释掉就好了

**Comment by cgspine** [comment]
QMUIDemo 的 versionCode 是通过 gitVersion 控制的。 
如果通过git clone 获取源码，则可以正常编译；如果通过 download 下载 zip 的形式下载源码，则需要修改 qmuidemo 目录下的 build.gradle 文件，硬编码一个 gitVersion

**Comment by baohexin** [comment]
注释掉不行啊

**Comment by didumeiyouxue** [comment]
gitVersion = cmd.execute().text.trim().toInteger()

这里的值改成随便一个整数就好，例如：
 gitVersion = 10

**Comment by didumeiyouxue** [comment]
gitVersion = cmd.execute().text.trim().toInteger()

这里的值改成随便一个整数就好，例如：
 gitVersion = 10

**Comment by captain991** [comment]
@didumeiyouxue 十分感谢
