### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by BeetleSxy** [QMUI/QMUI_Android#95]
### 运行环境 ###

- [x] 设备型号：如：`honor  8`
- [x] 设备系统版本：如 `Android 7.0`
- [x] Gradle 版本：如 `4.1`
- [x] QMUI Android 版本：`v1.0.3`

### 具体问题描述 ###
编译失败
#### 异常日志（堆栈） ####
Error:Could not find method ﻿apply() for arguments [{plugin=com.android.application}] on project ':qmuidemo' of type org.gradle.api.Project.
Consult IDE log for more details (Help | Show Log)

**Comment by cgspine** [comment]
是否和 #93 是同样的问题？

**Comment by BeetleSxy** [comment]
在git clone后遇到了 #93 问题参照解决方法后出现此问题

**Comment by cgspine** [comment]
你的Android Studio版本是多少？是否有尝试过 Build -> Clear Project ?

**Comment by BeetleSxy** [comment]
Android Studio 3.0 有尝试过 Clear Project
