### ISSUE TITLE
这个不支持侧滑吗？

### ISSUE THREAD

**Issue by BennyXXY** [QMUI/QMUI_Android#98]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

**Comment by cgspine** [comment]
QMUI 中没有手势返回的支持，因为还没有找到比外界开源更好的做法。外部开源的大多是只支持 activity， 也有支持fragemnt的如 http://www.jianshu.com/p/c7610170b36c。内部用的手势返回是把FragmentManager整个取出来修改，这样一来就无法享受到官方FragmentManager的更新了。

**Comment by cgspine** [comment]
QMUI 中没有手势返回的支持，因为还没有找到比外界开源更好的做法。外部开源的大多是只支持 activity， 也有支持fragemnt的如 http://www.jianshu.com/p/c7610170b36c 。内部用的手势返回是把FragmentManager整个取出来修改，这样一来就无法享受到官方FragmentManager的更新了。
