### ISSUE TITLE
QMUIQQFaceView使用.9背景图时表情位置问题

### ISSUE THREAD

**Issue by And009** [QMUI/QMUI_Android#99]
### 运行环境 ###

- [x] 设备型号：如：`MX note6'
- [x] 设备系统版本： `Android 7.0`
- [x] Gradle 版本： `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

### 具体问题描述 ###
具体情况如图所示，只有表情的时候表情全部跑上面去了
#### 问题截图 ####
![image](https://user-images.githubusercontent.com/22973635/33753898-bfe9c830-dc24-11e7-826a-1ffb8fa1fdfb.png)

**Comment by cgspine** [comment]
我这边测试并未出现异常，能否提供下List的itemView 的 布局和9png?

**Comment by And009** [comment]
-。-应该是我布局的问题，我给每个item末尾都加个空格就好了

**Comment by threedeer** [comment]
我也出现这个问题了。我试了下  加个空格确实可以。但是这应该就是bug
